'use strict';
// Kaserne: zentrale Gladiatorenübersicht mit Talentbewertung, Klassenvergleich und direkter Klassenzuweisung.
// Reine Anzeige und Verwaltung. Alle Zahlen stammen aus vorhandenen Berechnungen (g.potential, M.scoutScore, M.power);
// hier werden keine Stats, Potenziale, Kampf- oder Balancewerte verändert.
(()=>{
const M=window.MG,S=M.s,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ROLES=['Soldat','Fernkämpfer','Assassine'].filter(r=>M.roles.includes(r)),ICON={Soldat:'⚔',Fernkämpfer:'🏹',Assassine:'🗡'},PER_PAGE=20;
// Talentstufen nach dem vorhandenen allgemeinen Potenzial (g.potential, 1–100). Die Grenzen folgen der tatsächlichen Verteilung
// neuer Rekruten (32 Würfe, Mittel 62): gemessen an 6.000 erzeugten Rekruten und gegen die exakte Verteilung gerechnet.
// Anteil je Stufe: 6 % · 14 % · 25 % · 28 % · 19 % · 7,5 % · 1,2 % · 0,44 % · 0,14 % · 0,04 % (Prodigy: etwa 1 von 2.600).
const TIERS=[[91,'Prodigy'],[88,'Elite-Talent'],[85,'Ausnahmetalent'],[81,'Hochbegabt'],[75,'Talentiert'],[69,'Begabt'],[63,'Brauchbar'],[57,'Mittelmaß'],[50,'Unbegabt'],[0,'Nichtsnutz']];
const tierOf=t=>{const i=TIERS.findIndex(([min])=>t>=min);return {level:10-i,name:TIERS[i][1],min:TIERS[i][0]};};
const stars=level=>'★'.repeat(Math.round(level/2))+'☆'.repeat(5-Math.round(level/2));
const weaponName=id=>M.weaponDefs.find(w=>w.id===id)?.name||id;
// Vergleichswaffe für den Scout-Kampfwert: immer dieselbe Güte, nie ein zufälliges Lagerstück, keine Rüstung.
const REF_Q=1,refItems=new Map(),refItem=def=>{if(!refItems.has(def))refItems.set(def,M.makeItem('weapon',def,REF_Q));return refItems.get(def);};
const bare=(g,item=null)=>M.power({...g,enemyGear:{weapon:null,secondary:item,shield:null,armor:{}}});
// ---------- Werte je Gladiator, zwischengespeichert bis sich etwas Relevantes ändert ----------
const cache=new Map();
function signature(g){let n=0;for(const k in g.stats)n+=g.stats[k];for(const k in g.mastery)n+=g.mastery[k];for(const k in g.moves)n+=g.moves[k];return g.role+'|'+g.potential+'|'+g.fights+'|'+Math.round(M.health(g))+'|'+n.toFixed(2);}
function info(g){const sig=signature(g),hit=cache.get(g.id);if(hit&&hit.sig===sig)return hit;
 const talent=Math.round(M.clamp(g.potential??50,1,100)),tier=tierOf(talent),classes={};
 for(const role of ROLES){const now=M.scoutScore(g,role,false),cap=M.scoutScore(g,role,true);classes[role]={role,ist:now.score,pot:cap.score,weapon:cap.best.id,weaponPot:cap.best.value,weaponIst:g.mastery[cap.best.id]||1,kw:bare(g,refItem(cap.best.id)),side:role==='Fernkämpfer'?{id:'dagger',pot:g.caps.weapons.dagger||1,ist:g.mastery.dagger||1}:null};}
 const best=ROLES.map(r=>classes[r]).sort((a,b)=>b.pot-a.pot)[0];
 const data={sig,id:g.id,talent,tier,kw:bare(g),classes,best:best.role,raw:best.pot-best.ist};cache.set(g.id,data);return data;}
function prune(){if(cache.size<=S.roster.length*2+20)return;const alive=new Set(S.roster.map(g=>g.id));for(const id of cache.keys())if(!alive.has(id))cache.delete(id);}
// ---------- Ansichtszustand ----------
let lens='all',onlyClass=false,sort='kw',pageNo=0,viewId=null,viewTab='overview';
const SORTS=[['kw','BESTE JETZT','Kampfwert'],['talent','GRÖSSTE TALENTE','Talent'],['raw','ROHDIAMANTEN','Abstand IST → Potenzial'],['ist','KLASSEN-IST',''],['pot','KLASSEN-POTENZIAL',''],['weapon','WAFFENPOTENZIAL','']];
const lensRole=(g,d)=>lens==='all'?d.best:lens;
function key(g,d){const c=d.classes[lensRole(g,d)];return sort==='kw'?d.kw:sort==='talent'?d.talent:sort==='raw'?(lens==='all'?d.raw:c.pot-c.ist):sort==='ist'?c.ist:sort==='pot'?c.pot:c.weaponPot;}
function rows(){prune();return S.roster.filter(g=>!onlyClass||lens==='all'||g.role===lens).map(g=>({g,d:info(g)})).sort((a,b)=>key(b.g,b.d)-key(a.g,a.d)||b.d.talent-a.d.talent||a.g.name.localeCompare(b.g.name));}
// ---------- Scout-Texte ----------
function scoutLine(g,d){if(d.tier.level<10)return '';const c=d.classes[d.best],seed=[...g.id].reduce((n,ch)=>n+ch.charCodeAt(0),0);
 if(d.raw>=40)return 'Vergiss seine derzeitige Stärke. Schau dir sein Potenzial an.';
 if(c.weaponPot>=90)return 'Bei allen Göttern … gib ihm '+(/[aeiouäöü]$/i.test(weaponName(c.weapon))?'eine ':'einen ')+esc(weaponName(c.weapon))+' und sieh zu.';
 return ['Bei allen Göttern …','Den lässt du mir nicht wieder gehen.','So einen sehe ich vielleicht einmal im Leben.'][seed%3];}
const WORDS={strength:['enorme Kraft','viel Kraft','unterdurchschnittliche Kraft','sehr wenig Kraft'],stamina:['außergewöhnliche Ausdauer','gute Ausdauer','schwache Ausdauer','kaum Ausdauer'],condition:['außergewöhnliche Kondition','gute Kondition','schwache Kondition','sehr schlechte Kondition'],agility:['außergewöhnliche Beweglichkeit','starke Beinarbeit','träge Beine','sehr unbeweglich'],dexterity:['außergewöhnlich geschickte Hände','geschickte Hände','ungeschickte Hände','sehr ungeschickt'],reflex:['außergewöhnliche Reflexe','schnelle Reflexe','langsame Reflexe','sehr langsame Reflexe'],precision:['außergewöhnliche Präzision','gute Präzision','ungenau','sehr ungenau'],block:['außergewöhnliche Schildarbeit','gute Schildarbeit','schwaches Schildpotenzial','sehr schwaches Schildpotenzial'],balance:['außergewöhnlich standfest','guter Stand','wackeliger Stand','fällt leicht'],toughness:['außergewöhnlich robust','robuster Körper','geringe körperliche Robustheit','sehr geringe körperliche Robustheit'],pain:['spürt kaum Schmerz','hohe Schmerztoleranz','schmerzempfindlich','sehr schmerzempfindlich'],will:['eiserner Wille','starker Wille','schwacher Wille','bricht schnell ein'],aggression:['außergewöhnlich angriffslustig','angriffslustig','zögerlich','sehr zögerlich'],tactics:['außergewöhnliches taktisches Gespür','gutes taktisches Gespür','wenig taktisches Gespür','kein taktisches Gespür'],teamwork:['außergewöhnlicher Teamkämpfer','guter Teamkämpfer','schwacher Teamkämpfer','Einzelgänger ohne Abstimmung'],experience:['kann außergewöhnlich viel Erfahrung sammeln','lernt viel aus Kämpfen','lernt wenig aus Kämpfen','lernt kaum aus Kämpfen'],morale:['unerschütterliche Moral','stabile Moral','wankende Moral','sehr labile Moral']};
// Auffällig ist, was nach der Verteilung der SOLL-Werte (32 Bernoulli-Würfe je Wert) im obersten oder untersten Zehntel liegt:
// ab 78 bzw. bis 57. Das äußerste Hundertstel (ab 88 bzw. bis 47) zählt doppelt. Gilt für alle Grundwerte, Manöver und Körperteile.
// Waffen werden nicht einzeln gewertet: dort zählt je Klasse nur die stärkste.
const mark=v=>v>=88?2:v>=78?1:v<=47?-2:v<=57?-1:0;
function analysis(g,d){const out=[],add=(group,m,v,text)=>{if(m)out.push({group,m,v:Math.round(v),text});};
 for(const [k,words] of Object.entries(WORDS)){const v=g.caps.stats[k],m=mark(v);add('Grundwerte',m,v,m?words[m===2?0:m===1?1:m===-1?2:3]:'');}
 for(const [k,v] of Object.entries(g.caps.moves)){const m=mark(v),name=(M.moveNames[k]||k).replace('Zufällige 2er-/3er-/4er-Kombo','Kombo');add('Manöver',m,v,name);}
 for(const [id,name] of M.parts){const p=g.caps.body[id];if(!p||g.body[id]?.missing)continue;add('Körper',mark(p.strength),p.strength,name+' · Kraft');add('Körper',mark(p.agility),p.agility,name+' · Beweglichkeit');}
 const seen=new Set();for(const role of ROLES){const c=d.classes[role];if(seen.has(c.weapon))continue;seen.add(c.weapon);if(c.weaponPot>=94)add('Klasse & Waffe',2,c.weaponPot,'enormes '+weaponName(c.weapon)+'-Potenzial');else if(c.weaponPot>=88)add('Klasse & Waffe',1,c.weaponPot,'gutes '+weaponName(c.weapon)+'-Potenzial');}
 for(const role of ROLES){const p=d.classes[role].pot,label=role==='Fernkämpfer'?'Fernkampf':role==='Soldat'?'Soldaten':'Assassinen';if(p>=78)add('Klasse & Waffe',2,p,'außergewöhnliche '+label+'-Eignung');else if(p>=76)add('Klasse & Waffe',1,p,'starke '+label+'-Eignung');else if(p<=63)add('Klasse & Waffe',-2,p,'sehr schlechte '+label+'-Eignung');else if(p<=65)add('Klasse & Waffe',-1,p,'schlechte '+label+'-Eignung');}
 const order=['Klasse & Waffe','Grundwerte','Manöver','Körper'],by=(a,b)=>order.indexOf(a.group)-order.indexOf(b.group);
 return {plus:out.filter(x=>x.m>0).sort((a,b)=>by(a,b)||b.m-a.m||b.v-a.v),minus:out.filter(x=>x.m<0).sort((a,b)=>by(a,b)||a.m-b.m||a.v-b.v)};}
// ---------- Darstellung ----------
const btn=(label,action,cls='',pressed)=>`<button class="btn ${cls}" data-action="${action}"${pressed===undefined?'':` aria-pressed="${pressed}"`}>${label}</button>`;
function classRows(g,d,withWeaponIst=false){return `<div class="bk-classes">${ROLES.map(role=>{const c=d.classes[role],on=g.role===role;return `<button class="bk-class${on?' on':''}${d.best===role?' best':''}" data-action="barracks:class:${g.id}:${role}" aria-pressed="${on}" title="${on?'Zugewiesene Klasse':'Als '+role+' einteilen'}"><span class="bk-role">${ICON[role]} ${role.toUpperCase()}</span><span class="bk-val">${Math.round(c.ist)} → <b>${Math.round(c.pot)}</b></span><span class="bk-weapon">${esc(weaponName(c.weapon))} ★${Math.round(c.weaponPot)}${c.side?' · '+esc(weaponName(c.side.id))+' ★'+Math.round(c.side.pot):''}${withWeaponIst?' <small>(IST '+Math.round(c.weaponIst)+')</small>':''}</span><span class="bk-kwref">KW ${c.kw}</span></button>`;}).join('')}</div>`;}
function card({g,d}){const line=scoutLine(g,d);return `<article class="bk-card bk-t${d.tier.level}"><canvas data-scoutfigure="${g.id}" aria-label="${esc(g.name)}"></canvas><div class="bk-main"><header><h3>${esc(g.name)}</h3><b class="bk-kw" title="Kampfwert ohne Ausrüstung">KW ${d.kw}</b></header><p class="bk-talent"><span class="bk-stars" aria-hidden="true">${stars(d.tier.level)}</span> <strong>${d.tier.name.toUpperCase()}</strong> · Talent ${d.talent}</p>${line?`<p class="bk-quote">„${line}“</p>`:''}${classRows(g,d)}<footer><span>Klasse: <b>${g.role.toUpperCase()}</b>${g.locks?.class?' 🔒':''}${M.health(g)<70?' · <span class="bk-hurt">verletzt</span>':''}${g.smithDuty?' · <span class="bk-hurt">'+(g.smithDuty==='queue'?'wartet auf die Schmiedelehre':'in der Schmiedelehre')+'</span>':''}</span><span class="bk-actions">${btn('GENAUER BETRACHTEN','barracks:view:'+g.id+':overview','small')}${btn('PROFIL','detail:'+g.id,'small')}${btn('AUSRÜSTEN','loadout:'+g.id,'small')}</span></footer></div></article>`;}
function legend(list){const count=Array(11).fill(0);for(const {d} of list)count[d.tier.level]++;return `<details class="bk-legend"><summary>Talentstufen · 10 Stufen nach allgemeinem Talent</summary><ol>${[...TIERS].reverse().map(([min,name],i)=>{const max=i<9?[...TIERS].reverse()[i+1][0]-1:100;return `<li class="bk-t${i+1}"><b>${i+1}. ${name}</b><span>Talent ${min||1}–${max}</span><span>${count[i+1]} im Kader</span></li>`;}).join('')}</ol><p class="tiny">Die Stufe beschreibt nur das vorhandene allgemeine Talent. Sie verändert keine Werte. Hohe Stufen sind bei Rekruten selten, eine Prodigy etwa 1 von 2.600.</p></details>`;}
function page(){const list=rows(),pages=Math.max(1,Math.ceil(list.length/PER_PAGE));pageNo=Math.max(0,Math.min(pageNo,pages-1));const lensName=lens==='all'?'beste Klasse':lens;
 return `<div class="page-head"><h1>Kaserne</h1><p class="sub">${S.roster.length} Gladiatoren${M.capacity()<100000?' · '+M.capacity()+' Plätze':''} · KW ohne Ausrüstung · Klassenzeile antippen = zuweisen</p></div>
<section class="bk-bar"><div class="bk-chips" role="group" aria-label="Bewerten als"><span>Bewerten als</span>${btn('ALLE','barracks:lens:all',lens==='all'?'active':'',lens==='all')}${ROLES.map(r=>btn(ICON[r]+' '+r.toUpperCase(),'barracks:lens:'+r,lens===r?'active':'',lens===r)).join('')}${lens==='all'?'':btn('NUR '+lens.toUpperCase(),'barracks:only',onlyClass?'active':'',onlyClass)}</div>
<div class="bk-chips" role="group" aria-label="Sortieren nach"><span>Sortieren</span>${SORTS.map(([id,name])=>btn(name,'barracks:sort:'+id,sort===id?'active':'',sort===id)).join('')}</div>
<p class="tiny">Sortiert nach ${esc(SORTS.find(s=>s[0]===sort)[2]||SORTS.find(s=>s[0]===sort)[1])}${['ist','pot','weapon','raw'].includes(sort)?' · bewertet als '+esc(lensName):''} ↓ · ${list.length} Gladiatoren</p>${legend(list)}</section>
${list.length?`<div class="bk-grid">${list.slice(pageNo*PER_PAGE,pageNo*PER_PAGE+PER_PAGE).map(card).join('')}</div>`:`<div class="empty">${S.roster.length?'Kein Gladiator mit dieser Klasse.':'Deine Schule wartet auf ihre ersten Gladiatoren.'} ${btn('ZUM SKLAVENHÄNDLER','nav:market','primary')}</div>`}
${pages>1?`<div class="buttons bk-pager">${btn('‹','barracks:page:-1','small')}<span>Seite ${pageNo+1} / ${pages}</span>${btn('›','barracks:page:1','small')}</div>`:''}`;}
// ---------- Genauer betrachten ----------
const TABS=[['overview','ÜBERSICHT'],['traits','STÄRKEN & SCHWÄCHEN'],['stats','STATS'],['weapons','WAFFEN']];
function view(){const g=S.roster.find(g=>g.id===viewId);if(!g){viewId=null;return;}const d=info(g),line=scoutLine(g,d);let body='';
 if(viewTab==='overview'){const v=M.combatValues(g);body=`<p class="bk-talent bk-t${d.tier.level}"><span class="bk-stars" aria-hidden="true">${stars(d.tier.level)}</span> <strong>${d.tier.name.toUpperCase()}</strong> · Talent ${d.talent} · Stufe ${d.tier.level} von 10</p>${line?`<p class="bk-quote">„${line}“</p>`:''}<dl class="bk-facts">${[['Kampfwert ohne Ausrüstung',d.kw],['Kampfwert mit Ausrüstung',v.current+' · SOLL '+v.maximum],['Allgemeines Talent',d.talent+' / 100'],['Empfohlene Klasse',ICON[d.best]+' '+d.best],['Alter',g.age+' Jahre'],['Gesundheit',Math.round(M.health(g))+' %'],['Kämpfe',g.fights+' · '+g.wins+' Siege'],['Herkunft',esc(g.origin)]].map(([k,x])=>`<dt>${k}</dt><dd>${x}</dd>`).join('')}</dl><h3>Klasse zuweisen</h3><p class="tiny">IST → Potenzial · beste Talentwaffe · Kampfwert mit Vergleichswaffe, ohne Rüstung.</p>${classRows(g,d)}`;}
 else if(viewTab==='traits'){const a=analysis(g,d),row=x=>`<li class="${x.m>0?'bk-plus':'bk-minus'}"><b>${x.m===2?'++':x.m===1?'+':x.m===-1?'−':'−−'}</b> ${esc(x.text)} <small>${x.v}</small></li>`,list=items=>{let group='';return items.map(x=>(x.group!==group?`<li class="bk-group">${group=x.group}</li>`:'')+row(x)).join('');};body=`<div class="bk-traits"><div><h3>Stärken · ${a.plus.length}</h3><ul>${list(a.plus)||'<li class="tiny">Nichts sticht heraus.</li>'}</ul></div><div><h3>Schwächen · ${a.minus.length}</h3><ul>${list(a.minus)||'<li class="tiny">Keine auffällige Schwäche.</li>'}</ul></div></div><p class="tiny">Der Scout beurteilt die Anlage, also die SOLL-Werte aller Grundwerte, Manöver und Körperteile. Genannt wird, was im obersten oder untersten Zehntel liegt (ab 78 bzw. bis 57), das äußerste Hundertstel doppelt. Waffen einzeln nicht: dort zählt nur die stärkste je Klasse. Die Zahl ist der SOLL-Wert.</p>`;}
 else if(viewTab==='stats'){body=`<div class="stats-grid">${Object.entries(M.stats).map(([k,n])=>`<div class="stat"><span>${n}</span><strong>${g.stats[k].toFixed(1)} / ${g.caps.stats[k]}</strong></div>`).join('')}${[['Größe',g.height+' cm'],['Gewicht',g.weight+' kg'],['Armlänge',g.arm+' cm'],['Beinlänge',g.leg+' cm'],['Körperfett',g.fat+' %'],['Muskelmasse',g.muscle+' kg']].map(([n,x])=>`<div class="stat"><span>${n}</span><strong>${x}</strong></div>`).join('')}</div><p class="tiny">IST / SOLL. Werte steigen nur durch tatsächliche Kampfaktionen.</p>`;}
 else{body=ROLES.map(role=>{const c=d.classes[role],list=M.classSpecs[role].weapons.map(id=>({id,ist:g.mastery[id]||1,pot:g.caps.weapons[id]||1})).sort((a,b)=>b.pot-a.pot);return `<section class="bk-wclass${g.role===role?' on':''}"><h3>${ICON[role]} ${role.toUpperCase()} · IST ${Math.round(c.ist)} → POT ${Math.round(c.pot)}</h3><p>Beste Talentwaffe: <b>${esc(weaponName(c.weapon))} ★${Math.round(c.weaponPot)}</b><br>KW mit Referenz-${esc(weaponName(c.weapon))}: <b>${c.kw}</b></p><div class="bk-wlist">${list.map(w=>`<span>${esc(weaponName(w.id))}</span><span>${w.ist.toFixed(0)} → <b>${w.pot.toFixed(0)}</b></span>`).join('')}${c.side?`<span>Nahkampf: ${esc(weaponName(c.side.id))}</span><span>${c.side.ist.toFixed(0)} → <b>${c.side.pot.toFixed(0)}</b></span>`:''}</div><p class="tiny">${role==='Fernkämpfer'?'Im Nahkampf nur der Dolch, kein Schild.':role==='Assassine'?'Nahkampf: Kurzschwert, Gladius oder Axt.':'Alle Nahkampfwaffen, Schild erlaubt.'}</p></section>`;}).join('')+`<p class="tiny">Vergleichswaffe: immer Güte „${esc(M.gearQuality[REF_Q])}“, ohne Rüstung. Vorhandene Lagerstücke fließen nicht ein.</p>`;}
 M.ui.modal(esc(M.displayName?.(g)||g.name),`<nav class="bk-tabs" aria-label="Ansicht">${TABS.map(([id,name])=>btn(name,'barracks:view:'+g.id+':'+id,'small'+(viewTab===id?' active':''),viewTab===id)).join('')}</nav>${body}`,btn('PROFIL ÖFFNEN','detail:'+g.id)+btn('AUSRÜSTEN','loadout:'+g.id)+btn('VERWALTEN & SPERREN','army:person:'+g.id)+(M.workshop?.state.master&&!g.smithDuty?btn('IN DIE SCHMIEDELEHRE','barracks:smith:'+g.id):''));}
// ---------- Einbindung ----------
const oldPage=M.schoolPage;M.schoolPage=p=>p==='gladiators'||p==='scout'?page():oldPage(p);
const oldClick=M.schoolClick;M.schoolClick=action=>{if(action==='nav:scout')action='nav:gladiators';if(!action.startsWith('barracks:'))return oldClick(action);
 const [,a,b,c]=action.split(':');
 if(a==='lens'){lens=b;onlyClass=onlyClass&&b!=='all';pageNo=0;}
 else if(a==='only'){onlyClass=!onlyClass;pageNo=0;}
 else if(a==='sort'){sort=b;pageNo=0;}
 else if(a==='page')pageNo+=+b;
 else if(a==='class'){const g=S.roster.find(g=>g.id===b);if(g&&g.role!==c)M.ui.notify(M.setClass(b,c));M.ui.render();if(viewId===b&&document.getElementById('modal')&&!document.getElementById('modal').hidden)view();return true;}
 else if(a==='smith'){M.ui.close();M.ui.notify(M.workshop.sendGladiator(b));M.ui.render();return true;}
 else if(a==='view'){viewId=b;viewTab=TABS.some(t=>t[0]===c)?c:'overview';view();return true;}
 M.ui.render();return true;};
M.barracks={info,tierOf,tiers:TIERS,analysis,rows,page,bare,get state(){return {lens,onlyClass,sort,pageNo};},set(next){({lens=lens,onlyClass=onlyClass,sort=sort,pageNo=pageNo}=next);}};
})();
