'use strict';
// Versionskennung: wird beim Veröffentlichen durch die Commit-Kennung ersetzt, damit Browser nach einem Update keine alten Dateien aus dem Zwischenspeicher nehmen.
var BUILD='98fb40c1';
(async()=>{
 const cache=new Map(),pending=new Set();let db=null,error='';const marker='mini-gladiator-large-save-v1';
 try{if(!window.indexedDB)throw Error('IndexedDB unavailable');db=await new Promise((resolve,reject)=>{const req=indexedDB.open('mini-gladiator-saves',1);req.onupgradeneeded=()=>req.result.createObjectStore('profiles');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Bitte andere Spiel-Tabs schließen und neu laden.'));});await new Promise((resolve,reject)=>{const tx=db.transaction('profiles','readonly'),req=tx.objectStore('profiles').openCursor();req.onsuccess=()=>{const cursor=req.result;if(cursor){cache.set(cursor.key,cursor.value);cursor.continue();}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
 catch(ex){if(localStorage.getItem(marker))throw Error('Der gespeicherte große Spielstand konnte nicht geöffnet werden. Bitte erneut laden; es wird kein neuer Spielstand angelegt.');db=null;}
 window.MGSave={get(key){return cache.has(key)?cache.get(key):localStorage.getItem(key);},set(key,raw){this.setMany([[key,raw]]);},setMany(entries){for(const [key,raw] of entries)cache.set(key,raw);if(!db){for(const [key,raw] of entries)localStorage.setItem(key,raw);return;}const tx=db.transaction('profiles','readwrite');for(const [key,raw] of entries)tx.objectStore('profiles').put(raw,key);const job=new Promise(resolve=>{tx.oncomplete=()=>{error='';try{localStorage.setItem(marker,'1');}catch{}resolve();};tx.onerror=tx.onabort=()=>{error='Speichern fehlgeschlagen. Bitte den Spielstand geöffnet lassen und freien Browserspeicher prüfen.';const n=document.getElementById('notice');if(n){n.textContent=error;n.style.opacity=1;}resolve();};});pending.add(job);job.then(()=>pending.delete(job));},removeProfile(key){const hit=k=>k===key||String(k).startsWith(key+':'),keys=[...cache.keys()].filter(hit);for(const k of keys)cache.delete(k);try{for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&hit(k))localStorage.removeItem(k);}}catch{}if(!db||!keys.length)return;const tx=db.transaction('profiles','readwrite');for(const k of keys)tx.objectStore('profiles').delete(k);const job=new Promise(resolve=>{tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>{error='Löschen fehlgeschlagen. Bitte die Seite neu laden und erneut versuchen.';const n=document.getElementById('notice');if(n){n.textContent=error;n.style.opacity=1;}resolve();};});pending.add(job);job.then(()=>pending.delete(job));},async flush(){while(pending.size)await Promise.all([...pending]);if(error)throw Error(error);},get error(){return error;}};
 for(const name of ['profiles','data','household','management','scout','sim','benchmark','school','world','forge','spy','audio','arena','techniques','manager','school-ui','world-ui','mobile','ludus','intro','forge-ui','forge-intro','scene-nav','barracks','trader','wanderer-talk','wanderers','village-life','smith-wrath','archer-plot','hall'])await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=name+'.js?v='+BUILD;script.onload=resolve;script.onerror=()=>reject(Error(name+' konnte nicht geladen werden.'));document.body.appendChild(script);});
})().catch(ex=>{const app=document.getElementById('app');app.textContent='Spiel konnte nicht gestartet werden: '+ex.message;const button=document.createElement('button');button.className='btn';button.textContent='Erneut versuchen';button.onclick=()=>location.reload();app.appendChild(button);});

