'use strict';
window.MG=(()=>{
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),uid=()=>crypto.randomUUID(),copy=x=>JSON.parse(JSON.stringify(x));
const stats={strength:'Stärke',stamina:'Ausdauer',condition:'Kondition',agility:'Beweglichkeit',dexterity:'Geschicklichkeit',reflex:'Reflexe',precision:'Präzision',block:'Blocken',balance:'Balance',toughness:'Zähigkeit',pain:'Schmerztoleranz',will:'Willenskraft',aggression:'Aggression',tactics:'Taktik',teamwork:'Teamwork',experience:'Erfahrung',morale:'Moral'};
const parts=[['head','Kopf',0,-62,18,18],['neck','Hals',0,-46,9,9],['chest','Brust',0,-32,28,20],['belly','Bauch',0,-12,25,18],['ls','Linke Schulter',-23,-38,14,14],['rs','Rechte Schulter',23,-38,14,14],['lua','Linker Oberarm',-28,-23,12,18],['rua','Rechter Oberarm',28,-23,12,18],['lfa','Linker Unterarm',-31,-3,10,20],['rfa','Rechter Unterarm',31,-3,10,20],['lh','Linke Hand',-31,13,11,11],['rh','Rechte Hand',31,13,11,11],['lt','Linker Oberschenkel',-10,15,15,26],['rt','Rechter Oberschenkel',10,15,15,26],['lsh','Linker Unterschenkel',-11,42,12,24],['rsh','Rechter Unterschenkel',11,42,12,24],['lf','Linker Fuß',-14,60,17,10],['rf','Rechter Fuß',14,60,17,10]];
const partName=id=>parts.find(p=>p[0]===id)?.[1]||id;
const branches={head:['head'],neck:['neck','head'],ls:['ls','lua','lfa','lh'],rs:['rs','rua','rfa','rh'],lua:['lua','lfa','lh'],rua:['rua','rfa','rh'],lfa:['lfa','lh'],rfa:['rfa','rh'],lh:['lh'],rh:['rh'],lt:['lt','lsh','lf'],rt:['rt','rsh','rf'],lsh:['lsh','lf'],rsh:['rsh','rf'],lf:['lf'],rf:['rf']};
const traits=['Mutig','Feige','Aggressiv','Diszipliniert','Loyal','Egoistisch','Berserker','Taktiker','Teamspieler','Blutrünstig','Gelassen','Zäh','Talentiert','Verletzungsanfällig','Schneller Lerner','Spätentwickler'];
const origins=['Rom','Gallien','Germanien','Thrakien','Hispanien','Numidien','Griechenland','Britannien','Ägypten','Syrien','Judäa','Kappadokien','Dakien','Illyrien','Lusitanien','Mauretanien','Nubien','Armenien','Parthien','Sizilien'];
const names=['Cassius','Varro','Drusus','Titus','Aelius','Brutus','Crixus','Marcellus','Aquila','Felix','Lucius','Gaius','Severus','Decimus','Flavius','Marius','Damon','Atticus','Cato','Rufus','Valerius','Silvanus','Tiberius','Nero','Dorian','Leontius','Aster','Corvinus','Maximus','Trajan'];
const surnames=['Varrus','Corvus','Ferox','Gallus','Nerva','Lupus','Fortis','Aurelius','Macer','Vindex','Scaeva','Rutilus'];
const qualities=['Gewöhnlich','Erfahren','Talentiert','Elite','Champion','Ausnahmetalent'],recruitPrices=[100,300,1000,4000,20000,100000],gearQuality=['Improvisiert','Einfach','Solide','Gut','Hochwertig','Meisterhaft','Legendär'],gearPrices=[35,100,300,900,3000,12000,60000];
// id, name, damage, range, seconds, weight, penetration, block, ammunition, old pixel sprite
const weaponDefs=[['dagger','Dolch',13,36,.64,1,.10,.08,0,3],['short','Kurzschwert',16,46,.84,2,.13,.13,0,0],['gladius','Gladius',18,51,1.02,2.5,.18,.20,0,0],['long','Langschwert',20,64,1.23,3.5,.21,.25,0,0],['axe','Axt',24,49,1.47,4,.27,.09,0,2],['doubleaxe','Doppelaxt',33,58,1.85,6,.32,.08,0,2],['club','Keule',23,48,1.1,3,.24,.12,0,4],['mace','Streitkolben',28,50,1.38,4,.39,.15,0,4],['hammer','Hammer',39,54,1.9,7,.52,.12,0,4],['spear','Speer',18,91,1.42,3,.31,.19,0,1],['trident','Dreizack',20,84,1.56,3.5,.26,.25,0,5],['halberd','Hellebarde',30,98,1.95,6,.39,.28,0,1],['greatsword','Zweihandschwert',32,78,1.88,6,.32,.30,0,0],['javelin','Wurfspeer',25,155,2.40,3,.35,.02,3,1],['throwaxe','Wurfaxt',23,120,2.20,3,.22,.02,8,2],['net','Wurfnetz',0,155,2.8,2,.02,.02,1,8],['bow','Bogen',19,255,2.10,2,.28,.01,18,9],['crossbow','Armbrust',40,310,3.5,4,.40,.01,12,10]].map(d=>({id:d[0],name:d[1],damage:d[2],range:d[3],delay:d[4],weight:d[5],pen:d[6],block:d[7],ammo:d[8],sprite:d[9],bladed:!['club','mace','hammer','net','bow','crossbow'].includes(d[0]),twoHand:['doubleaxe','hammer','halberd','greatsword','bow','crossbow'].includes(d[0])}));
const armorDefs=[['helm','Helm',['head','neck'],2.5,10],['chestplate','Brustpanzer',['chest','belly'],7,15],['leftarm','Linke Armschiene',['lua','lfa','lh'],2,9],['rightarm','Rechte Armschiene',['rua','rfa','rh'],2,9],['leftleg','Linke Beinschiene',['lt','lsh','lf'],3,11],['rightleg','Rechte Beinschiene',['rt','rsh','rf'],3,11],['leftshoulder','Linker Schulterpanzer',['ls'],1.5,10],['rightshoulder','Rechter Schulterpanzer',['rs'],1.5,10]].map(d=>({id:d[0],name:d[1],parts:d[2],weight:d[3],protection:d[4]}));
const shieldDefs=[['buckler','Buckler',.16,8,1.5],['smallshield','Kleiner Rundschild',.24,12,2.5],['roundshield','Mittlerer Rundschild',.34,18,4],['scutum','Scutum',.46,26,7],['tower','Schwerer Turmschild',.58,33,11]].map(d=>({id:d[0],name:d[1],area:d[2],protection:d[3],weight:d[4]}));
const definitionMap={weapon:Object.fromEntries(weaponDefs.map(d=>[d.id,d])),armor:Object.fromEntries(armorDefs.map(d=>[d.id,d])),shield:Object.fromEntries(shieldDefs.map(d=>[d.id,d]))};
const roles=['Soldat','Assassine','Fernkämpfer'];
const leagues=[['Straßenarena',0,0,0,110,0,0],['Dorfarena',8,180,110,260,30,1],['Provinzarena',22,440,420,650,85,1],['Stadtarena',42,830,1150,1700,230,3],['Imperiale Arena',70,1400,2800,4500,650,4],['Champion-Liga',108,2300,6500,11000,1600,4],['Arena der Legenden',158,3500,15000,28000,4200,4]].map((d,i)=>({name:d[0],wins:d[1],fame:d[2],promotion:d[3],reward:Math.round(d[4]*1.2),fee:d[5],arena:d[6],risk:.008+i*.008}));
const buildings={housing:['Unterkunft','+3 Plätze',140],training:['Trainingsplatz','+3 % Manöver- und Grundwerte-Lerntempo',180],strength:['Kraftbereich','+3 % Kraft-Lerntempo im Kampf',200],endurance:['Ausdauerbereich','+3 % Ausdauer-Lerntempo im Kampf',200],weapons:['Waffentraining','+3 % Nahkampfwaffen-Lerntempo',240],archery:['Wurfplatz','+3 % Wurfwaffen-Lerntempo',240],medic:['Medicus','−5 % Behandlungskosten',250],hospital:['Krankenstation','+1 natürliche Heilung pro Tag',220],storage:['Lager','+15 Gegenstandsplätze',140],forge:['Schmiede','Schmiedeverbesserungen freischalten',350],tactics:['Taktikraum','+3 % Taktik- & Team-Lerntempo',240]};
const trainingDefs=[['Krafttraining',['strength'],['lua','rua','lt','rt'],'strength'],['Ausdauertraining',['stamina','condition'],['chest'],'endurance'],['Sprint',['agility','condition'],['lt','rt','lsh','rsh'],'endurance'],['Beinarbeit',['balance','agility'],['lt','rt','lf','rf'],'training'],['Schwerttraining',['dexterity','strength'],['rua','rfa','rh'],'weapons','sword'],['Speertraining',['dexterity','precision'],['lua','rua','rh'],'weapons','spear'],['Schildtraining',['block','balance'],['lua','lfa','lh'],'weapons','shield'],['Netztraining',['precision','dexterity'],['lua','rua','rh'],'archery','throw'],['Wurfwaffentraining',['precision','strength'],['rua','rh'],'archery','throw'],['Ausweichtraining',['agility','balance'],['lt','rt','lf','rf'],'training'],['Reflextraining',['reflex','dexterity'],['head'],'training'],['Taktiktraining',['tactics','will'],['head'],'tactics'],['Teamtraining',['teamwork','morale'],['chest'],'tactics'],['Ansturm',['strength','balance'],['lt','rt','chest'],'training',null,'charge'],['Rücksprung',['agility','reflex'],['lt','rt','lf','rf'],'training',null,'backstep']];
const tournaments=[{id:'open',name:'Drei gegen Drei',rule:'Alle Ausrüstungen erlaubt.',mult:2},{id:'melee',name:'Klingenbund',rule:'Nur Nahkampfwaffen.',mult:2.4},{id:'light',name:'Tanz der Klingen',rule:'Höchstens 12 kg Ausrüstung je Gladiator.',mult:2.5},{id:'ranged',name:'Adlerturnier',rule:'Jeder Gladiator braucht eine Fernkampfwaffe.',mult:2.5},{id:'veteran',name:'Eid der Veteranen',rule:'Mindestens 10 Kämpfe je Gladiator.',mult:3},{id:'champion',name:'Krone des Imperiums',rule:'Ab Champion-Liga.',mult:4}];
let s;try{s=JSON.parse(window.MGSave?window.MGSave.get(window.GladiatorProfiles?.key||'mini-gladiator-manager-v2'):localStorage.getItem(window.GladiatorProfiles?.key||'mini-gladiator-manager-v2'))}catch{}if(!s||s.version!==2)s={version:2,rng:Date.now()>>>0,gold:2000,day:1,fame:0,wins:0,losses:0,league:0,fightLeague:0,rank:Array(7).fill(1000),roster:[],inventory:[],market:[],fallen:[],trainers:[],buildings:Object.fromEntries(Object.keys(buildings).map(k=>[k,0])),teams:[[],[],[]],teamIndex:0,tactics:{aggression:'Ausgeglichen',formation:'Normal',priority:'Nächster Gegner',ranged:'Abstand halten',help:'Normal'},records:[],history:[],event:null,sponsor:null,tournament:null,battle:null,lastReport:null,options:{music:true,sound:true,shake:true,speed:1},lastMarket:1,started:false,stats:{earned:0,spent:0,kills:0,battles:0},recoveryDay:-100};
s.schoolName??=window.GladiatorProfiles?.name||'Ludus Holz';let storageError=false;function persist(){if(window.MG?.benchmarkActive||window.MG?.batchSaving)return true;for(const g of [...s.roster,...s.trainers])normalizeClassGear(g);try{window.MG?.world?.syncOwners();window.MG?.snapshotBattle?.();const arrears=Math.min(s.gold,s.soldArrears||0);if(arrears>0){s.gold-=arrears;s.stats.spent+=arrears;s.soldArrears-=arrears;}s.savedAt=Date.now();const key=window.GladiatorProfiles?.key||'mini-gladiator-manager-v2';if(window.MGSave?.setMany&&window.MG?.worldSerialize){const pack=window.MG.worldSerialize(key);window.MGSave.setMany([...pack.entries,[key,JSON.stringify(pack.root)]]);}else if(window.MGSave)window.MGSave.set(key,JSON.stringify(s));else localStorage.setItem(key,JSON.stringify(s));storageError=false;return true}catch{storageError=true;return false}}
function rng(){let t=s.rng+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}const rnd=(a,b)=>a+rng()*(b-a),pick=a=>a[Math.floor(rng()*a.length)];
function gaussian(mean=50,sd=12){let z=0;for(let i=0;i<6;i++)z+=rng();return mean+(z-3)*Math.SQRT2*sd}
function log(text){s.history.unshift({day:s.day,text});s.history=s.history.slice(0,100)}

const skinPalette=[['#edc9a4','#b88b69'],['#d9ac82','#9c7353'],['#c19169','#875e43'],['#a97851','#735036'],['#8d5b3f','#593d2e'],['#71462f','#4a3025'],['#593b2d','#35251e'],['#d3a08a','#a17561']];
const hairPalette=['#201c1b','#443025','#6d4930','#a86e39','#d3b76e','#943f27','#b1a592','#d5d0ba'];
function ensureIdentity(g){let seed=2166136261;for(const c of g.id)seed=Math.imul(seed^c.charCodeAt(0),16777619);const r=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296};if(!g.appearance){const north=['Germanien','Gallien','Britannien','Dakien'],south=['Numidien','Mauretanien','Nubien'],pool=g.origin==='Nubien'?[3,4,5,6]:north.includes(g.origin)?[0,1,2,7]:south.includes(g.origin)?[2,3,4,5]:[0,1,2,3,4,7];const skin=skinPalette[pool[Math.floor(r()*pool.length)]];g.appearance={skin:skin[0],shade:skin[1],hair:hairPalette[Math.floor(r()*hairPalette.length)],style:Math.floor(r()*6),beard:Math.floor(r()*4),voice:.82+r()*.4}}g.moves??={charge:Math.round(5+g.stats.strength*.14),backstep:Math.round(5+g.stats.agility*.14)};g.moves.thrust??=8;g.moves.spin??=6;g.moves.sand??=4;for(const [id,p]of Object.entries(g.body)){if(!p.wounds)p.wounds=p.injury?[{day:g.created||1,type:p.injury,attacker:'Frühere Verletzung · Verursacher unbekannt',weapon:'',hits:1,damage:0}]:[]}return g}
function recordWound(g,id,type,attacker,weapon='',damage=0){ensureIdentity(g);const p=g.body[id],fight=s.battle?.id||'day-'+s.day;let last=p.wounds[0];if(last&&last.fight===fight&&last.attacker===attacker&&last.type===type){last.hits++;last.damage+=damage;last.day=s.day;}else{p.wounds.unshift({day:s.day,fight,type,attacker:attacker||'Unbekannt',weapon,hits:1,damage});p.wounds=p.wounds.slice(0,24)}}
function wishes(g){ensureIdentity(g);const st=g.stats;const scores=[['javelin',st.precision*.65+st.dexterity*.2+st.agility*.15,'Meine Präzision liegt mir. Mit einem Wurfspeer könnte ich den Kampf eröffnen.'],['spear',st.dexterity*.45+st.tactics*.25+g.arm*.15,'Mit meiner Reichweite und Waffenführung würde ich gern einen Speer führen.'],['hammer',st.strength*.65+st.balance*.2+g.muscle*.15,'Ich kann schwere Schläge tragen. Ein Hammer würde mir liegen.'],['dagger',st.agility*.6+st.reflex*.25+st.dexterity*.15,'Ich bin beweglich. Mit einem Dolch könnte ich schnell in die Lücken stoßen.'],['gladius',st.dexterity*.5+st.block*.25+st.balance*.25,'Ein Gladius würde gut zu meiner Waffenführung und meinem Gleichgewicht passen.'],['net',st.tactics*.5+st.teamwork*.3+st.precision*.2,'Ich würde gern ein Netz werfen und meinen Kameraden eine Lücke schaffen.']].sort((a,b)=>b[1]-a[1]);let out=[{title:'Lieblingswaffe · '+weaponDefs.find(w=>w.id===scores[0][0]).name,text:gear(g,'weapon')?.def===scores[0][0]?'Mit meiner jetzigen Waffe fühle ich mich gut aufgehoben.':scores[0][2]}];for(const [slot,text]of [['helm','Ein Helm würde mir ein besseres Gefühl geben, wenn die Schläge auf meinen Kopf zielen.'],['leftshoulder','Über einen Schutz für meine linke Schulter würde ich mich freuen.'],['rightshoulder','Meine rechte Schulter ist noch ungeschützt. Ein Schulterpanzer wäre mir lieb.']])if(!g.equipment.armor[slot]){out.push({title:'Ein persönlicher Wunsch',text});break}if(out.length===1)out.push({title:'Ausrüstung',text:'Meine wichtigen Schutzplätze sind belegt. Danke, dass du auf mich achtest.'});return out}

function makeGladiator(q=0,enemy=false){const age=Math.floor(rnd(18,37)),height=Math.round(clamp(gaussian(179,9),157,202)),muscle=Math.round(clamp(gaussian(40+q*1.4,5),25,65)),fat=Math.round(clamp(gaussian(16,4),8,28)),weight=Math.round((height-100)*.62+muscle*.58+fat*.6),base=enemy?23+q*9:20;const st=Object.fromEntries(Object.keys(stats).map(k=>[k,clamp(bernoulliValue(base),5,95)]));st.morale=bernoulliValue(enemy?71:20);st.experience=bernoulliValue(enemy?5+q*10:20);let tr=[pick(traits)];if(q>1)tr.push(pick(traits.filter(t=>!tr.includes(t))));if(enemy){if(tr.includes('Mutig'))st.will+=10;if(tr.includes('Feige'))st.will-=8;if(tr.includes('Berserker'))st.aggression+=12;if(tr.includes('Taktiker'))st.tactics+=10;if(tr.includes('Teamspieler'))st.teamwork+=12;if(tr.includes('Gelassen'))st.reflex+=6;if(tr.includes('Diszipliniert')){st.condition+=6;st.tactics+=5}if(tr.includes('Zäh')){st.toughness+=10;st.pain+=8}if(tr.includes('Loyal'))st.teamwork+=7;if(tr.includes('Aggressiv'))st.aggression+=10;if(tr.includes('Blutrünstig'))st.aggression+=8;}for(const k in st)st[k]=clamp(st[k],1,100);const g={id:uid(),name:pick(names)+' '+pick(surnames),age,birthday:s.day,height,weight,arm:Math.round(height*.43+rnd(-5,5)),leg:Math.round(height*.49+rnd(-5,5)),fat,muscle,origin:pick(origins),build:weight>95?'Kräftig':height<171?'Kompakt':fat<13?'Sehnig':'Athletisch',quality:q,traits:tr,stats:st,potential:bernoulliValue(62+q*2+(tr.includes('Talentiert')?5:0),32),body:{},scars:[],history:[],wins:0,losses:0,kills:0,fights:0,fame:0,highest:0,fatigue:0,blood:100,role:enemy?pick(roles):'Soldat',recruitStandard:!enemy,equipment:{weapon:null,secondary:null,shield:null,armor:{}},skills:Object.fromEntries(['sword','spear','shield','bow','throw'].map(k=>[k,bernoulliValue(enemy?10:20)])),dead:false,retired:false,healing:null,created:s.day};for(const [id] of parts)g.body[id]={hp:100,max:100,strength:clamp(bernoulliValue(enemy?st.strength:20),1,100),agility:clamp(bernoulliValue(enemy?st.agility:20),1,100),protection:0,pain:0,bleed:0,grade:0,chronic:0,missing:false,injury:''};g.mastery=Object.fromEntries(weaponDefs.map(w=>[w.id,bernoulliValue(enemy?10+q*4:20)]));g.moves=Object.fromEntries(['dodge','charge','backstep','thrust','spin','sand','slash','overhead','kick','rise','recover','rearFinish','shieldBash','groundFinish'].map(k=>[k,bernoulliValue(enemy?8+q*2:20)]));ensureCareer(g);window.MG?.ensureFamily?.(g);window.MG?.ensureGladiatorSmith?.(g);return g}
function makeItem(kind,id,q=0,material='metal'){let d=(kind==='weapon'?weaponDefs:kind==='armor'?armorDefs:shieldDefs).find(x=>x.id===id);return {id:uid(),kind,def:id,q,...(kind==='armor'?{material:['leather','medium','metal'].includes(material)?material:'metal'}:{}),durability:100+q*10,maxDurability:100+q*10,up:{sharp:0,durable:0,balance:0,penetration:0},...(!d?{invalid:true}:{})}}
function definition(i){return definitionMap[i.kind]?.[i.def]}
const weaponTitles={
 bow:['Astbogen','Jagdbogen','Soldatenbogen','Veteranenbogen','Adlerbogen','Meisterbogen','Diana – Mondbogen'],
 crossbow:['Holzarmbrust','Leichte Armbrust','Wacharmbrust','Veteranenarmbrust','Adlerschütze','Meisterarmbrust','Scorpio – Präzision Roms'],
 dagger:['Scherbenmesser','Eisendolch','Wachendolch','Vipernzahn','Schattenklinge','Nachtstich','Nox – Zahn der Nacht'],
 short:['Schrottklinge','Kurzschwert','Soldatenklinge','Veteranenklinge','Kaiserklinge','Meistergladius','Sol – Sonnenklinge'],
 gladius:['Kerbengladius','Eisengladius','Legionsgladius','Centurionklinge','Adlergladius','Triumphklinge','Invictus – Roms Wille'],
 long:['Rostschwert','Langschwert','Wachenschwert','Reiterschwert','Tribunenklinge','Silberfalke','Aurora – Morgensternklinge'],
 axe:['Splitterbeil','Eisenaxt','Kriegsaxt','Wolfsbeil','Blutbeil','Meisterbeil','Mors – Schicksalsbeil'],
 doubleaxe:['Schrottaxt','Doppelaxt','Doppelbart','Sturmbeil','Königsbeil','Zwillingsschneide','Gemini – Zorn der Zwillinge'],
 club:['Knüppel','Hartholzkeule','Eisenkeule','Dornenkeule','Wächterkeule','Löwenkeule','Herkules – Titanenkeule'],
 mace:['Schrottkolben','Streitkolben','Flanschkolben','Panzerknacker','Richterkolben','Imperialkolben','Justitia – Urteil aus Stahl'],
 hammer:['Steinhammer','Eisenhammer','Kriegshammer','Knochenbrecher','Erdbrecher','Titanenhammer','Vulcanus – Weltenbrecher'],
 spear:['Spitzstock','Jagdspeer','Kriegsspeer','Adlerspeer','Blitzspeer','Titanenspeer','Fulmen – Jupiters Speer'],
 trident:['Fischergabel','Dreizack','Arenadreizack','Flutspalter','Meereskrone','Herr der Gezeiten','Neptun – Zorn der Tiefe'],
 halberd:['Schrotthellebarde','Hellebarde','Wachengleve','Sturmgleve','Palasthellebarde','Drachenhaken','Terminus – Letzte Grenze'],
 greatsword:['Schrottzweihänder','Zweihandschwert','Schlachtzweihänder','Hünenklinge','Riesentöter','Kolossschneide','Atlas – Himmelsspalter'],
 javelin:['Wurfstock','Wurfspeer','Legionspilum','Falkenpilum','Adlerpilum','Himmelslanze','Fulgur – Blitzwurf'],
 throwaxe:['Wurfbeil aus Schrott','Wurfaxt','Jägerwurfbeil','Rabenwurfbeil','Falkenwurfbeil','Sturmwurfbeil','Aquilo – Nordwind'],
 net:['Flickennetz','Fangnetz','Arenanetz','Jägernetz','Kettennetz','Silbernetz','Fatum – Schicksalsnetz']};
const gearLooks=[
 {metal:'#8c7861',edge:'#b29d79',trim:'#59432f',cloth:'#695c46'},
 {metal:'#8d9892',edge:'#c2c5b0',trim:'#5d4834',cloth:'#685646'},
 {metal:'#a3b2ac',edge:'#dae1ca',trim:'#a4844e',cloth:'#456c65'},
 {metal:'#6e9699',edge:'#b7d6cc',trim:'#cbb782',cloth:'#395e76'},
 {metal:'#b9c0cb',edge:'#edf0db',trim:'#d9aa54',cloth:'#704754'},
 {metal:'#dec591',edge:'#fff0bc',trim:'#855a39',cloth:'#446c78'},
 {metal:'#e9d693',edge:'#fff4d3',trim:'#c06d45',cloth:'#703d68'}];
function itemTitle(i){if(!i)return 'Keine';const q=clamp(i.q||0,0,6),d=definition(i);if(i.kind==='weapon')return weaponTitles[i.def]?.[q]||d?.name||'?';const set=['Flicken','Rekruten','Legionärs','Veteranen','Prätorianer','Triumph','Unsterblichen'][q];return (i.kind==='armor'?(i.material==='leather'?'Leder · ':i.material==='medium'?'Verstärkt · ':'Metall · '):'')+set+'-'+(d?.name||'?');}
// Leder wird mit jeder Qualitätsstufe dunkler, edler und stärker beschlagen; verstärkte Rüstung zeigt Metallplatten auf Leder.
const leatherLooks=[
 {metal:'#927653',edge:'#b39770',trim:'#5a4630',dark:'#5a4630',stud:'#77664c',cloth:'#695c46'},
 {metal:'#805936',edge:'#b18c59',trim:'#4e3727',dark:'#4e3727',stud:'#9a8a68',cloth:'#685646'},
 {metal:'#77492c',edge:'#b98550',trim:'#3d2a1e',dark:'#3d2a1e',stud:'#b89a62',cloth:'#456c65'},
 {metal:'#6a3d27',edge:'#b0784a',trim:'#c9a55a',dark:'#2f211a',stud:'#c9a55a',cloth:'#395e76'},
 {metal:'#5a2c22',edge:'#a35c40',trim:'#d8b45e',dark:'#261a17',stud:'#dbdccb',cloth:'#704754'},
 {metal:'#33292c',edge:'#6d5a58',trim:'#d9b65c',dark:'#17151a',stud:'#ecd184',cloth:'#446c78'},
 {metal:'#5a1c27',edge:'#a8444a',trim:'#f0cf74',dark:'#26101a',stud:'#fff0bc',gem:'#5fd0c0',cloth:'#703d68'}];
const mediumLooks=gearLooks.map((look,q)=>({...look,leather:['#6f5a43','#6b4a30','#5f3d27','#553423','#4a2a20','#352626','#42202a'][q],dark:leatherLooks[q].dark}));
function itemLook(i){return (i?.kind==='armor'&&i.material==='leather'?leatherLooks:i?.kind==='armor'&&i.material==='medium'?mediumLooks:gearLooks)[clamp(i?.q||0,0,6)];}
function itemName(i){return i?itemTitle(i)+' · '+gearQuality[i.q]:'Keine';}

function itemPrice(kind,id,q){const d=(kind==='weapon'?weaponDefs:kind==='armor'?armorDefs:shieldDefs).find(x=>x.id===id);return Math.round(gearPrices[q]*(kind==='weapon'?(d.damage/16)*.8+.2:kind==='armor'?d.weight/9+.3:d.weight/10+.55))}
function itemStats(i){if(!i)return null;const workmanship=1+clamp(i.forgeQuality||0,-.1,.1)+clamp(i.refinement?.bonus||0,0,.1),d=definition(i),f=(i.q===0?.78:Math.pow(4,(i.q-1)/5)),condition=.55+.45*clamp(i.durability/i.maxDurability,0,1);const netThickness=d.id==='net'?3.6*f*condition*(1+i.up.sharp*.005)*(i.rolls?.damage??1)*workmanship:0;return {...d,netThickness,netDuration:netThickness,damage:d.damage*f*condition*(1+i.up.sharp*.005)*(i.rolls?.damage??1)*workmanship,range:d.range*(i.rolls?.range??1),delay:d.delay*(i.forgeRange?2-(i.rolls?.speed??1):1/(i.rolls?.speed??1))/(1+i.q*.012+i.up.balance*.003),weight:d.weight*(i.kind==='armor'&&i.material==='leather'?.40:i.material==='medium'?.68:1)*(1-i.q*.003)*(i.rolls?.weight??1),pen:clamp(((d.pen||0)+i.q*.01+i.up.penetration*.003)*(i.rolls?.pen??1),0,.85),protection:(d.protection||0)*(i.kind==='armor'&&i.material==='leather'?.65:i.material==='medium'?.82:1)*f*condition*(i.rolls?.protection??1)*workmanship,block:(d.block||0)*(1+i.q*.025)*(i.rolls?.block??1),area:d.area===undefined?undefined:clamp(d.area*(1+i.q*.035)*(i.rolls?.area??1),0,.78),crit:(1.45+i.q*.025)*(i.rolls?.crit??1)}}
let inventorySource=null,inventoryLength=-1,inventoryMap=new Map();function inventoryItem(id){if(!id)return undefined;if(inventorySource!==s.inventory||inventoryLength!==s.inventory.length){inventorySource=s.inventory;inventoryLength=s.inventory.length;inventoryMap=new Map(s.inventory.map(i=>[i.id,i]));}return inventoryMap.get(id)}
function allowedRanged(g,item){const id=typeof item==='string'?item:item?.def;return ({Fernkämpfer:['bow','crossbow'],Soldat:['net'],Assassine:['javelin','throwaxe']}[g.role]||[]).includes(id);}
// Nahkampfwaffe je Klasse: Fernkämpfer nur Dolch und kein Schild, Assassinen Kurzschwert, Gladius oder Axt, Soldaten alles.
const classMelee={Fernkämpfer:['dagger'],Assassine:['short','gladius','axe']};
function allowedMelee(g,item){const id=typeof item==='string'?item:item?.def,list=classMelee[g.role];return !list||list.includes(id);}
function allowedShield(g){return g.role!=='Fernkämpfer';}
function meleeRule(g){return g.role==='Fernkämpfer'?'Fernkämpfer tragen im Nahkampf nur den Dolch.':'Assassinen tragen Kurzschwert, Gladius oder Axt.';}
function normalizeClassGear(g){if(!g?.equipment)return;if(!g.enemyGear){const second=inventoryItem(g.equipment.secondary);if(second&&!allowedMelee(g,second))g.equipment.secondary=null;if(g.equipment.shield&&!allowedShield(g))g.equipment.shield=null;}const i=g.enemyGear?.weapon||inventoryItem(g.equipment.weapon);if(i&&definition(i).ammo&&!allowedRanged(g,i)){if(g.enemyGear)g.enemyGear.weapon=null;else g.equipment.weapon=null;}}
function gear(g,slot){const i=g.enemyGear?g.enemyGear[slot]:inventoryItem(g.equipment[slot]);return slot==='weapon'&&i&&definition(i).ammo&&!allowedRanged(g,i)?null:i}
function armorItems(g){return g.enemyGear?Object.values(g.enemyGear.armor||{}):Object.values(g.equipment.armor).map(inventoryItem).filter(Boolean)}
function weightGear(g){return [gear(g,'weapon'),gear(g,'secondary'),gear(g,'shield'),...armorItems(g)].filter(Boolean).reduce((v,i)=>v+definition(i).weight*(i.kind==='armor'&&i.material==='leather'?.40:i.material==='medium'?.68:1)*(1-i.q*.003)*(i.rolls?.weight??1),0)}
function health(g){let n=0,w=0;for(const [id]of parts){const k=['head','neck','chest','belly'].includes(id)?3:1;n+=(g.body[id].missing?0:g.body[id].hp)*k;w+=k}return n/w}
function limb(g,ids){return ids.reduce((a,id)=>a+(g.body[id].missing?0:clamp(g.body[id].hp/(100+g.body[id].chronic),.08,1)*(g.body[id].fracture?.28:1)),0)/ids.length}
function power(g){return Math.round((Object.values(g.stats).reduce((a,b)=>a+b)/17)*(.5+health(g)/200)+(itemStats(gear(g,'secondary')||gear(g,'weapon'))?.damage||4)*.6+armorItems(g).reduce((n,i)=>n+itemStats(i).protection,0)*.15)}
function capacity(){return Math.max(60,6+s.buildings.housing*3,s.roster.length)}function storageCapacity(){return Math.max(2000,30+s.buildings.storage*15,s.inventory.length)}
function price(g){if(g.recruitStandard)return 100;return Math.round(recruitPrices[g.quality]*(.9+(power(g)/100)*.3))}function marketValue(g){return Math.round(price(g)*(1+Math.min(.8,g.fights*.008)+g.fame/300)*health(g)/100)}
function refreshMarket(force=false){if(s.blindRecruitment){s.market=[];s.lastMarket=s.day;return true;}if(!force&&s.day-s.lastMarket<3)return false;s.market=Array.from({length:6},()=>{const g=makeGladiator(0);g.price=100;g.name='Rekrut aus '+g.origin;return g});s.lastMarket=s.day;return true}if(!s.market.length)refreshMarket(true);

function equippedBy(id){return s.roster.find(g=>['weapon','secondary','shield'].some(k=>g.equipment[k]===id)||Object.values(g.equipment.armor).includes(id))}
function buyItem(kind,id,q,material='metal'){if(!Number.isInteger(q)||q<0||q>6||!(kind==='weapon'?weaponDefs:kind==='armor'?armorDefs:shieldDefs).some(d=>d.id===id))return 'Ungültiger Gegenstand.';let cost=itemPrice(kind,id,q);if(s.gold<cost)return 'Nicht genug Gold.';if(s.inventory.length>=storageCapacity())return 'Lager ist voll.';const i=makeItem(kind,id,q,material);i.durability=i.maxDurability;s.inventory.push(i);s.gold-=cost;s.stats.spent+=cost;persist();return 'Gekauft: '+itemName(i)}
function equip(gid,iid,secondary=false){const g=s.roster.find(g=>g.id===gid),i=inventoryItem(iid);if(!g||!i)return 'Gegenstand fehlt.';if(secondary&&i.kind==='weapon'&&!definition(i).ammo&&!allowedMelee(g,i))return meleeRule(g);if(i.kind==='shield'&&!allowedShield(g))return 'Fernkämpfer tragen keinen Schild.';if(i.kind==='weapon'&&!secondary&&definition(i).ammo&&!allowedRanged(g,i))return 'Diese Fernwaffe passt nicht zur Klasse: Fernkämpfer – Bogen/Armbrust, Soldat – Netz, Assassine – Wurfaxt/Wurfspeer.';if(secondary&&i.kind==='weapon'&&definition(i).ammo)return 'Als Hauptwaffe ist eine Nahkampfwaffe erforderlich.';if(i.kind==='weapon'&&!secondary&&!definition(i).ammo)return 'Im Fernkampfplatz sind Wurfwaffen, Netze, Bögen und Armbrüste möglich.';const owner=equippedBy(iid);if(owner){for(const k of ['weapon','secondary','shield'])if(owner.equipment[k]===iid)owner.equipment[k]=null;for(const k in owner.equipment.armor)if(owner.equipment.armor[k]===iid)delete owner.equipment.armor[k]}if(secondary&&i.kind==='weapon'&&definition(i).ammo)return 'Als Hauptwaffe ist eine Nahkampfwaffe erforderlich.';if(i.kind==='armor')g.equipment.armor[i.def]=iid;else g.equipment[i.kind==='weapon'&&secondary?'secondary':i.kind]=iid;persist();return 'Ausrüstung zugewiesen.'}
function sellItem(id){const i=inventoryItem(id);if(!i)return '';if(equippedBy(id))return 'Zuerst den Gegenstand ablegen.';const gold=Math.round(itemPrice(i.kind,i.def,i.q)*.42*(i.durability/i.maxDurability));s.gold+=gold;s.inventory=s.inventory.filter(x=>x!==i);persist();return '+'+gold+' Gold'}
function addScar(g,id,reason){if(!g.scars.some(x=>x.part===id&&x.reason===reason))g.scars.push({part:id,day:s.day,reason});}
function injuryGrade(p){return p.missing?5:p.hp<20?4:p.hp<40?3:p.hp<65?2:p.hp<90?1:0}
function noteInjury(g,id,text,attacker=null,weapon=null){if(attacker)recordWound(g,id,text,attacker,weapon);const p=g.body[id];p.injury=text;p.grade=injuryGrade(p);g.history.unshift({day:s.day,text:partName(id)+': '+text});g.history=g.history.slice(0,100)}
function kill(g,cause,killer){if(g.dead)return;g.dead=true;g.cause=cause;g.killer=killer||'Unbekannt';if(!g.enemy){const entry={id:g.id,name:g.name,age:g.age,wins:g.wins,fights:g.fights,kills:g.kills,highest:g.highest,cause,killer:g.killer,day:s.day,scars:copy(g.scars),parents:copy(g.parents||null),killHistory:copy(g.killHistory||[])};try{window.MG?.onFallen?.(g,entry);}catch(e){console.warn(e);}s.fallen.unshift(entry);s.roster=s.roster.filter(x=>x.id!==g.id);s.teams=s.teams.map(t=>t.filter(id=>id!==g.id));log(g.name+' ist gefallen: '+cause);persist()}}
function advanceDay(days=1){if(s.battle)return 'Während eines Kampfes nicht möglich.';for(let d=0;d<days;d++){s.day++;window.MG?.chargeSold?.();for(const g of s.roster){g.fatigue=Math.max(0,g.fatigue-14-s.buildings.hospital);g.blood=Math.min(100,g.blood+12);const treatment=g.healing;for(const p of Object.values(g.body)){if(p.missing)continue;let heal=3+s.buildings.hospital+(treatment?[0,7,16,26][treatment.tier]:0);if(p.fracture){p.fracture.days=Math.max(0,p.fracture.days-(treatment?1+treatment.tier*.2:1));heal=Math.min(heal,2.5);if(p.fracture.days>0)p.hp=Math.min(p.hp,64);else {addScar(g,Object.keys(g.body).find(k=>g.body[k]===p),'Verheilter Bruch');p.fracture=null;}}if(p.internal){p.internal.days=Math.max(0,p.internal.days-1);heal=Math.min(heal,2);if(!p.internal.days)p.internal=null;}p.hp=Math.min(p.fracture?64:p.internal?60:100-p.chronic,p.hp+heal);p.pain=Math.max(0,p.pain-heal*.7);p.bleed=Math.max(0,p.bleed-4);p.grade=injuryGrade(p);if(!p.fracture&&!p.internal&&p.hp>=90-p.chronic)p.injury=p.chronic?'Dauerhafte Einschränkung':''}if(treatment){treatment.days--;if(treatment.days<=0)g.healing=null}if((s.day-g.birthday)%365===0)g.age++;g.stats.morale=clamp(g.stats.morale+1,1,g.caps.stats.morale)}if(s.day-s.lastMarket>=3)refreshMarket();if(s.sponsor&&s.day>s.sponsor.until){log('Der Sponsorenvertrag ist ausgelaufen.');s.sponsor=null}window.MG?.householdDay?.()}persist();return days+' Tag'+(days>1?'e':'')+' vergangen. Erholung und Heilung angewendet.'}
function train(){return 'Gladiatoren lernen durch ihre tatsächlichen Aktionen im Kampf. Es gibt keine manuelle Punktevergabe.'}

function medicalCost(g,tier){return Math.round((15+(100-health(g))*1.8+g.scars.length*3)*[0,1,3,7][tier]*Math.max(.5,1-s.buildings.medic*.05))}
function treat(id,tier){const g=s.roster.find(g=>g.id===id);if(!g)return '';const cost=medicalCost(g,tier);if(s.gold<cost)return 'Nicht genug Gold.';s.gold-=cost;s.stats.spent+=cost;g.healing=tier?{tier,days:4}:null;for(const [id,p]of Object.entries(g.body)){p.bleed=0;if(p.missing)continue;p.hp=Math.min(p.fracture?64:p.internal?60:100-p.chronic,p.hp+[0,8,20,35][tier]);p.pain=Math.max(0,p.pain-tier*10);if(tier>0&&p.chronic>0)p.chronic=Math.min(p.chronic,Math.max(1,Math.round(p.chronic*(1-[0,.03,.08,.18][tier])*100)/100));p.grade=injuryGrade(p)}g.blood=Math.min(100,g.blood+tier*15);persist();return tier?'Behandlung begonnen. Zusätzliche Heilung an den nächsten vier Tagen.':'Natürliche Heilung gewählt.'}
function retire(id){const g=s.roster.find(g=>g.id===id);if(!g)return '';if(g.fights<5)return 'Mindestens fünf Kämpfe für eine Trainerlaufbahn nötig.';ensureCareer(g);g.retired=true;g.trainerEnabled=true;g.trainerCaps=copy(g.mastery);const specialty=g.fame>=200?'tactics':g.skills.bow>g.skills.sword?'archery':'weapons';s.trainers.push({...g,specialty});s.roster=s.roster.filter(x=>x!==g);s.teams=s.teams.map(t=>t.filter(x=>x!==id));log(g.name+' arbeitet nun als Trainer.');persist();return 'Als Trainer eingestellt.'}
function buildingCost(k){return 0}function upgradeBuilding(k){return 'Gebäude-Upgrades sind entfernt.'}
function repairCost(i){return Math.max(0,Math.ceil((i.maxDurability-i.durability)*(.3+i.q*.6)));}
function repairEquipped(){if(s.battle)return 'Während eines Kampfes nicht möglich.';const items=s.inventory.filter(i=>equippedBy(i.id)&&i.durability<i.maxDurability),cost=items.reduce((n,i)=>n+repairCost(i),0);if(!items.length)return 'Alle angelegten Gegenstände sind intakt.';if(s.gold<cost)return 'Nicht genug Gold für alle angelegten Gegenstände.';s.gold-=cost;s.stats.spent+=cost;for(const i of items)i.durability=i.maxDurability;persist();return items.length+' angelegte Gegenstände für '+cost+' Gold repariert.';}
function forge(id,type){if(s.battle)return 'Während eines Kampfes nicht möglich.';if(type!=='repair')return 'Verfeinerungen sind entfernt. Ausrüstung kann repariert werden.';const i=inventoryItem(id);if(!i)return 'Gegenstand nicht gefunden.';const c=repairCost(i);if(s.gold<c)return 'Nicht genug Gold.';s.gold-=c;s.stats.spent+=c;i.durability=i.maxDurability;persist();return 'Ausrüstung repariert.'}
function makeEvent(){s.event=null;}
function resolveEvent(yes){const e=s.event;if(!e)return '';if(e.type==='trainer'){s.event=null;persist();return 'Trainer werden ausschließlich aus deinem eigenen Ruhestand berufen.';}const g=s.roster.find(g=>g.id===e.g);if(yes&&['merchant','wages','trainer'].includes(e.type)&&s.gold<e.cost)return 'Nicht genug Gold.';if(yes){if(e.type==='sponsor')s.sponsor={name:pick(['Haus Aelius','Die Goldene Amphore','Gilde der Schmiede']),until:s.day+15,bonus:.18};if(e.type==='merchant'){if(s.inventory.length>=storageCapacity())return 'Lager ist voll.';s.gold-=e.cost;s.inventory.push(e.item)}if(e.type==='wages'){s.gold-=e.cost;if(g)g.stats.morale=Math.min(g.caps.stats.morale,g.stats.morale+15)}if(e.type==='challenge')s.challenge={reward:leagues[s.fightLeague??s.league].reward*1.8,league:s.fightLeague??s.league};if(e.type==='trait'&&g){const t=pick(traits.filter(t=>!g.traits.includes(t)));g.traits.push(t);log(g.name+' entwickelt: '+t)}if(e.type==='prospect'){const r=makeGladiator(0);r.age=18;r.potential=98;delete r.caps;ensurePotentials(r);r.price=150;r.name='Junges Talent';s.market.push(r)}}else if(e.type==='wages'&&g)g.stats.morale=Math.max(15,g.stats.morale-12);s.event=null;persist();return yes?'Ereignis angenommen.':'Ereignis abgelehnt.'}
function recovery(){if(s.roster.length>=3&&s.gold>=100)return 'Die Schule ist noch handlungsfähig.';if(s.day-s.recoveryDay<7)return 'Nächste Notfallhilfe an Tag '+(s.recoveryDay+7)+'.';s.recoveryDay=s.day;s.gold+=350;log('Die Arena-Gilde gewährt 350 Gold für den Wiederaufbau.');persist();return '350 Gold Wiederaufbauhilfe. Gefallene bleiben verloren.'}
function selectedTeam(){return s.teams[s.teamIndex].map(id=>s.roster.find(g=>g.id===id)).filter(Boolean)}
function validateTeam(type='league',tournamentId){const team=selectedTeam();if(team.some(g=>g.smithAssigned))return 'Ein Gladiator arbeitet in der Schmiede. Löse zuerst seine Zuweisung.';if(team.length!==3)return 'Wähle genau drei Gladiatoren unter TEAM.';if(team.some(g=>g.age<18))return 'Nur Erwachsene ab 18 Jahren dürfen antreten.';if(team.some(g=>g.dead||g.body.head.missing||g.body.chest.hp<5))return 'Ein Gladiator ist nicht kampffähig.';if(type==='tournament'){const t=tournaments.find(x=>x.id===tournamentId);if(t.id==='melee'&&team.some(g=>itemStats(gear(g,'weapon'))?.ammo))return 'Nur Nahkampfwaffen sind zugelassen.';if(t.id==='light'&&team.some(g=>weightGear(g)>12))return 'Höchstens 12 kg Ausrüstung je Gladiator.';if(t.id==='ranged'&&team.some(g=>!itemStats(gear(g,'weapon'))?.ammo))return 'Alle drei brauchen Fernkampfwaffen.';if(t.id==='veteran'&&team.some(g=>g.fights<10))return 'Jeder Gladiator braucht zehn Kämpfe.';if(t.id==='champion'&&s.league<5)return 'Erst ab Champion-Liga.'}return ''}


const moveNames={pierce:'Durchstich',combo:'Zufällige 2er-/3er-/4er-Kombo',groundFinish:'Bodenabschluss',shieldBash:'Schildstoß',rearFinish:'Griff von hinten',slash:'Hieb',overhead:'Überkopfschlag',kick:'Tritt',rise:'Aufstehen',recover:'Standfestigkeit nach Treffern',dodge:'Ausweichen',charge:'Ansturm',backstep:'Rücksprung',thrust:'Stich',spin:'Drehschlag',sand:'Sandtritt'};
const statHelp={strength:'Erhöht den Nahkampfschaden. Wächst durch Schläge und Anstürme.',stamina:'Erhöht die maximale Kampfenergie. Wächst beim Laufen, Angreifen und Ausweichen.',condition:'Beschleunigt die Energieregeneration. Wächst bei Anstrengung im Kampf.',agility:'Erhöht Lauftempo und erschwert gegnerische Treffer. Wächst beim Bewegen und Ausweichen.',dexterity:'Verbessert Waffenführung, Trefferchance und Angriffstempo. Wächst beim Angreifen.',reflex:'Verbessert Reaktion, Konter und Ausweichentscheidungen. Wächst bei Blocks und Ausweichversuchen.',precision:'Verbessert Fernkampftreffer und kritische Treffer. Wächst durch Würfe und gezielte Treffer.',block:'Erhöht die Chance auf Schild- und Waffenblocks. Wächst durch Blockversuche und erfolgreiche Blocks.',balance:'Verringert Rückstoß. Wächst beim Blocken, Abfangen von Treffern und Anstürmen.',toughness:'Verringert den Schmerz durch Verletzungen. Wächst bei erlittenen Treffern.',pain:'Verringert den Leistungsverlust durch Schmerzen. Wächst beim Durchstehen von Treffern.',will:'Verringert Rückzug und Aufgabe bei Gefahr. Wächst beim Weiterkämpfen und Durchstehen von Treffern.',aggression:'Erhöht die Angriffshäufigkeit. Wächst durch Angriffsversuche.',tactics:'Verbessert Zielwahl und Positionierung. Wächst bei Zielentscheidungen.',teamwork:'Verbessert Hilfe für angegriffene Teamkameraden. Wächst bei tatsächlicher Unterstützung.',experience:'Verbessert Treffer, Entscheidungen und Reaktionen. Wächst bei Kampfaktionen.',morale:'Aktuelle Zuversicht: beeinflusst den Schaden. Schwankt mit Sieg, Niederlage, Erholung und Ereignissen; kein verteilbarer Skill.'};
const moveHelp={pierce:'Kräftiger Stich durch ein bereits verletztes Körperteil. Die Klinge wird anschließend herausgezogen. Der Schaden zählt einmalig als Durchstich. Nur geeignete Klingen- und Stichwaffen.',combo:'Nach jedem Schlag besteht eine Chance von 50 % auf einen weiteren Angriff, bis maximal vier Schläge. Folgeangriffe erhalten den bestehenden Trefferbonus. Verletzungen, Abwehr, Abstand und Ausdauer können die Serie beenden.',groundFinish:'Abschlussstich mit Klingen oder Abschlussschlag mit Schlagwaffen gegen am Boden liegende Gegner. Deutliches Ausholen, unterbrechbar und kein garantierter tödlicher Treffer. Wächst durch tatsächliche Versuche.',shieldBash:'Naher Stoß mit einem benutzbaren Schild. Verbraucht Ausdauer, stößt zurück und kann taumeln lassen. Wird durch tatsächlich ausgeführte Schildstöße trainiert.',rearFinish:'Abwehrbarer Abschlussangriff gegen abgelenkte oder bereits verletzte Gegner von hinten, nur mit einer Nahkampf-Klingenwaffe und zwei brauchbaren Armen. Dolche erhalten einen Bonus. Angriffsfertigkeit und Geschick werden gegen Reflexe, Blocken und Erfahrung geprüft. Kein garantierter Kill.',slash:'Wächst durch ausgeführte normale Hiebe und verbessert deren Schaden.',overhead:'Wächst durch ausgeführte Überkopfschläge. Mehr Schaden und Durchschlag, längeres Ausholen.',kick:'Wächst nur durch ausgeführte Tritte. Kurze Reichweite, verbraucht Energie, stößt Gegner zurück und kann sie aus dem Gleichgewicht bringen.',rise:'Wächst durch tatsächliche Aufstehversuche. Verkürzt das Aufrichten und senkt die Chance, erneut zu stürzen. Verletzungen, Blutverlust, Erschöpfung und verbrauchte Kampfenergie verlängern die Bodenphase deutlich. Verletzte oder fehlende Beine bleiben entscheidend.',recover:'Wächst beim Abfangen schwerer Treffer und beim Erholen vom Taumeln. Verkürzt das Taumeln.',sand:'Trick auf kurze Distanz. Sand stört kurz die Sicht; der Gegner reibt sich die Augen. Wächst nur durch den tatsächlichen Versuch.',thrust:'Wächst durch ausgeführte Stiche mit Dolch, Schwert, Speer oder Dreizack. Verbessert den Durchschlag.',spin:'Wächst durch versuchte Drehschläge mit geeigneten Nahkampfwaffen. Kann nahe Gegner treffen, kostet mehr Energie.',dodge:'Wächst bei kurzen Ausweichschritten und vermiedenen Treffern. Verbessert Reaktion und Erholungszeit. Mit gezogenem Bogen oder gezogener Armbrust sind Ausweichreaktion und Ausweicherfolg stark reduziert (Faktor 0,25). Nach dem Wechsel zur Nahkampfwaffe gilt wieder der normale Wert. Keine Rolle und keine garantierte Unverwundbarkeit.',charge:'Wächst beim Ansturmversuch und ausgeführten Sturmangriff. Erhöht Tempo und Bonusschaden; braucht Anlauf.',backstep:'Wächst beim Rücksprung nach Treffern. Verbessert Distanz, Ausweichchance und Erholungszeit.'};
function stableRoll(g,key){let h=2166136261;for(const c of g.id+':'+key)h=Math.imul(h^c.charCodeAt(0),16777619);h^=h>>>16;h=Math.imul(h,0x45d9f3b);h^=h>>>16;return(h>>>0)/4294967296}
function bernoulliValue(mean,n=64){let hits=0,p=clamp((mean-1)/99,.01,.98);for(let i=0;i<n;i++)if(rng()<p)hits++;return Math.round(1+99*hits/n);}
function personalCap(g,key,value){let hits=0,p=.52+g.potential*.0026;for(let i=0;i<32;i++)if(stableRoll(g,key+':trial:'+i)<p)hits++;return Math.max(Math.ceil(value||0),Math.round(1+99*hits/32));}
function ensurePotentials(g){for(const k of ['pierce','combo','dodge','thrust','spin','sand','slash','overhead','kick','rise','recover','rearFinish','shieldBash','groundFinish'])g.moves[k]??=Math.round(3+stableRoll(g,'initial:'+k)*7);if(!g.caps){const cap=(key,value)=>personalCap(g,key,value);g.caps={stats:Object.fromEntries(Object.entries(g.stats).map(([k,v])=>[k,cap('stat:'+k,v)])),weapons:Object.fromEntries(weaponDefs.map(w=>[w.id,cap('weapon:'+w.id,g.mastery?.[w.id]||10)])),moves:Object.fromEntries(Object.entries(g.moves).map(([k,v])=>[k,cap('move:'+k,v)])),body:Object.fromEntries(parts.map(([id])=>[id,{strength:cap('body-strength:'+id,g.body[id].strength),agility:cap('body-agility:'+id,g.body[id].agility)}]))};}for(const k of Object.keys(g.moves))g.caps.moves[k]??=personalCap(g,'move:'+k,g.moves[k]);delete g.talents;delete g.level;delete g.xp;return g.caps}

function learningValue(g,group,key){if(group==='body'){const [id,k]=key.split('.');return g.body[id][k]}return (group==='weapons'?g.mastery:g[group])[key]}
function learningCap(g,group,key){if(group==='body'){const [id,k]=key.split('.');return g.caps.body[id][k]}return g.caps[group]?.[key]??0}
function addLearning(g,group,key,amount){const cap=learningCap(g,group,key),value=learningValue(g,group,key);if(!Number.isFinite(value)||!cap||amount<=0)return 0;const gain=Math.max(0,Math.min(cap,value+amount)-value);if(group==='body'){const [id,k]=key.split('.');if(g.body[id].missing)return 0;g.body[id][k]+=gain}else(group==='weapons'?g.mastery:g[group])[key]+=gain;return gain}
function learn(a,group,key,amount){if(s.battle?.benchmark)return 0;if(!s.battle||s.battle.finale||s.battle.paused||a.g.dead||a.g.retired||a.down||a.surrendered||!s.battle.actors.includes(a))return 0;const g=a.g;if(!g.caps)ensureCareer(g);if(group==='weapons'&&!weaponDefs.some(w=>w.id===key))return 0;const building=group==='weapons'?(weaponDefs.find(w=>w.id===key)?.ammo?'archery':'weapons'):group==='moves'?'training':['strength','stamina','condition'].includes(key)?key==='strength'?'strength':'endurance':['tactics','teamwork'].includes(key)?'tactics':'training';let rate=(.7+g.potential/150)*(g.traits.includes('Schneller Lerner')?1.2:1)*(g.age>36?.75:1)*(1+(s.buildings[building]||0)*.03);if(group==='weapons'&&lesson(g,key).teacher)rate*=1.15;const gain=addLearning(g,group,key,amount*rate*(.08+.92*Math.pow(Math.max(0,(learningCap(g,group,key)-learningValue(g,group,key))/Math.max(1,learningCap(g,group,key))),.65)));a.learning??={};const path=group+':'+key;a.learning[path]=(a.learning[path]||0)+gain;return gain}
function applyLearningBonus(a){if(a.learningBonusApplied)return;a.learningBonusApplied=true;if((a.xpMultiplier||1)<=1||a.g.dead)return;for(const [path,amount]of Object.entries(a.learning||{})){const [group,key]=path.split(':');a.learning[path]+=addLearning(a.g,group,key,amount*((a.xpMultiplier||1)-1))}}
function learningLabel(path){const [group,key]=path.split(':');if(group==='stats')return stats[key];if(group==='moves')return moveNames[key];if(group==='weapons')return weaponDefs.find(w=>w.id===key)?.name||key;const [id,k]=key.split('.');return partName(id)+' · '+(k==='strength'?'Kraft':'Beweglichkeit')}
const mantleNames=['Leinen des Neulings','Staub des Sandes','Band des Kämpfers','Kupfersaum','Mantel des Siegers','Eid der Arena','Bronzeflamme','Wolfsfell','Rote Düne','Silbersaum','Stolz des Ludus','Karmesinband','Adlerschwinge','Goldene Amphore','Eiserner Lorbeer','Banner der Provinz','Löwenfell','Purpursaum','Triumph von Marmor','Stern von Rom','Mantel des Tribuns','Schild des Volkes','Rubinbanner','Nacht des Champions','Glut des Imperiums','Goldener Adler','Lorbeer des Senats','Königlicher Purpur','Sonnenbrokat','Eid der Unsterblichen','Sturm des Mars','Krone der Asche','Saphir des Himmels','Mantel des Prätors','Flügel der Aurora','Kaisersammet','Löwe des Firmaments','Purpur der Titanen','Gewebe des Schicksals','Gold der Ewigkeit','Sternenlorbeer','Feuer des Olymp','Triumph der Götter','Banner der Äonen','Mantel des Weltenherrschers','Sonne des Unsterblichen','Seide der Legenden','Krone der Zeiten','Letzter Morgenstern','Mantel der Unendlichkeit'];
const mantles=mantleNames.map((name,i)=>({tier:i+1,name,fame:Math.round(20*(Math.pow(1.24,i+1)-1)/.24),color:['#706348','#3f7974','#984332','#465786','#755183','#b18739','#466b49','#923d62','#356d88','#9b713b'][i%10],trim:i<10?'#a48c65':i<25?'#d0bb88':i<40?'#e7c566':'#f6df96',pattern:Math.floor(i/10),length:22+Math.floor(i/5)*2}));
function mantle(g){return [...mantles].reverse().find(m=>g.fame>=m.fame)||null}
function nextMantle(g){return mantles.find(m=>g.fame<m.fame)||null}

// Existing saves are extended in place. Recorded item rolls never change on reload.
function ensureCareer(g){if(g.moves&&g.caps){for(const k of ['pierce','combo']){g.moves[k]??=Math.round(3+stableRoll(g,'initial:'+k)*7);g.caps.moves[k]??=personalCap(g,'move:'+k,g.moves[k]);}}if(g.mastery&&g.caps){for(const id of ['bow','crossbow']){g.mastery[id]??=10;g.caps.weapons[id]??=Math.max(g.mastery[id],g.potential||60);}}if(g.caps&&g.mastery&&g.killHistory&&g.moves?.thrust!==undefined&&g.caps.moves.thrust!==undefined&&g.moves.sand!==undefined&&g.caps.moves.sand!==undefined&&g.moves.recover!==undefined&&g.caps.moves.recover!==undefined&&g.moves.rearFinish!==undefined&&g.caps.moves.rearFinish!==undefined&&g.moves.shieldBash!==undefined&&g.caps.moves.shieldBash!==undefined&&g.moves.groundFinish!==undefined&&g.caps.moves.groundFinish!==undefined){delete g.level;delete g.xp;delete g.talents;return g;}ensureIdentity(g);if(!g.mastery){const family=id=>['spear','trident','halberd'].includes(id)?'spear':['shortbow','longbow','sling','gastraphetes'].includes(id)?'bow':['javelin','throwaxe'].includes(id)?'throw':'sword';g.mastery=Object.fromEntries(weaponDefs.map(w=>[w.id,clamp(g.skills?.[family(w.id)]??10,1,100)]))}for(const w of weaponDefs)g.mastery[w.id]??=10;if(g.trainingWeapon&&!weaponDefs.some(w=>w.id===g.trainingWeapon))g.trainingWeapon='short';if(!g.killHistory){g.killHistory=[];g.unrecordedKills=g.kills||0}if(g.retired&&!g.trainerCaps)g.trainerCaps=copy(g.mastery);ensurePotentials(g);return g}
function mastery(g,id){ensureCareer(g);return g.mastery[id]||0}

function combatPractice(g,id,amount=.008){const a=s.battle?.actors.find(a=>a.g.id===g.id);if(a)learn(a,'weapons',id,amount)}
function lesson(g,id=gear(g,'weapon')?.def||'fist'){ensureCareer(g);const teacher=s.trainers.filter(t=>t.retired&&t.trainerEnabled!==false&&t.trainerCaps?.[id]>mastery(g,id)).sort((a,b)=>b.trainerCaps[id]-a.trainerCaps[id])[0];return {id,teacher,cap:teacher?Math.min(teacher.trainerCaps[id],g.caps.weapons[id]):0,rate:teacher?.15:0}}

function setTrainingWeapon(id,weapon){const g=s.roster.find(g=>g.id===id);if(g&&weaponDefs.some(w=>w.id===weapon)){g.trainingWeapon=weapon;persist()}}
function toggleTrainer(id){const t=s.trainers.find(t=>t.id===id&&t.retired);if(!t)return 'Nur eigene pensionierte Gladiatoren können unterrichten.';t.trainerEnabled=t.trainerEnabled===false;persist();return t.trainerEnabled?'Mentor für Kampferfahrung aktiviert.':'Mentor pausiert.'}
s.smiths??=[];
for(const g of [...s.roster,...s.market,...s.trainers,...(s.battle?.actors.map(a=>a.g)||[])])ensureCareer(g);
const forgeCategories=[...weaponDefs.map(d=>({key:'weapon/'+d.id,name:d.name,kind:'weapon',def:d.id})),...armorDefs.map(d=>({key:'armor/'+d.id,name:d.name,kind:'armor',def:d.id})),...shieldDefs.map(d=>({key:'shield/'+d.id,name:d.name,kind:'shield',def:d.id}))];
// Sum of Bernoulli trials: bell-shaped binomial distribution, no clipped upper tail.
// P(Soll=100) = .58^24, approximately 1 in 475,000 per category.
function smithRoll(p=.58){let successes=0;for(let n=0;n<24;n++)if(rng()<p)successes++;return successes;}
function smithPotential(){return Math.round(20+80*smithRoll()/24);}
function ensureSmith(t){t.categories??={};for(const c of forgeCategories){if(!t.categories[c.key]){const current=clamp(t.skill??(8+2*smithRoll(.5)),1,100);t.categories[c.key]={current,potential:Math.max(current,smithPotential())}}}t.crafted??=0;delete t.skill;delete t.level;delete t.xp;return t}
function ensureGladiatorSmith(g){if(!g.smith){let seed=2166136261;for(const c of g.id)seed=Math.imul(seed^c.charCodeAt(0),16777619);const r=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296};const bin=p=>{let n=0;for(let j=0;j<24;j++)if(r()<p)n++;return n};g.smith={};for(const c of forgeCategories){const current=Math.round(1+99*bin(19/99)/24);g.smith[c.key]={current,potential:Math.max(current,Math.round(20+80*bin(.58)/24))}}}for(const c of forgeCategories)g.smith[c.key]??={current:30,potential:65};return g.smith;}
function forgeStaff(){return s.roster.filter(g=>g.smithAssigned&&!g.dead&&!g.retired);}
function forgeKnowledge(key){const staff=forgeStaff();for(const g of staff)ensureGladiatorSmith(g);const lead=staff.sort((a,b)=>b.smith[key].current-a.smith[key].current)[0];return lead?{...lead.smith[key],lead}:{current:0,potential:0,lead:null};}
function assignSmith(id){if(s.battle)return 'Während eines Kampfes nicht möglich.';const g=s.roster.find(g=>g.id===id);if(!g)return 'Gladiator nicht gefunden.';ensureGladiatorSmith(g);g.smithAssigned=!g.smithAssigned;persist();return g.name+(g.smithAssigned?' arbeitet jetzt in der Schmiede.':' steht wieder für Arenakämpfe bereit.');}
function progressForge(i,base=.12){const k=forgeKnowledge(i.kind+'/'+i.def);if(!k.lead)return 0;const gain=Math.min(k.potential-k.current,base*Math.pow(Math.max(0,(k.potential-k.current)/Math.max(1,k.potential)),.75));k.lead.smith[i.kind+'/'+i.def].current+=gain;k.lead.smithCrafted=(k.lead.smithCrafted||0)+1;return gain;}
function smithHireCost(){return 0}
function hireSmith(){return 'Weise einen Gladiator aus deinem Kader der Schmiede zu.'}
function trainSmith(){return 'Gladiatoren lernen das Schmieden durch Herstellung.'}
function selectSmith(){return forgeStaff()[0]||null}
function reforgeCost(i){return Math.round(Math.max(35,itemPrice(i.kind,i.def,i.q)*.18)*(1+(i.reforges||0)*.08))}
function rollForge(i){const k=forgeKnowledge(i.kind+'/'+i.def),roll=()=>.9+.2*Math.pow(rng(),1/(.65+k.current/100));i.rolls=Object.fromEntries(['damage','speed','range','weight','pen','block','crit','protection','area'].map(key=>[key,key==='weight'?2-roll():roll()]));i.maxDurability=Math.round((100+i.q*10)*roll());i.durability=i.maxDurability;i.maker=k.lead?.name||'Schmiede';i.forgedDay=s.day;i.forgeRange=.10;return progressForge(i)}
function reforge(){return 'Umschmieden ist nicht mehr möglich.'}
function craft(kind,def,q,material='metal'){if(s.battle)return 'Während eines Kampfes nicht möglich.';if(!forgeStaff().length)return 'Weise zuerst einen Gladiator der Schmiede zu.';if(!forgeCategories.some(c=>c.kind===kind&&c.def===def)||!Number.isInteger(q)||q<0||q>6)return 'Ungültige Kategorie.';if(s.inventory.length>=storageCapacity())return 'Lager ist voll.';const cost=Math.round(itemPrice(kind,def,q)*.9);if(s.gold<cost)return 'Nicht genug Gold.';s.gold-=cost;s.stats.spent+=cost;const i=makeItem(kind,def,q,material);rollForge(i);s.inventory.push(i);persist();return itemName(i)+' hergestellt von '+i.maker+'.'}
for(const g of [...s.roster,...s.market,...s.trainers])ensureGladiatorSmith(g);
s.event=null;
if(!s.standardRecruitMigration){refreshMarket(true);s.standardRecruitMigration=true;}
for(const g of [...s.roster,...s.market,...s.trainers,...(s.battle?.actors.map(a=>a.g)||[])]){ensureGladiatorSmith(g);if(!roles.includes(g.role))g.role=['Flankierer','Duellist'].includes(g.role)?'Assassine':'Soldat';}
// Remove discontinued gear, including equipped and in-flight weapons, without touching careers.
const removedWeapons=new Set(['shortbow','longbow','gastraphetes','sling']);
const retiredGear=new Set(s.inventory.filter(i=>i.kind==='weapon'&&removedWeapons.has(i.def)).map(i=>i.id));
s.inventory=s.inventory.filter(i=>!retiredGear.has(i.id));
for(const g of [...s.roster,...s.market,...s.trainers,...(s.battle?.actors.map(a=>a.g)||[])]){for(const slot of ['weapon','secondary']){if(retiredGear.has(g.equipment?.[slot]))g.equipment[slot]=null;if(g.enemyGear?.[slot]&&removedWeapons.has(g.enemyGear[slot].def))g.enemyGear[slot]=null;}for(const id of removedWeapons){if(g.mastery)delete g.mastery[id];if(g.trainerCaps)delete g.trainerCaps[id]}}
if(s.battle){for(const a of s.battle.actors){const w=gear(a.g,'weapon');if(w?.def==='javelin')a.ammo=Math.min(a.ammo,3);if(w?.def==='net')a.ammo=Math.min(a.ammo,1);}s.battle.projectiles=(s.battle.projectiles||[]).filter(p=>!removedWeapons.has(p.snapshot?.w?.id)&&p.kind!==6);for(const a of s.battle.actors){if(!gear(a.g,'weapon')){a.ammo=0;a.wind=0;a.swing=0;a.disarmed=false;}}}
if(s.event?.item&&removedWeapons.has(s.event.item.def))s.event=null;
if(!s.reforgeMigration){let refund=0;if(s.materials)refund=Math.round((s.materials.ore||0)*4+(s.materials.wood||0)*3+(s.materials.leather||0)*4);for(const t of s.smiths){if(t.job){refund+=Math.ceil(gearPrices[t.job.charge||2]/60)*60;t.job=null;}}s.gold+=refund;if(refund)log('Umstellung der Schmiede: '+refund+' Gold für Material und offene Aufträge erstattet.');s.reforgeMigration=true;}delete s.materials;
for(const g of [...s.roster,...s.market,...s.trainers,...(s.battle?.actors.map(a=>a.g)||[])])for(const p of Object.values(g.body||{})){if(!p.fracture&&/bruch/i.test(p.injury)&&p.hp<90)p.fracture={days:21,severe:p.hp<35};}for(const g of s.fallen){delete g.level;delete g.xp;}
persist();

if(s.battle)for(const a of s.battle.actors){if(a.team===0){const g=s.roster.find(g=>g.id===a.g.id);if(g)a.g=g}}
if(!s.battle)for(const g of s.roster){const w=gear(g,'weapon');if(w&&!definition(w).ammo){if(!gear(g,'secondary'))g.equipment.secondary=w.id;g.equipment.weapon=null;}}
for(const g of [...s.roster,...s.trainers])normalizeClassGear(g);
return {allowedRanged,normalizeClassGear,allowedMelee,allowedShield,classMelee,forgeStaff,assignSmith,ensureGladiatorSmith,repairCost,repairEquipped,bernoulliValue,itemTitle,itemLook,smithPotential,gaussian,forgeCategories,forgeKnowledge,progressForge,smithHireCost,ensureSmith,craft,moveNames,statHelp,moveHelp,ensurePotentials,learningValue,learningCap,addLearning,learn,applyLearningBonus,learningLabel,mantles,mantle,nextMantle,ensureIdentity,recordWound,wishes,skinPalette,hairPalette,ensureCareer,mastery,combatPractice,lesson,setTrainingWeapon,toggleTrainer,hireSmith,trainSmith,selectSmith,reforgeCost,reforge,s,stats,parts,partName,branches,traits,origins,qualities,recruitPrices,gearQuality,gearPrices,weaponDefs,armorDefs,shieldDefs,roles,leagues,buildings,trainingDefs,tournaments,clamp,uid,copy,rng,rnd,pick,persist,log,makeGladiator,makeItem,definition,itemName,itemPrice,itemStats,inventoryItem,gear,armorItems,weightGear,health,limb,power,capacity,storageCapacity,price,marketValue,refreshMarket,equippedBy,buyItem,equip,sellItem,addScar,injuryGrade,noteInjury,kill,advanceDay,train,medicalCost,treat,retire,buildingCost,upgradeBuilding,forge,makeEvent,resolveEvent,recovery,selectedTeam,validateTeam,get storageError(){return storageError||window.MGSave?.error}};
})();
