'use strict';
(()=>{
const M=window.MG,S=M.s,W=M.workshop,F=W.state,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,disabled=false)=>`<button class="btn" data-action="smith:${action}" ${disabled?'disabled':''}>${label}</button>`;
let offerPage=0,itemPage=0,recipeTab='weapon',clock=0,paintClock=0,scene=null,sceneStarting=false,backdrop=null;
const figures=new Map();
function actor(p,apprentice=false){if(figures.has(p.id))return figures.get(p.id);const rng=S.rng,g=M.makeGladiator(0);S.rng=rng;g.id=p.id;g.name=p.name;g.appearance={...p.appearance};g.height=p.height;g.weight=p.weight;g.muscle=apprentice?37:58;g.fame=0;g.scars=[];g.equipment={weapon:null,secondary:null,shield:null,armor:{}};g.enemyGear={weapon:null,secondary:null,shield:null,armor:{}};const hammer=M.makeItem('weapon','hammer',1),sword=M.makeItem('weapon','gladius',1);const a={id:p.id,g,team:0,x:apprentice?790:653,y:270,a:0,phase:0,state:'idle',energy:100,ammo:0,moveSpeed:0,forgeWorker:true,hammer,sword,apprentice,bloodMarks:{},work:0,nextWork:0};figures.set(p.id,a);return a;}
function skills(p,apprentice=false){return ['weapon','armor','shield'].map(kind=>`<details><summary>${{weapon:'Waffen',armor:'Rüstungen',shield:'Schilde'}[kind]}</summary><div class="smith-skills">${W.categories.filter(c=>c.kind===kind).map(c=>{const k=W.knowledge(c.key),v=p.potentials[c.key],gain=v-k.potential;return `<div><span>${esc(c.name)}</span><b>${apprentice?k.potential+' → '+v:k.current.toFixed(1)+' / '+v}</b>${apprentice?`<small class="${gain>0?'better':'tiny'}">${gain>0?'+'+gain+' möglich':'keine Verbesserung'}</small>`:''}</div>`;}).join('')}</div></details>`).join('');}
const material=i=>i.kind==='armor'?{leather:'Leder',medium:'Verstärkt',metal:'Metall'}[i.material||'metal']:'';
function recipeList(){const refinement=recipeTab==='refinement',cats=W.categories.filter(c=>refinement||recipeTab==='weapon'?(refinement||c.kind==='weapon'):c.kind!=='weapon');return `<div class="buttons">${[['weapon','Waffen'],['armor','Rüstungen'],['refinement','Verfeinerungen']].map(([id,n])=>button(n,'recipes:'+id,recipeTab===id)).join('')}</div><div class="smith-recipes">${cats.map(c=>{if(refinement)return `<div>${esc(c.name)} <b>${F.refinements.includes(c.key)?'+10 %':'???'}</b></div>`;const rs=W.recipes.filter(r=>r.key===c.key);return `<details><summary>${esc(c.name)} · ${rs.filter(r=>F.recipes.includes(r.id)).length}/${rs.length}</summary>${rs.map(r=>{const known=F.recipes.includes(r.id);return `<div class="smith-recipe${known?' known':''}"><span>${M.gearQuality[r.q]}</span><span>${known?esc(M.itemTitle(r)):'???'}</span><b>${known?'Bekannt':'???'}</b></div>`;}).join('')}</details>`;}).join('')}</div>`;}
function apprenticeDesk(){const free=S.roster.filter(g=>!g.dead&&!g.retired&&!g.smithDuty).sort((a,b)=>a.name.localeCompare(b.name)),queue=W.queueList();return `<div class="smith-send"><h3>Gladiator in die Lehre geben</h3><p class="tiny">Wer am Amboss steht oder wartet, kostet keinen Sold und kämpft nicht. Die Lehre dauert zehn Spieltage. Kein Lehrling hat die Abschlussprüfung je überlebt.</p>${free.length?`<div class="toolbar"><label for="smithGladiator">Gladiator <select id="smithGladiator" class="select">${free.map(g=>`<option value="${g.id}">${esc(g.name)} · ${esc(g.role)} · Talent ${Math.round(g.potential??50)}</option>`).join('')}</select></label>${button('IN DIE LEHRE GEBEN','send')}</div>`:'<p class="tiny">Kein freier Gladiator im Kader.</p>'}${F.plea?`<p class="smith-plea">${esc(F.plea.name)}: „${esc(F.plea.line)}“</p>`:''}<h3>Warteschlange · ${queue.length}</h3>${queue.length?`<ol class="smith-queue">${queue.map((g,n)=>`<li><span><b>${n+1}.</b> ${esc(g.name)} <small>${esc(g.role)} · Talent ${Math.round(g.potential??50)}</small></span>${button('Zurückholen','recall:'+g.id)}</li>`).join('')}</ol>`:'<p class="tiny">Niemand wartet. Der Nächste rückt nach, sobald der Platz am Amboss frei ist.</p>'}</div>`;}
// Schmied-Shop als Katalog: Waffen | Rüstungen → Art mit Anzahl → aufklappen → Angebote → kaufen. Nur Darstellung der vorhandenen Angebote.
let shopTab='weapon',shopOpen='';
const axisOf=i=>i.def==='net'?'netThickness':i.kind==='weapon'?'damage':'protection',axisName=i=>({damage:'Schaden',protection:'Schutz',netThickness:'Netzdicke'})[axisOf(i)],days=i=>Math.max(1,i.forgedDay+W.shelfDays-S.day);
function offerRow(o,locked){const i=o.item,q=Math.round((i.forgeQuality||0)*100);return `<div class="smith-row"><button class="smith-row-main" data-action="smith:info:${i.id}" aria-label="Details zu ${esc(M.itemName(i))}"><b>${M.gearQuality[i.q]}</b><span>${esc(M.itemTitle(i))}</span><small>${axisName(i)} ${M.itemStats(i)[axisOf(i)].toFixed(1)} · Güte ${q>0?'+':''}${q} % · noch ${days(i)} ${days(i)===1?'Tag':'Tage'}</small></button><div class="smith-row-buy"><strong>${o.price} Gold</strong>${button('KAUFEN','buy:'+i.id,locked||S.gold<o.price)}</div></div>`;}
function shop(master,locked){if(!master)return '';const weapon=shopTab==='weapon',cats=W.categories.filter(c=>weapon?c.kind==='weapon':c.kind!=='weapon'),by={};for(const o of F.offers)(by[W.key(o.item)]??=[]).push(o);const total=w=>F.offers.filter(o=>(o.item.kind==='weapon')===w).length,stocked=cats.filter(c=>by[c.key]),empty=cats.filter(c=>!by[c.key]);if(shopOpen&&!by[shopOpen])shopOpen='';
 return `<section class="smith-section smith-shop" id="smithShop"><h2>Schmied · Shop</h2><p class="tiny">${esc(master.name)} schmiedet an jedem Spieltag ${W.daily} Stücke. Jedes bleibt ${W.shelfDays} Spieltage im Angebot.</p>${F.comment?`<p class="smith-plea">„${esc(F.comment)}“</p>`:''}<div class="smith-tabs" role="tablist">${[['weapon','WAFFEN',total(true)],['armor','RÜSTUNGEN',total(false)]].map(([id,n,count])=>`<button class="btn${shopTab===id?' active':''}" role="tab" aria-selected="${shopTab===id}" data-action="smith:shop:${id}">${n} · ${count}</button>`).join('')}</div>${stocked.length?`<div class="smith-cats">${stocked.map(c=>{const list=[...by[c.key]].sort((a,b)=>a.item.q-b.item.q||a.price-b.price),open=shopOpen===c.key;return `<div class="smith-cat${open?' open':''}"><button class="smith-cat-head" data-action="smith:cat:${c.key}" aria-expanded="${open}"><span>${open?'▼':'▶'} ${esc(c.name)}</span><b>${list.length} verfügbar</b></button>${open?`<div class="smith-cat-list">${list.map(o=>offerRow(o,locked)).join('')}</div>`:''}</div>`;}).join('')}</div>`:`<p>Der Schmied hat gerade keine ${weapon?'Waffen':'Rüstungen'} im Angebot.</p>`}${empty.length?`<p class="tiny">Derzeit nicht im Angebot: ${empty.map(c=>esc(c.name)).join(', ')}</p>`:''}</section>`;}
function offerInfo(id){const o=F.offers.find(o=>o.item.id===id);if(!o)return;const i=o.item,axis=axisOf(i),base=M.itemStats({...i,forgeQuality:0,refinement:null}),actual=M.itemStats(i),q=Math.round((i.forgeQuality||0)*100),locked=W.saving||!!F.apprentice?.phase;M.ui.modal(esc(M.itemTitle(i)),`<div class="smith-offer"><canvas data-gear="${i.kind}:${i.def}:${i.q}:${i.material||''}" aria-label="${esc(M.itemName(i))}"></canvas><p>${M.gearQuality[i.q]} · ${esc(M.definition(i).name)}</p><dl><dt>Basis${axis==='damage'?'schaden':axis==='protection'?'schutz':'netzdicke'}</dt><dd>${base[axis].toFixed(2)}</dd><dt>Schmiedequalität</dt><dd>${q>0?'+':''}${q} %</dd><dt>Tatsächlicher Wert</dt><dd>${actual[axis].toFixed(2)}</dd><dt>Schmiedekönnen</dt><dd>${i.forgeSkill.current} / ${i.forgeSkill.potential}</dd><dt>Geschmiedet</dt><dd>${i.forgedDay===S.day?'heute':'Tag '+i.forgedDay} · noch ${days(i)} ${days(i)===1?'Tag':'Tage'}</dd><dt>Gewicht</dt><dd>${actual.weight.toFixed(1)} kg</dd><dt>Preis</dt><dd>${o.price} Gold</dd></dl></div>`,button('KAUFEN · '+o.price+' GOLD','buy:'+i.id,locked||S.gold<o.price)+button('ABLEHNEN','reject:'+i.id,locked));M.paintGear?.();}
function page(){const master=F.master,a=F.apprentice,locked=W.saving||!!a?.phase;offerPage=Math.max(0,Math.min(offerPage,Math.ceil(F.offers.length/12)-1));itemPage=Math.max(0,Math.min(itemPage,Math.ceil(S.inventory.length/12)-1));return `<div class="page-head"><h1>Schmiede</h1></div><section class="smith-workplace"><canvas id="smithScene" width="660" height="420" aria-label="Hauptschmied und Lehrling bei der Arbeit"></canvas><div><h2>${master?esc(master.name):'Hauptschmied'}</h2>${master?`<p>${master.crafted} Teile hergestellt · kein Unterhalt</p><h3>Ist / Soll</h3>${skills(master)}`:button('HAUPTSCHMIED EINSTELLEN · 250 GOLD','hire',S.gold<250)}</div></section>${W.error?`<p role="alert">${esc(W.error)}</p>`:''}${shop(master,locked)}<section class="smith-section"><h2>Lehrling</h2>${a?`<div class="smith-apprentice"><canvas id="smithApprentice" width="120" height="120" aria-label="${esc(a.name)}"></canvas><div><h3>${esc(a.name)}</h3><p>${a.phase?'Ausbildung abgeschlossen':Math.max(0,a.endsDay-S.day)+' Spieltage verbleiben'}</p>${a.phase?button('ABSCHLUSS ANSEHEN','ceremony',W.saving):''}</div></div>${skills(a,true)}`:button('LEHRLING EINSTELLEN','apprentice',!master||locked)}${master?apprenticeDesk():''}</section><section class="smith-section"><h2>Rezepte</h2>${recipeList()}</section><section class="smith-section"><h2>Verfeinern & Reparieren</h2><div class="buttons">${button('‹','items:-1',itemPage===0)}<span>Seite ${itemPage+1}</span>${button('›','items:1',(itemPage+1)*12>=S.inventory.length)}<button class="btn" data-action="army:repairall">Beschädigte Teile reparieren</button></div>${S.inventory.slice(itemPage*12,itemPage*12+12).map(i=>`<details><summary>${esc(M.itemName(i))}${i.refinement?' · verfeinert':''}</summary><p>${esc(M.equippedBy(i.id)?.name||'Im Lager')}</p><div class="buttons">${button(i.refinement?'Bereits verfeinert':F.refinements.includes(W.key(i))?'VERFEINERN · '+W.refineCost(i)+' GOLD':'Rezept unbekannt','refine:'+i.id,!master||locked||!!i.refinement||!F.refinements.includes(W.key(i))||S.gold<W.refineCost(i))}<button class="btn" data-action="forge:${i.id}:repair" ${M.repairCost(i)?'':'disabled'}>Reparieren · ${M.repairCost(i)} Gold</button></div></details>`).join('')}</section>`;}
M.workshopPage=page;
const oldPage=M.schoolPage;M.schoolPage=p=>p==='forge'?page():oldPage(p);
const oldClick=M.schoolClick;M.schoolClick=action=>{if(['slotcraft','slotcraftconfirm','craftdialog','craft','goforge'].includes(action.split(':')[0])||action==='army:craft'){M.ui.close();M.ui.click('nav:forge');return true;}if(!action.startsWith('smith:'))return oldClick(action);if(S.battle)return true;const [,a,b]=action.split(':');let message='';if(a==='hire')message=W.hireMaster();if(a==='apprentice')message=W.hireApprentice();if(a==='send')message=W.sendGladiator(b||$('smithGladiator')?.value||'');if(a==='recall')message=W.recallGladiator(b);if(a==='buy'||a==='reject'){message=a==='buy'?W.buy(b):W.reject(b);M.ui.close();}if(a==='shop'){shopTab=b==='armor'?'armor':'weapon';shopOpen='';}if(a==='cat')shopOpen=shopOpen===b?'':b;if(a==='info'){offerInfo(b);return true;}if(a==='refine')message=W.refine(b);if(a==='offers')offerPage+=+b;if(a==='items')itemPage+=+b;if(a==='recipes')recipeTab=b;if(a==='ceremony')startScene();if(message)M.ui.notify(message);M.ui.render();return true;};
// Reine Darstellung: feste Arbeitsfolgen, zeitbasierte Wege, keine Karriere-Zufallszahlen.
const stations={heat:{x:762,y:241,a:0},hammer:{x:651,y:246,a:0},quench:{x:752,y:291,a:0},grind:{x:691,y:291,a:0},rack:{x:675,y:251,a:Math.PI},bellows:{x:850,y:261,a:Math.PI},rest:{x:738,y:257,a:0},bench:{x:819,y:293,a:0}};
const masterJobs=[['heat',4],['hammer',7],['quench',3],['grind',5],['rack',2],['rest',3]],helperJobs=[['bellows',8],['rest',3],['bench',4],['bellows',7],['rest',2]];
function idle(a,t){
 const dt=Math.max(0,Math.min(.1,t-(a.workTime??t)));a.workTime=t;
 a.phase=t*5;a.wind=0;a.swing=0;a.wipeTimer=0;a.forgePose='';a.forgeTask='';a.forgeHold='';a.state='idle';a.moveSpeed=0;a.g.enemyGear.secondary=null;
 const jobs=a.apprentice?helperJobs:masterJobs;a.jobIndex??=0;a.jobElapsed??=0;
 let [job,duration]=jobs[a.jobIndex],target=stations[job];
 // Each station is approached through the clear aisle; no diagonal walk through equipment.
 if(a.jobTarget!==job){a.jobTarget=job;a.workRoute=[{x:a.x,y:263},{x:target.x,y:263},{x:target.x,y:target.y}];}
 const point=a.workRoute[0];
 if(point){const dx=point.x-a.x,dy=point.y-a.y,d=Math.hypot(dx,dy),step=Math.min(d,dt*34);if(d<.4){a.x=point.x;a.y=point.y;a.workRoute.shift();}else{a.x+=dx/d*step;a.y+=dy/d*step;a.a=Math.abs(dx)>.2?(dx>0?0:Math.PI):target.a;a.moveSpeed=34;a.state='move';}return;}
 a.a=target.a;a.forgeTask=job;a.jobElapsed+=dt;a.workBeat=a.jobElapsed;
 if(job==='rest'&&a.jobElapsed<1.3)a.wipeTimer=1;
 if(a.jobElapsed>=duration){a.jobIndex=(a.jobIndex+1)%jobs.length;a.jobElapsed=0;a.jobTarget=null;}
}
function stationMotion(ctx,list){
 const r=(x,y,w,h,c)=>{ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);},operator=list.find(a=>a.forgeTask==='bellows'),pump=operator?(1+Math.sin(operator.workBeat*4))/2:.3;
 // The same phase drives hands, lever and leather folds.
 const top=228-pump*5;r(826,top,26,3,'#a58052');r(828,top+3,23,239-top-3,'#704b36');for(let y=top+4;y<239;y+=3)r(829,y,21,1,'#3f3429');r(825,239,28,2,'#ad895a');r(843,top-1,12,2,'#b5976e');
 for(let n=0;n<4;n++){const f=(clock*2+n*.31)%1;r(786+n*7,211-f*(5+pump*5),4,5+f*3,n%2?'#f5c56b':'#d77b37');}
 const grinder=list.find(a=>a.forgeTask==='grind');if(grinder){for(let n=0;n<4;n++){const angle=grinder.workBeat*6+n*Math.PI/2;r(720+Math.cos(angle)*7,269+Math.sin(angle)*7,2,2,'#ccd0b8');}r(728,269+Math.sin(grinder.workBeat*6)*5,6,2,'#80603e');}
 for(const a of list){if(a.forgeTask==='hammer'){const hit=a.workBeat%1.2;if(hit>.66&&hit<.94){const u=(hit-.66)/.28;for(let n=0;n<5;n++)r(677+(n-2)*u*11,219-Math.sin(u*Math.PI)*(3+n),1,1,n%2?'#ffd899':'#e99a46');}}
 if(a.forgeTask==='grind'){const u=(a.workBeat*4)%1;for(let n=0;n<3;n++)r(712-u*(5+n*3),260+u*(3+n*2),1,1,'#edbd73');}
 if(a.forgeTask==='quench'){for(let n=0;n<4;n++){const u=(a.workBeat*.65+n/4)%1;ctx.globalAlpha=(1-u)*.5;r(778+n*4+Math.sin(u*5)*2,264-u*19,2+u*3,3+u*3,'#d3d3bd');}ctx.globalAlpha=1;}}
}
function workers(){return F.master?[actor(F.master),...(F.apprentice?[actor(F.apprentice,true)]:[])]:[];}
function drawWorkers(ctx){const list=workers();if(scene)poseScene(list,scene.elapsed);else for(const a of list)idle(a,clock);stationMotion(ctx,list);M.renderForgeActors(ctx,list.sort((a,b)=>a.y-b.y));if(scene)M.renderForgeEffects(ctx,scene.limbs,scene.fx);}
// Keep the shared renderer unchanged for ordinary Ludus figures; only add forge residents.
const renderActors=M.renderLudusActors;M.renderForgeActors=renderActors;M.renderLudusActors=(ctx,list)=>{renderActors(ctx,list);if(ctx.canvas?.id==='ludusCanvas')drawWorkers(ctx);};
function paint(canvas){if(!canvas)return;backdrop??=M.ludus.background();const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.scale(canvas.width/240,canvas.height/153);ctx.translate(-625,-145);ctx.drawImage(backdrop,0,0);drawWorkers(ctx);ctx.fillStyle=clock%1>.5?'#c88945':'#e2ab5c';ctx.fillRect(790,205,7,10);ctx.fillRect(805,210,5,7);ctx.restore();}
const paintLudus=M.paintLudus;M.paintLudus=()=>{paintLudus?.();if(M.ui.getPage()==='forge'){paint($('smithScene'));const c=$('smithApprentice');if(c&&F.apprentice){const ctx=c.getContext('2d');ctx.clearRect(0,0,120,120);const a=actor(F.apprentice,true);ctx.save();ctx.translate(60,108);ctx.scale(1.8,1.8);renderActors(ctx,[{...a,x:0,y:0,a:0}]);ctx.restore();}}};
async function startScene(){if(scene||sceneStarting||!F.apprentice?.phase||S.battle)return;sceneStarting=true;const ready=await W.prepareScene();sceneStarting=false;if(!ready){if(W.error)M.ui.notify(W.error);return;}const id=F.apprentice.id;scene={id,elapsed:0,limbs:[],fx:[],struck:false,finishing:false};const overlay=document.createElement('div');overlay.id='smithCeremony';overlay.className='smith-ceremony';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Abschluss der Lehrlingszeit');overlay.innerHTML='<div><h2>Die Abschlussprüfung</h2><canvas id="smithCeremonyCanvas" width="660" height="420" aria-label="Schmied und Lehrling"></canvas><p id="smithSpeech" aria-live="polite"></p><p id="smithSceneStatus"></p><button class="btn" data-action="smith:retry" hidden>Speichern erneut versuchen</button></div>';document.body.appendChild(overlay);}
function poseScene(list,t){const [a,b]=list;if(!a||!b)return;for(const p of list){p.state='idle';p.moveSpeed=0;p.wind=0;p.swing=0;p.wipeTimer=0;p.forgePose='';p.forgeTask='';p.phase=t*4;}a.x=653;a.y=250;a.a=0;b.x=778;b.y=270;b.a=Math.PI;b.g.enemyGear.secondary=null;a.g.enemyGear.secondary=t<4?a.hammer:t<4.5?null:t<11?a.sword:a.hammer;
 if(t<2)a.forgePose='inspect';else if(t<4)a.forgePose='shake';
 if(t>=3&&t<8){b.stagger=.2;b.facePain=.6;}else b.stagger=0;
 if(t>=6&&t<7){a.x=653+(t-6)*78;a.state='move';a.moveSpeed=40;}
 if(t>=7&&t<10)a.x=731;
 if(t>=7&&t<7.7){a.technique='overhead';a.windMax=.7;a.wind=7.7-t;}
 if(t>=7.7&&t<8.2){a.swingKind='slash';a.swingMax=.5;a.swing=8.2-t;}
 if(t>=8&&!scene.struck){scene.struck=true;b.g.body.head.missing=true;b.g.dead=true;b.down=true;b.fallSide=-1;scene.limbs.push({x:b.x+4,y:b.y,z:55,angle:0,part:'head',skin:b.g.appearance.skin,hair:b.g.appearance.hair,g:b.g});for(let n=0;n<16;n++)scene.fx.push({x:b.x,y:b.y,z:42,vx:20+Math.random()*25,vy:Math.random()*12-6,vz:20+Math.random()*20,life:.6+Math.random()*.5,size:2,color:n%3?'#aa3c36':'#87352e'});M.sound?.('sever');}
 if(t>=10&&t<12){a.x=731-(t-10)*39;a.a=Math.PI;a.moveSpeed=40;a.state='move';}
 if(t>=12){a.a=0;a.g.enemyGear.secondary=a.hammer;const k=t%1.2;a.technique='overhead';a.windMax=.7;a.wind=k<.7?.7-k:0;a.swingKind='overhead';a.swingMax=.5;a.swing=k>=.7?1.2-k:0;}
}
async function complete(){if(!scene||scene.finishing)return;scene.finishing=true;const id=scene.id;if(await W.finishScene(id)){figures.delete(id);scene=null;$('smithCeremony')?.remove();M.ui.render();}else{scene.finishing=false;const status=$('smithSceneStatus');if(status)status.textContent=W.error;const retry=$('smithCeremony')?.querySelector('button');if(retry)retry.hidden=false;}}
const click=M.schoolClick;M.schoolClick=action=>{if(action==='smith:retry'){complete();return true;}return click(action);};
const tick=M.ludusTick;M.ludusTick=dt=>{if(document.hidden)return;clock+=Math.min(dt,.1);paintClock+=dt;tick?.(dt);if(paintClock<1/30)return;const step=Math.min(paintClock,.1);paintClock=0;if(scene){if(scene.elapsed<13)scene.elapsed+=step;for(const p of scene.limbs){if(p.z>0){p.x+=step*12;p.y+=step*14;}p.z=Math.max(0,55-(scene.elapsed-8)*45);p.angle+=p.z?step*5:0;}for(const p of scene.fx){p.x+=p.vx*step;p.y+=p.vy*step;p.vz-=180*step;p.z=Math.max(0,p.z+p.vz*step);p.life-=step;}scene.fx=scene.fx.filter(p=>p.life>0);paint($('smithCeremonyCanvas'));const speech=$('smithSpeech'),line=scene.elapsed>=4.5&&scene.elapsed<10?F.apprentice?.line||'':'';if(speech&&speech.textContent!==line)speech.textContent=line;if(scene.elapsed>=13&&!W.error)complete();}else if(F.apprentice?.phase&&!W.error&&!S.battle&&!M.intro?.active?.())startScene();if(M.ui.getPage()==='forge')paint($('smithScene'));};
M.forgeVisuals={actor,paint,workers,startScene,get scene(){return scene;}};
M.ui.render();
})();

