'use strict';
(()=>{const M=window.MG,S=M.s,{clamp,gaussian,rng,pick}=M;
const femaleNames=['Livia','Aelia','Flavia','Cassia','Valeria','Daria','Iulia','Aurelia','Lucilla','Sabina','Thalia','Claudia','Selene','Mara','Neria','Amina','Iris','Dido','Lysandra','Tertia'];
const originLooks={Rom:[0,1,2,3,7],Gallien:[0,1,2,7],Germanien:[0,1,7],Thrakien:[0,1,2,3],Hispanien:[0,1,2,3,7],Numidien:[2,3,4,5],Griechenland:[0,1,2,3],Britannien:[0,1,2,7],Ägypten:[1,2,3,4,5],Syrien:[0,1,2,3,4],Judäa:[1,2,3,4],Kappadokien:[0,1,2,3],Dakien:[0,1,2,7],Illyrien:[0,1,2,3],Lusitanien:[0,1,2,3,7],Mauretanien:[2,3,4,5],Nubien:[3,4,5,6],Armenien:[0,1,2,3],Parthien:[1,2,3,4],Sizilien:[0,1,2,3,7]};
S.household??=[];S.candidates??=[];S.children??=[];S.lineage??={};S.householdMarketDay??=S.day;
function snapshot(g){return {stats:M.copy(g.stats),moves:M.copy(g.moves),mastery:M.copy(g.mastery),caps:M.copy(g.caps),body:Object.fromEntries(M.parts.map(([id])=>[id,{strength:g.body[id].strength,agility:g.body[id].agility}])),height:g.height,weight:g.weight,arm:g.arm,leg:g.leg,fat:g.fat,muscle:g.muscle,potential:g.potential,appearance:M.copy(g.appearance)}}
function ensureFamily(g){M.ensureCareer(g);g.genes??=snapshot(g);for(const k of Object.keys(M.moveNames)){g.genes.moves[k]??=g.moves[k];g.genes.caps.moves[k]??=g.caps.moves[k];}g.preference??=pick(M.origins);g.preferenceKnown??=false;g.familyWish??=rng()<.8;return g}
function register(g){S.lineage[g.id]??={id:g.id,name:g.name,origin:g.origin,parents:M.copy(g.parents||null)};S.lineage[g.id].name=g.name;return S.lineage[g.id]}
function originAppearance(g){const skins=originLooks[g.origin]||[0,1,2,3,4,5,6,7],pal=M.skinPalette[pick(skins)];g.appearance.skin=pal[0];g.appearance.shade=pal[1];return g}
const make=M.makeGladiator;M.makeGladiator=(q=0,enemy=false)=>{const g=make(q,enemy);originAppearance(g);ensureFamily(g);g.genes=snapshot(g);return g};
function makeWoman(){const g=M.makeGladiator(0);g.sex='female';g.name=pick(femaleNames);g.age=Math.round(clamp(gaussian(26,5),18,39));g.height=Math.round(clamp(gaussian(166,7),149,190));g.muscle=Math.round(clamp(gaussian(32,5),22,48));g.weight=Math.round(clamp(gaussian(64,9),46,97));g.build=g.weight>78?'Kräftig':g.height<158?'Kompakt':'Schlank';g.arm=Math.round(g.height*.43);g.leg=Math.round(g.height*.49);g.appearance.beard=0;g.appearance.style=pick([1,2,3,4]);g.appearance.silhouette=clamp(gaussian(1,.16),.72,1.35);g.appearance.cloth=pick(['#677dab','#ab785a','#926785','#6f916d','#bf9b66']);g.recovery=clamp(Math.round(gaussian(52,15)),1,100);g.fertility=clamp(Math.round(gaussian(52,15)),1,100);g.genes=snapshot(g);g.created=S.day;return g}
function refreshHousehold(){S.candidates=Array.from({length:4},makeWoman);S.householdMarketDay=S.day}
function welcome(id){if(S.battle)return 'Während des Kampfes nicht möglich.';const w=S.candidates.find(w=>w.id===id);if(!w)return 'Person nicht mehr verfügbar.';if(S.household.length>=S.roster.length)return 'Höchstens ein Haushaltsmitglied pro aktivem Gladiator.';if(S.household.length>=M.capacity())return 'Unterkunft ausbauen, um weitere Haushaltsmitglieder aufzunehmen.';S.household.push(w);S.candidates=S.candidates.filter(x=>x!==w);register(w);M.log(w.name+' zieht als freies Haushaltsmitglied in die Schule.');M.persist();return w.name+' willkommen. Beziehungen entstehen nur im gegenseitigen Einvernehmen.'}
function partner(g){return S.household.find(w=>w.partnerId===g.id)||null}
function propose(gid,wid){if(S.battle)return 'Während des Kampfes nicht möglich.';const g=[...S.roster,...S.trainers].find(g=>g.id===gid),w=S.household.find(w=>w.id===wid);if(!g||!w||g.age<18||w.age<18||g.dead)return 'Zwei freie Erwachsene erforderlich.';ensureFamily(g);if(partner(g)||w.partnerId)return 'Mindestens eine Person lebt bereits in einer Partnerschaft.';g.proposals??={};const last=g.proposals[w.id];if(last&&S.day-last.day<30)return 'Beide wünschen vorerst Abstand. Frühestens an Tag '+(last.day+30)+' erneut fragen.';const accepted=rng()<.75;g.proposals[w.id]={day:S.day,accepted};if(!accepted){M.persist();return 'Die beiden möchten keine Beziehung eingehen. Ihre Entscheidung bleibt bestehen.';}w.partnerId=g.id;w.bondDay=S.day;w.nextFamilyDay=S.day+Math.round(clamp(gaussian(42-w.fertility*.2,5),14,60));register(g);register(w);M.log(g.name+' und '+w.name+' entscheiden sich für eine Partnerschaft.');M.persist();return 'Beide stimmen zu. '+w.name+' und '+g.name+' sind ein Paar.'}
function recoveryBonus(g){const w=partner(g);return w?Math.min(12,w.recovery/10+(w.origin===g.preference?2:0)):0}
function disclose(g){ensureFamily(g);g.preferenceKnown=true;M.persist();return {title:'Partnerschaft',text:'Ich fühle mich Menschen aus '+g.preference+' besonders verbunden.'+(g.familyWish?' Eine eigene Familie kann ich mir vorstellen.':' Zurzeit wünsche ich mir keine Kinder.')}}
function inherit(a,b){const base=(a+b)/2,cat=Math.floor((clamp(base,1,100)-1)/10),low=Math.max(1,(cat-2)*10+1),high=Math.min(100,(cat+3)*10);return clamp(Math.round(gaussian(base,6)),low,high)}
function childOf(father,mother){ensureFamily(father);ensureFamily(mother);const a=father.genes,b=mother.genes,g=make(0),sex=rng()<.5?'male':'female';g.name=sex==='male'?g.name:pick(femaleNames);g.sex=sex;g.origin=pick([father.origin,mother.origin]);g.parents={father:{id:father.id,name:father.name},mother:{id:mother.id,name:mother.name}};for(const k of Object.keys(M.stats)){g.stats[k]=inherit(a.stats[k],b.stats[k]);g.caps.stats[k]=Math.max(g.stats[k],inherit(a.caps.stats[k],b.caps.stats[k]));}for(const k of Object.keys(M.moveNames)){g.moves[k]=inherit(a.moves[k],b.moves[k]);g.caps.moves[k]=Math.max(g.moves[k],inherit(a.caps.moves[k],b.caps.moves[k]));}for(const w of M.weaponDefs){g.mastery[w.id]=inherit(a.mastery[w.id],b.mastery[w.id]);g.caps.weapons[w.id]=Math.max(g.mastery[w.id],inherit(a.caps.weapons[w.id],b.caps.weapons[w.id]));}for(const [id]of M.parts)for(const k of ['strength','agility']){g.body[id][k]=inherit(a.body[id][k],b.body[id][k]);g.caps.body[id][k]=Math.max(g.body[id][k],inherit(a.caps.body[id][k],b.caps.body[id][k]));}g.potential=inherit(a.potential,b.potential);for(const k of ['height','weight','arm','leg','fat','muscle'])g[k]=Math.round((a[k]+b[k])/2*clamp(gaussian(1,.025),.93,1.07));g.appearance=M.copy(pick([a.appearance,b.appearance]));g.appearance.hair=pick([a.appearance.hair,b.appearance.hair]);if(sex==='female')g.appearance.beard=0;g.genes=snapshot(g);g.age=18;g.created=S.day;g.birthday=S.day;g.history=[{day:S.day,text:'Kind von '+father.name+' und '+mother.name+'.'}];g.preference=pick(M.origins);g.preferenceKnown=false;g.familyWish=rng()<.8;const c={id:g.id,name:g.name,sex,born:S.day,parents:M.copy(g.parents),template:g,decision:null};S.children.push(c);register(g);M.log(g.name+' wird als Kind von '+father.name+' und '+mother.name+' als erwachsenes Nachwuchstalent verfügbar.');return c}
function childAge(c){return Math.max(18,18+Math.floor((S.day-c.born)/365))}
function educate(id,yes){if(S.battle)return 'Während des Kampfes nicht möglich.';const c=S.children.find(c=>c.id===id);if(!c||c.decision)return 'Die Entscheidung ist bereits getroffen.';if(childAge(c)<18)return 'Ausbildung erst ab 18 Jahren möglich.';if(!yes){c.decision='civilian';M.persist();return c.name+' entscheidet sich für ein Leben außerhalb der Arena.';}if(c.sex!=='male')return 'Dieser Ausbildungsweg ist nur für erwachsene Söhne vorgesehen.';if(S.gold<1000)return 'Nicht genug Gold.';if(S.roster.length>=M.capacity())return 'Unterkunft ist voll.';const g=M.copy(c.template);g.age=childAge(c);g.created=S.day;g.birthday=c.born;g.title='Sohn von '+c.parents.father.name;S.gold-=1000;S.stats.spent+=1000;S.roster.push(g);c.decision='gladiator';g.history.unshift({day:S.day,text:'Mit '+g.age+' Jahren freiwillig in die Gladiatorenschule eingetreten.'});register(g);M.persist();return g.name+' – '+g.title+' – tritt deiner Schule bei.'}
function householdDay(){for(const w of S.household){if((S.day-w.birthday)%365===0)w.age++;const g=[...S.roster,...S.trainers].find(g=>g.id===w.partnerId&&!g.dead);if(!g){if(w.partnerId){w.formerPartner=w.partnerId;w.partnerId=null;}continue;}ensureFamily(g);const bonus=recoveryBonus(g);g.fatigue=Math.max(0,g.fatigue-bonus);g.blood=Math.min(100,g.blood+bonus*.15);if(g.age<18||w.age<18||w.age>44||g.age>65||!g.familyWish||!w.familyWish)continue;if(S.day>=(w.nextFamilyDay||S.day+365)){w.nextFamilyDay=S.day+Math.round(clamp(gaussian(65-w.fertility*.35,8),20,85));if(rng()<.42+w.fertility*.004)childOf(g,w);}}if(S.day-S.householdMarketDay>=30)refreshHousehold();}
const rest=M.advanceDay;M.advanceDay=(days=1)=>{if(S.battle)return 'Während eines Kampfes nicht möglich.';days=clamp(Math.floor(days),1,365);const count=S.children.length;rest(days);M.persist();return days+' Tage vergangen. Erholung und Familienchronik aktualisiert.'+(S.children.length>count?' '+(S.children.length-count)+' Kind(er) geboren.':'')};
const wishes=M.wishes;M.wishes=g=>[...wishes(g),disclose(g)];
for(const g of [...S.roster,...S.market,...S.trainers,...(S.battle?.actors.map(a=>a.g)||[])]){ensureFamily(g);if(!g.enemy)register(g)}
if(!S.familyMigration){for(const g of S.market){originAppearance(g);g.genes=snapshot(g);}S.familyMigration=true;}
for(const c of S.children){ensureFamily(c.template);}
if(!S.householdInitialized){refreshHousehold();S.householdInitialized=true;}
Object.assign(M,{ensureFamily,partner,propose,recoveryBonus,disclose,inherit,childOf,childAge,educate,welcome,householdDay,makeWoman,register});M.persist();
})();
