'use strict';
(()=>{const M=window.MG,S=M.s;S.soldArrears??=0;const nouns=['Kämpfer','Jäger','Wächter','Bezwinger','Streiter','Eroberer','Champion','Titan','Herrscher','Imperator'],adjectives=['standhafte','eiserne','furchtlose','unbeugsame','siegreiche','unerbittliche','ruhmreiche','legendäre','unsterbliche','ewige'];let previous=0;const killTitles=Array.from({length:100},(_,i)=>{const kills=i===99?100000:Math.max(previous+1,Math.round(Math.pow(100000,i/99)));previous=kills;return {kills,name:i===99?'die Legende der Hunderttausend':'der '+adjectives[Math.floor(i/10)]+' '+nouns[i%10]};});
function honor(g){let low=0,high=99,found=-1;while(low<=high){const mid=(low+high)>>1;if(g.kills>=killTitles[mid].kills){found=mid;low=mid+1;}else high=mid-1;}return {index:found,title:killTitles[found]?.name||'',next:killTitles[found+1]||null};}
function displayName(g){const h=honor(g);return g.name+(h.title?' · '+h.title:'');}
function dailySold(){return S.roster.filter(g=>!g.dead&&!g.retired).length*2;}
function chargeSold(){const due=dailySold(),paid=Math.min(S.gold,due);S.gold-=paid;S.stats.spent+=paid;S.soldArrears+=due-paid;}
function salePrice(g){return Math.max(1,Math.floor(M.marketValue(g)*.45));}
function sellGladiator(id){if(S.battle)return 'Während eines Kampfes nicht möglich.';const g=S.roster.find(g=>g.id===id);if(!g)return 'Gladiator nicht gefunden.';const price=salePrice(g);M.register(g);S.lineage[g.id].departure={day:S.day,type:'Verkauft',wins:g.wins,kills:g.kills};for(const w of S.household)if(w.partnerId===id){w.formerPartner=g.name;delete w.partnerId;delete w.nextFamilyDay;}S.roster=S.roster.filter(x=>x!==g);S.teams=S.teams.map(t=>t.filter(x=>x!==id));S.gold+=price;S.stats.earned+=price;M.log(g.name+' wurde für '+price+' Gold verkauft. Ausrüstung bleibt im Lager.');M.persist();return price+' Gold erhalten. Die Ausrüstung bleibt im Lager.';}
function dismissWoman(id){if(S.battle)return 'Während eines Kampfes nicht möglich.';const w=S.household.find(w=>w.id===id);if(!w)return 'Person nicht gefunden.';M.register(w);S.lineage[w.id].departure={day:S.day,type:'Haushalt verlassen'};S.household=S.household.filter(x=>x!==w);M.log(w.name+' verlässt den Haushalt. Ihre Familienchronik bleibt erhalten.');M.persist();return 'Haushaltsmitglied verabschiedet.';}
// Free arenas share the standard league opponent generator, including mastery,
// equipment, injuries and champion chance. Entry stakes remain freely selectable.
const openArenas=Array.from({length:50},(_,i)=>{const league=[1,4,11,26,40,47,50].findIndex(end=>i<end),L=M.leagues[league],fee=(i+1)*50;return {id:i,name:i===49?'Arena der Vollendeten':'Freie Arena '+(i+1),fee,reward:L.reward,league};});
function arenaPrize(b,won){const L=M.leagues[b.league],champion=b.champion?1.3:1;if(!won)return b.openArena?0:Math.round(L.reward*.18);const sponsor=S.sponsor?1+S.sponsor.bonus:1,fame=1+Math.min(.25,b.actors.filter(a=>a.team===0).reduce((n,a)=>n+a.g.fame,0)/10000);return L.reward*champion*sponsor*fame;}
Object.assign(M,{killTitles,honor,displayName,dailySold,chargeSold,salePrice,sellGladiator,dismissWoman,openArenas,arenaPrize});})();
