'use strict';
(()=>{const INDEX='mini-gladiator-profiles-v1',ACTIVE='mini-gladiator-active-profile',LEGACY='mini-gladiator-manager-v2';let list=[],active=null,error='';try{list=JSON.parse(localStorage.getItem(INDEX)||'[]');if(!Array.isArray(list))throw Error('Ungültige Profilliste');active=localStorage.getItem(ACTIVE);if(!list.length){const old=localStorage.getItem(LEGACY),id='legacy';if(old){const saved=JSON.parse(old);if(saved.version!==2)throw Error('Alter Spielstand nicht lesbar');localStorage.setItem('mini-gladiator-profile-'+id,old);}list=[{id,name:'Ludus Holz',created:Date.now()}];localStorage.setItem(INDEX,JSON.stringify(list));active=id;localStorage.setItem(ACTIVE,id);}if(!list.some(p=>p.id===active)){active=list[0].id;localStorage.setItem(ACTIVE,active);}}catch(e){error='Spielerprofile konnten nicht geöffnet werden. Der bisherige Spielstand bleibt erhalten.';}
const key=active?'mini-gladiator-profile-'+active:LEGACY;
function save(){if(!window.MG?.persist())return 'Speichern fehlgeschlagen. Bitte freien Browserspeicher prüfen.';return '';}
function activate(id){if(error)return error;if(!list.some(p=>p.id===id))return 'Profil nicht gefunden.';const err=save();if(err)return err;try{const raw=(window.MGSave?window.MGSave.get('mini-gladiator-profile-'+id):localStorage.getItem('mini-gladiator-profile-'+id));if(raw&&JSON.parse(raw).version!==2)return 'Spielstand nicht lesbar.';localStorage.setItem(ACTIVE,id);}catch{return 'Profil konnte nicht geladen werden.';}if(window.MGSave)window.MGSave.flush().then(()=>location.reload()).catch(e=>{try{localStorage.setItem(ACTIVE,active);}catch{}window.MG?.ui?.notify(e.message);});else location.reload();return '';}
function create(name){name=String(name||'').trim().slice(0,32);if(!name)return 'Bitte einen Spieler- oder Schulnamen eingeben.';if(error)return error;const err=save();if(err)return err;const id=crypto.randomUUID(),next=[...list,{id,name,created:Date.now()}];try{localStorage.setItem(INDEX,JSON.stringify(next));localStorage.setItem(ACTIVE,id);}catch{try{localStorage.setItem(ACTIVE,active);}catch{}return 'Neues Profil konnte nicht gespeichert werden.';}if(window.MGSave)window.MGSave.flush().then(()=>location.reload()).catch(e=>{try{localStorage.setItem(ACTIVE,active);}catch{}window.MG?.ui?.notify(e.message);});else location.reload();return '';}
function rename(name){name=String(name||'').trim().slice(0,32);if(!name)return 'Bitte einen Namen eingeben.';if(error)return error;const previous=window.MG.s.schoolName;window.MG.s.schoolName=name;const err=save();if(err){window.MG.s.schoolName=previous;return err;}return '';}
function readable(id){try{const raw=window.MGSave?window.MGSave.get('mini-gladiator-profile-'+id):localStorage.getItem('mini-gladiator-profile-'+id);return !raw||JSON.parse(raw).version===2;}catch{return false;}}
function wipe(id){const k='mini-gladiator-profile-'+id;if(window.MGSave?.removeProfile){window.MGSave.removeProfile(k);return;}try{for(let i=localStorage.length-1;i>=0;i--){const n=localStorage.key(i);if(n&&(n===k||n.startsWith(k+':')))localStorage.removeItem(n);}}catch{}}
function remove(id){if(error)return error;if(!list.some(p=>p.id===id))return 'Profil nicht gefunden.';const next=list.filter(p=>p.id!==id);if(id!==active){try{localStorage.setItem(INDEX,JSON.stringify(next));}catch{return 'Profil konnte nicht gelöscht werden.';}list=next;wipe(id);return '';}let target=next.find(p=>readable(p.id));if(!target){target={id:crypto.randomUUID(),name:'Ludus Holz',created:Date.now()};next.push(target);}const batch=window.MG?.batchSaving;if(window.MG)window.MG.batchSaving=true;try{localStorage.setItem(INDEX,JSON.stringify(next));localStorage.setItem(ACTIVE,target.id);}catch{try{localStorage.setItem(INDEX,JSON.stringify(list));localStorage.setItem(ACTIVE,active);}catch{}if(window.MG)window.MG.batchSaving=batch;return 'Profil konnte nicht gelöscht werden.';}wipe(id);if(window.MGSave)window.MGSave.flush().catch(()=>{}).then(()=>location.reload());else location.reload();return '';}
function entries(){return list.map(p=>{try{const data=p.id===active?window.MG?.s:JSON.parse((window.MGSave?window.MGSave.get('mini-gladiator-profile-'+p.id):localStorage.getItem('mini-gladiator-profile-'+p.id))||'null');return {...p,name:data?.schoolName||p.name,day:data?.day||1,gold:data?.gold??650,fighters:data?.roster?.length||0,savedAt:data?.savedAt||0,active:p.id===active};}catch{return {...p,invalid:true};}});}
window.GladiatorProfiles={key,active,name:list.find(p=>p.id===active)?.name||'Ludus Holz',entries,create,activate,remove,rename,save,get error(){return error}};
})();
