'use strict';
(()=>{const M=window.MG,S=M.s,C=M.clamp;
S.army??={recruit:{enabled:false,perDay:1,minGold:300,target:150,reserves:0},auto:{classes:false,equipment:false,replacements:false,teams:false},mode:'balanced',rules:{health:75,energy:60,grade:2,bleed:0,fractures:false,internal:false},audit:[],ammo:{arrow:120,bolt:80},dayReport:null};
S.army.auto??={};S.army.ammo??={arrow:120,bolt:80};S.teamPlans??=S.teams.map((ids,i)=>({name:'Team '+(i+1),size:3,leader:null,reserves:[],formation:'Normal',tactics:M.copy(S.tactics),classes:{},loadouts:{}}));
// One active formation per size. Preserve superseded formations as historical data.
function consolidateTeams(){
 const chosen=new Map(),keep=[],active=S.teamPlans[S.teamIndex];S.archivedTeams??=[];
 for(let i=0;i<S.teamPlans.length;i++){const p=S.teamPlans[i],old=chosen.get(p.size);if(old===undefined||p===active||(S.teamPlans[old]!==active&&S.teams[i].filter(Boolean).length>S.teams[old].filter(Boolean).length))chosen.set(p.size,i);}
 for(let i=0;i<S.teamPlans.length;i++){if(chosen.get(S.teamPlans[i].size)===i){keep.push(i);continue;}const p=S.teamPlans[i],members=S.teams[i];S.archivedTeams.push({plan:M.copy(p),members:[...members],day:S.day});const winner=S.teamPlans[chosen.get(p.size)];winner.reserves=[...new Set([...(winner.reserves||[]),...members.filter(Boolean)])];if(p.id&&S.world?.teams?.[p.id]){S.world.teams[p.id].active=false;S.world.teams[p.id].ended=S.day;}}
 S.teams=keep.map(i=>S.teams[i]);S.teamPlans=keep.map(i=>S.teamPlans[i]);S.teamIndex=Math.max(0,S.teamPlans.indexOf(active));
}
consolidateTeams();
const ranged=['bow','crossbow'],melee=M.weaponDefs.filter(w=>!w.ammo).map(w=>w.id),slots=['weapon','secondary','shield',...M.armorDefs.map(d=>d.id)];
M.classSpecs.Fernkämpfer.weapons=ranged;M.classSpecs.Soldat.weapons=melee;
function person(g){g.locks??={};g.reserve??=false;g.available??=true;g.ammoLoad??=M.gear(g,'weapon')?.def==='crossbow'?8:12;g.smithAssigned=false;return g;}
for(const g of S.roster)person(g);S.market=[];S.blindRecruitment=true;
function audit(message){S.army.audit.unshift({day:S.day,message});S.army.audit=S.army.audit.slice(0,120);return message;}
function plan(){return S.teamPlans[S.teamIndex];}
function teamOf(id){return S.teams.map((t,i)=>t.includes(id)?S.teamPlans[i]?.name:null).filter(Boolean).join(', ');}
function bestWeapon(g,range=false,potential=false){const values=potential?g.caps.weapons:g.mastery;return (range?ranged:melee).map(id=>({id,value:values[id]||1})).sort((a,b)=>b.value-a.value)[0];}
function combatValues(g){const projected={...g,stats:{...g.caps.stats},body:Object.fromEntries(Object.entries(g.body).map(([id,p])=>[id,{...p,hp:100-p.chronic}]))};return {current:M.power(g),maximum:Math.max(M.power(g),M.power(projected))};}
M.combatValues=combatValues;
function rating(g,role=g.role,mode='balanced'){const now=M.scoutScore(g,role,false).score,cap=M.scoutScore(g,role,true).score;return mode==='current'?now:mode==='potential'?cap:(now+cap)/2;}
function eligibility(g){person(g);const r=S.army.rules,p=Object.values(g.body),grade=Math.max(...p.map(M.injuryGrade));const causes=[];for(const id of r.blockParts||[]){const p=g.body[id];if(p&&(p.missing||p.fracture||p.internal||p.bleed>0||p.hp<100-p.chronic))causes.push(M.partName(id)+' verletzt');}if(g.dead||g.retired||g.age<18)causes.push('nicht aktiv');if(!g.available)causes.push('manuell geschont');if(g.reserve)causes.push('Reserve');if(M.health(g)<r.health)causes.push('Gesundheit');if(100-g.fatigue<r.energy)causes.push('Erschöpfung');if(grade>r.grade)causes.push('Verletzungsschwere');if(p.reduce((v,x)=>v+x.bleed,0)>r.bleed)causes.push('Blutung');if(!r.fractures&&p.some(x=>x.fracture))causes.push('Knochenbruch');if(!r.internal&&p.some(x=>x.internal))causes.push('innere Verletzung');if(g.body.head.missing||g.body.chest.hp<5)causes.push('kampfunfähig');return {ok:!causes.length,causes,grade,health:M.health(g),energy:100-g.fatigue};}
function ready(g,allowReserve=false){if(!allowReserve)return eligibility(g).ok;const old=g.reserve;g.reserve=false;const ok=eligibility(g).ok;g.reserve=old;return ok;}
function autoClasses(gs=S.roster,mode=S.army.mode){let n=0;for(const g of gs){person(g);if(g.locks.class)continue;g.role=[...M.roles].sort((a,b)=>rating(g,b,mode)-rating(g,a,mode))[0];n++;}audit(n+' Klassen nach '+mode+' zugewiesen; Klassensperren beachtet.');M.persist();return n;}
function recruitMany(amount=1,{automatic=false}={}){if(S.battle)return [];let n=Math.max(0,Math.min(Math.floor(Number(amount)||0),Math.floor(S.gold/100)));const recruits=[];for(let i=0;i<n;i++){const g=person(M.makeGladiator(0));g.price=100;g.recruitStandard=true;g.history.unshift({day:S.day,text:'Blind für 100 Gold rekrutiert.'});S.roster.push(g);recruits.push(g);M.register(g);}S.gold-=n*100;S.stats.spent+=n*100;if(S.army.auto.classes)autoClasses(recruits);if(S.army.auto.equipment)autoEquip(recruits,S.army.mode);if(n)audit(n+' unbekannte Rekruten aufgenommen · '+n*100+' Gold.');M.persist();return recruits;}
M.buyRecruit=()=>{const a=recruitMany(1);return a.length?a[0].name+' für 100 Gold rekrutiert.':'Nicht genug Gold.';};M.refreshMarket=()=>{S.market=[];return true;};M.capacity=()=>Number.MAX_SAFE_INTEGER;M.storageCapacity=()=>Math.max(20000,S.inventory.length+1);
function getSlot(g,k){return ['weapon','secondary','shield'].includes(k)?g.equipment[k]:g.equipment.armor[k];}function putSlot(g,k,id){if(k==='weapon'&&id&&!M.allowedRanged(g,M.inventoryItem(id)))return;if(['weapon','secondary','shield'].includes(k))g.equipment[k]=id||null;else if(id)g.equipment.armor[k]=id;else delete g.equipment.armor[k];if(id)M.world?.ownership(M.inventoryItem(id),g);}
function equipmentNeeds(gs=M.selectedTeam()){
 const held=new Set(S.roster.flatMap(g=>slots.map(k=>getSlot(g,k))).filter(Boolean)),free=S.inventory.filter(i=>!held.has(i.id)&&i.durability>0),claimed=new Set(),rows=[];
 const add=(g,slot,kind,def,label,required=false)=>{const candidates=free.filter(i=>!claimed.has(i.id)&&i.kind===kind&&(kind==='weapon'?(slot==='weapon'?ranged.includes(i.def):!M.definition(i).ammo):i.def===def||(kind==='shield'))).sort((a,b)=>{if(kind==='weapon')return ((b.def===def?200:0)+(g.mastery[b.def]||0))-((a.def===def?200:0)+(g.mastery[a.def]||0));return ((b.material===(g.role==='Soldat'?'metal':'leather')?100:0)+(M.itemStats(b).protection||0))-((a.material===(g.role==='Soldat'?'metal':'leather')?100:0)+(M.itemStats(a).protection||0));});const item=candidates[0];if(item)claimed.add(item.id);rows.push({id:g.id,name:g.name,slot,kind,def,label,required,locked:!!g.locks?.[slot],available:item?M.itemName(item):null,itemId:item?.id,status:item?'assign':'buy'});};
 for(const g of gs){const primary=M.gear(g,'weapon'),secondary=M.gear(g,'secondary'),close=secondary&&!M.definition(secondary).ammo?secondary:primary&&!M.definition(primary).ammo?primary:null;
 if(g.role==='Fernkämpfer'&&(!primary||!ranged.includes(primary.def))){const id=bestWeapon(g,true).id;add(g,'weapon','weapon',id,M.weaponDefs.find(w=>w.id===id).name,true);}
 if(!close){const id=bestWeapon(g).id;add(g,'secondary','weapon',id,(g.role==='Fernkämpfer'?'Ersatzwaffe: ':'Nahkampfwaffe: ')+M.weaponDefs.find(w=>w.id===id).name,true);}
 for(const d of M.armorDefs){const item=M.inventoryItem(getSlot(g,d.id));if(!item)add(g,d.id,'armor',d.id,d.name+' · '+(g.role==='Soldat'?'Metall empfohlen':'Leder empfohlen'),false);}
 if(g.role==='Soldat'&&close&&!M.definition(close).twoHand&&!M.gear(g,'shield'))add(g,'shield','shield','roundshield','Schild für die Frontlinie',false);
 for(const slot of slots){const item=M.inventoryItem(getSlot(g,slot));if(item&&item.durability>0&&item.durability/item.maxDurability<.25)rows.push({id:g.id,name:g.name,slot,kind:item.kind,def:item.def,label:M.itemName(item)+' · '+Math.round(item.durability/item.maxDurability*100)+' % Haltbarkeit',status:'repair',required:false,locked:!!g.locks?.[slot]});else if(item&&item.durability<=0)rows.push({id:g.id,name:g.name,slot,kind:item.kind,def:item.def,label:M.itemName(item)+' · beschädigt',status:'repair',required:item.kind==='weapon'});}
 }

 return {rows,missing:rows.filter(x=>x.required).length,buy:rows.filter(x=>x.status==='buy').length,assign:rows.filter(x=>x.status==='assign').length,repair:rows.filter(x=>x.status==='repair').length};
}
function equipmentValue(g,i,slot,mode){const v=M.itemStats(i),skill=(g.mastery[i.def]||1)*.65+(g.caps.weapons[i.def]||1)*.35,health=M.health(g)/100;
 if(i.kind==='weapon'){if(slot==='weapon')return M.allowedRanged(g,i)?(i.def==='net'?Math.max(1,v.netDuration||1)*10:v.damage/Math.max(.2,v.delay))*(1+skill/80)*(.7+g.stats.precision/100):-1;if(v.ammo)return -1;const preference=M.classSpecs[g.role].weapons.includes(i.def)?1.15:1;return v.damage/v.delay*(.6+skill/80)*preference*(v.twoHand&&g.locks.shield&&getSlot(g,'shield')?.25:1)*(v.twoHand&&g.stats.strength<30?.7:1)*(v.twoHand&&M.limb(g,['lua','lfa','lh','rua','rfa','rh'])<.5?.2:1);}
 if(i.kind==='shield')return (v.area*100+v.protection*.3)*(1+g.stats.block/100)/(1+v.weight/(g.role==='Soldat'?22:7));
 const mobility=g.role==='Soldat'?24:6;return v.protection*health/(1+v.weight/(mobility+g.stats.strength*.1))*(g.role!=='Soldat'&&i.material==='leather'?1.4:1);
}
function autoEquip(gs=S.roster,priority='balanced'){if(S.battle)return 'Während des Kampfes nicht möglich.';const target=gs.filter(g=>!g.dead&&!g.retired).map(person),ids=new Set(target.map(g=>g.id)),held=new Set();for(const g of S.roster)for(const k of slots)if(getSlot(g,k)&&(!ids.has(g.id)||g.locks[k]))held.add(getSlot(g,k));
 const rank=g=>priority==='combat'?M.power(g):priority==='hero'?(S.teamPlans.some(t=>t.leader===g.id)?1000:0)+rating(g,g.role,'current'):priority==='elite'?(S.teams[0]?.includes(g.id)?1000:0)+rating(g):priority==='talents'?rating(g,g.role,'potential')-rating(g,g.role,'current'):rating(g,g.role,priority);target.sort((a,b)=>rank(b)-rank(a));
 for(const g of target)for(const k of slots)if(!g.locks[k])putSlot(g,k,null);
 const groups={};for(const i of S.inventory){if(held.has(i.id)||i.durability<=0)continue;const k=i.kind==='weapon'?(M.definition(i).ammo?'weapon':'secondary'):i.kind==='shield'?'shield':i.def;(groups[k]??=[]).push(i);}
 let assigned=0;const notes=[];for(const g of target){for(const k of slots){if(g.locks[k])continue;if(k==='shield'&&(M.itemStats(M.gear(g,'secondary'))?.twoHand||g.role==='Fernkämpfer'))continue;let best=null,score=0;for(const i of groups[k]||[]){if(held.has(i.id))continue;const value=equipmentValue(g,i,k,priority);if(value>score){score=value;best=i;}}if(best){putSlot(g,k,best.id);held.add(best.id);assigned++;}}
 if(!g.locks.ammo){const def=M.gear(g,'weapon')?.def;g.ammoLoad=def==='crossbow'?8:def==='bow'?12:0;}notes.push(g.name+': '+M.itemName(M.gear(g,g.role==='Fernkämpfer'?'weapon':'secondary')));}
 M.world?.syncOwners();audit('Ausrüstung: '+assigned+' Teile verteilt ('+priority+'). '+notes.slice(0,8).join(' · ')+(notes.length>8?' …':''));M.persist();return assigned+' Ausrüstungsteile zugewiesen. Sperren und außerhalb der Auswahl angelegte Gegenstände bleiben geschützt.';}
function savePlan(){const p=plan();if(!p)return;for(const g of M.selectedTeam()){p.classes[g.id]=g.role;p.loadouts[g.id]=M.copy(g.equipment);}p.tactics=M.copy(S.tactics);p.formation=S.tactics.formation;M.persist();}
function activateTeam(index){savePlan();if(!S.teamPlans[index])return;S.teamIndex=index;S.tactics=M.copy(plan().tactics);M.persist();}
function newTeam(name='Neue Gruppe',size=3){if(![1,2,3,5,10,15,20,30,50,75,100].includes(+size))return;const existing=S.teamPlans.findIndex(p=>p.size===+size);if(existing>=0){activateTeam(existing);return;}S.teams.push([]);S.teamPlans.push({name:name.slice(0,40),size:+size,leader:null,reserves:[],formation:'Normal',tactics:M.copy(S.tactics),classes:{},loadouts:{}});activateTeam(S.teams.length-1);}
function deleteTeam(index=S.teamIndex){if(S.battle)return 'Während eines Kampfes nicht möglich.';if(!S.teamPlans[index])return 'Team nicht gefunden.';const name=S.teamPlans[index].name;S.teams.splice(index,1);S.teamPlans.splice(index,1);if(!S.teams.length){S.teams=[[]];S.teamPlans=[{name:'Neues Team',size:3,leader:null,reserves:[],formation:'Normal',tactics:M.copy(S.tactics),classes:{},loadouts:{}}];}if(S.teamIndex>index)S.teamIndex--;S.teamIndex=Math.min(S.teamIndex,S.teams.length-1);S.tactics=M.copy(plan().tactics);M.persist();return name+' gelöscht. Kämpfer und Ausrüstung bleiben erhalten.';}
function setMember(position,id){const t=S.teams[S.teamIndex],g=S.roster.find(g=>g.id===id);if(position<0||position>=plan().size)return;const old=t.indexOf(id);if(old>=0)t[old]=t[position]||'';t[position]=g?id:'';while(t.length&& !t[t.length-1])t.pop();savePlan();}
function autoTeam(goal='balanced'){const p=plan(),current=S.teams[S.teamIndex],locked=current.filter(id=>S.roster.find(g=>g.id===id)?.locks.team||(p.leaderLocked&&p.leader===id)),used=new Set(locked),members=[...locked];let candidates=S.roster.filter(g=>ready(g)&&!used.has(g.id)&&(!g.locks?.team||current.includes(g.id)));
 const roleOrder=goal==='ranged'?['Fernkämpfer','Fernkämpfer','Soldat']:goal==='defensive'?['Soldat','Soldat','Fernkämpfer']:goal==='offensive'?['Assassine','Soldat','Fernkämpfer']:goal==='melee'?['Soldat','Assassine']:['Soldat','Assassine','Fernkämpfer'];
 while(members.length<p.size&&candidates.length){const role=roleOrder[members.length%roleOrder.length],mode=goal==='potential'||goal==='talents'?'potential':goal==='current'?'current':'balanced';candidates.sort((a,b)=>(rating(b,b.role,mode)+(b.role===role?18:0))-(rating(a,a.role,mode)+(a.role===role?18:0)));members.push(candidates.shift().id);}
 // Preserve the positions of explicitly locked members.
 const result=Array(p.size).fill('');current.forEach((id,i)=>{if(i<p.size&&locked.includes(id))result[i]=id;});let additions=members.filter(id=>!locked.includes(id));for(let i=0;i<p.size;i++)if(!result[i])result[i]=additions.shift()||'';S.teams[S.teamIndex]=result;savePlan();return audit(result.filter(Boolean).length+'/'+p.size+' Plätze besetzt · Ziel '+goal+'. Gesperrte Teamplätze beibehalten.');}
function replaceInjured(){const p=plan(),t=S.teams[S.teamIndex],used=new Set(t),pool=S.roster.filter(g=>!used.has(g.id)&&ready(g,true)&&!g.locks?.team);let n=0;for(let i=0;i<p.size;i++){const old=S.roster.find(g=>g.id===t[i]);if(old&&(ready(old,true)||old.locks?.team||(p.leaderLocked&&p.leader===old.id)))continue;pool.sort((a,b)=>((p.reserves.includes(b.id)?40:0)+(b.role===old?.role?25:0)+rating(b))-((p.reserves.includes(a.id)?40:0)+(a.role===old?.role?25:0)+rating(a)));const replacement=pool.shift();if(replacement){t[i]=replacement.id;n++;}}
 savePlan();return audit(n+' verletzte oder leere Teamplätze ersetzt.');}
function prepareTeam(){replaceInjured();const msg=autoEquip(M.selectedTeam(),'current');savePlan();const problem=M.validateTeam('challenge');return audit(problem?'Team noch nicht bereit: '+problem:'Team einsatzbereit. '+msg);}
function ammoRequired(){return {arrow:0,bolt:0};}
function buyAmmo(){return 'Pfeile und Bolzen werden vor jedem Kampf kostenlos bereitgestellt.';}
const originalValidate=M.validateTeam;M.validateTeam=(type='league',tid)=>{const gs=M.selectedTeam(),size=plan().size;if(gs.length!==size||new Set(gs.map(g=>g.id)).size!==size)return 'Wähle genau '+size+' unterschiedliche Kämpfer.';for(const g of gs){const e=eligibility(g);const causes=e.causes.filter(x=>x!=='Reserve');if(causes.length)return g.name+': '+causes.join(', ');if(g.role==='Fernkämpfer'&&(!ranged.includes(M.gear(g,'weapon')?.def)||!M.gear(g,'secondary')))return g.name+' braucht Bogen/Armbrust und eine Nahkampf-Ersatzwaffe.';}
 if(type==='tournament'&&size!==3)return 'Bestehende Turniere bleiben 3 gegen 3. Wähle ein 3er-Team.';if(type==='tournament')return originalValidate(type,tid);return '';};
function heroValue(g){return C(g.stats.experience*.35+g.stats.will*.25+g.stats.morale*.2+Math.min(100,g.wins)*.1+Math.min(100,Math.log2(1+g.kills)*10)*.1,0,100);}
function challengeTier(rank){return ['Einstieg','Leicht','Solide','Fordernd','Veteranen','Schwer','Elite','Meister','Champion','Legendär'][Math.floor((rank-1)/5)];}
function generateChallenges(){S.army.challenges=[];if(S.world)return;for(const size of [1,3,10,15])for(let rank=1;rank<=50;rank++){const league=Math.min(6,Math.floor((rank-1)/7)),progress=((rank-1)%7)/7,next=M.leagues[Math.min(6,league+1)],base=M.leagues[league],factor=league===6?1+(rank-43)*.14:1;S.army.challenges.push({id:M.uid(),day:S.day,size,rank,name:M.pick(['Aschenwölfe','Eisenbanner','Skorpione','Adlerwache'])+' · '+challengeTier(rank),league,style:M.pick(['Soldaten','Assassinen','Fernkämpfer','Ausgeglichen']),reward:Math.round((base.reward+(next.reward-base.reward)*progress)*size/3*factor),fee:Math.round((base.fee+(next.fee-base.fee)*progress)*size/3*factor),used:false});}S.army.challengeVersion=2;}
M.applyChallengeDifficulty=(g,c)=>{if(!c?.rank)return;const mean=8+(c.rank-1)*1.78;for(const key in g.stats){g.stats[key]=C(M.bernoulliValue(mean),1,100);g.caps.stats[key]=Math.max(g.caps.stats[key]||0,g.stats[key]);}for(const key in g.mastery){g.mastery[key]=C(M.bernoulliValue(mean),1,100);g.caps.weapons[key]=Math.max(g.caps.weapons[key]||0,g.mastery[key]);}for(const key in g.moves){g.moves[key]=C(M.bernoulliValue(mean),1,100);if(g.caps.moves)g.caps.moves[key]=Math.max(g.caps.moves[key]||0,g.moves[key]);}for(const part of Object.values(g.body)){part.strength=C(M.bernoulliValue(mean),1,100);part.agility=C(M.bernoulliValue(mean),1,100);}const q=Math.min(6,Math.floor((c.rank-1)/8));for(const it of [g.enemyGear.weapon,g.enemyGear.secondary,g.enemyGear.shield,...Object.values(g.enemyGear.armor)].filter(Boolean))it.q=q;};

function beginChallenge(id){const c=S.army.challenges.find(c=>c.id===id&&!c.used);if(!c)return 'Herausforderung nicht mehr verfügbar.';if(plan().size!==c.size)return 'Wähle ein '+c.size+'er-Team.';S.pendingChallenge=c;const result=M.beginFight('challenge',id);if(result)delete S.pendingChallenge;else{c.used=true;delete S.pendingChallenge;M.persist();}return result;}
function fightSize(){return S.pendingChallenge?.size||plan()?.size||3;}
function onArmyBattle(b){const p=plan();b.teamTactics=[M.copy(S.tactics),{aggression:'Ausgeglichen',formation:'Normal',priority:'Nächster Gegner',ranged:'Abstand halten',help:'Hoch'}];for(const a of b.actors){const w=M.gear(a.g,'weapon');if(ranged.includes(w?.def))a.ammo=M.itemStats(w).ammo;}
 const leader=b.actors.find(a=>a.team===0&&a.g.id===p.leader),foe=b.actors.filter(a=>a.team===1).sort((a,b)=>heroValue(b.g)-heroValue(a.g))[0];b.leaders=[leader?.id,foe?.id];b.moraleBonus=[leader?Math.min(5,heroValue(leader.g)*.05):0,foe?Math.min(5,heroValue(foe.g)*.05):0];savePlan();}
function hospitalEstimate(g){let days=0,permanent=false;for(const p of Object.values(g.body)){if(p.missing||p.chronic>0)permanent=true;if(p.missing)continue;days=Math.max(days,Math.ceil((100-p.chronic-p.hp)/(3+S.buildings.hospital)),Math.ceil(p.fracture?.days||0),Math.ceil(p.internal?.days||0));}days=Math.max(days,Math.ceil(g.fatigue/(14+S.buildings.hospital)),Math.ceil((100-g.blood)/12));return {days:Math.max(0,days),permanent};}
const rest=M.advanceDay;function nextDay(){if(S.battle)return 'Während eines Kampfes nicht möglich.';const wasBatch=M.batchSaving;M.batchSaving=true;try{const before=new Set(S.roster.filter(g=>!ready(g,true)).map(g=>g.id)),children=S.children.length;rest(1);S.market=[];let learning=0;for(const g of S.roster){const id=g.trainingWeapon||M.gear(g,'secondary')?.def;if(!id)continue;const l=M.lesson(g,id);if(l.teacher&&g.fatigue<75){const gain=Math.min(l.cap-M.mastery(g,id),.025*(1+(g.potential||50)/100));if(gain>0){g.mastery[id]+=gain;learning+=gain;}}}
 const cfg=S.army.recruit;let recruited=[];if(cfg.enabled){const affordable=Math.max(0,Math.floor((S.gold-cfg.minGold)/100)),gap=Math.max(0,cfg.target-S.roster.length),reserves=cfg.reserves?Math.max(0,cfg.reserves-S.roster.filter(g=>!S.teams.flat().includes(g.id)).length):Infinity;recruited=recruitMany(Math.min(cfg.perDay,affordable,gap,reserves),{automatic:true});}
 if(S.army.auto.classes)autoClasses();if(S.army.auto.teams){const active=S.teamIndex;for(let i=0;i<S.teams.length;i++){activateTeam(i);autoTeam(S.army.mode);}activateTeam(active);}if(S.army.auto.replacements){const active=S.teamIndex;for(let i=0;i<S.teams.length;i++){activateTeam(i);replaceInjured();}activateTeam(active);}if(S.army.auto.equipment)autoEquip();generateChallenges();const healed=S.roster.filter(g=>before.has(g.id)&&ready(g,true)).map(g=>g.name);S.army.dayReport={day:S.day,healed,recruited:recruited.map(g=>g.id),training:learning,offspring:S.children.slice(children).map(c=>c.id),sold:M.dailySold(),challenges:S.army.challenges.length};M.persist();return 'Tag '+S.day+': '+healed.length+' genesen, '+recruited.length+' Rekruten, '+(S.children.length-children)+' Nachwuchstalente.';}finally{M.batchSaving=wasBatch;if(!wasBatch)M.persist();}}
M.advanceDay=()=>nextDay();
// Independent workshop retains the historical specialist records, never removes a fighter from a team.
if(!S.army.forgeMigration){for(const g of S.roster)g.smithAssigned=false;S.smiths=(S.smiths||[]).filter(s=>s.categories);if(!S.smiths.length){const t={id:M.uid(),name:'Fabrius',categories:{}};M.ensureSmith(t);S.smiths.push(t);}S.army.forgeMigration=true;}
function hireWorkshop(){if(S.battle)return 'Während des Kampfes nicht möglich.';const cost=250*Math.pow(2,S.smiths.length-1);if(S.gold<cost)return 'Nicht genug Gold.';S.gold-=cost;S.stats.spent+=cost;const t={id:M.uid(),name:M.pick(['Fabrius','Vulcanus','Ferrus','Acer'])+' '+(S.smiths.length+1),categories:{}};M.ensureSmith(t);S.smiths.push(t);M.persist();return t.name+' eingestellt.';}
function forgeInfo(key){for(const t of S.smiths)M.ensureSmith(t);const base=Math.max(0,...S.smiths.map(t=>t.categories[key]?.current||0)),cap=Math.max(base,...S.smiths.map(t=>t.categories[key]?.potential||0));S.army.forgeKnowledge??={};return {current:Math.max(base,S.army.forgeKnowledge[key]||0),potential:cap};}
function workshopCraft(kind,def,q,material='metal'){if(S.battle)return 'Während des Kampfes nicht möglich.';q=+q;if(!M.forgeCategories.some(c=>c.kind===kind&&c.def===def)||!Number.isInteger(q)||q<0||q>6)return 'Ungültige Ausrüstung.';const cost=Math.round(M.itemPrice(kind,def,q)*.9);if(S.gold<cost)return 'Nicht genug Gold.';const key=kind+'/'+def,k=forgeInfo(key),i=M.makeItem(kind,def,q,material),roll=()=>.9+.2*Math.pow(M.rng(),1/(.65+k.current/100));i.rolls=Object.fromEntries(['damage','speed','range','weight','pen','block','crit','protection','area'].map(n=>[n,n==='weight'?2-roll():roll()]));i.forgeRange=.1;i.maker='Schmiedebetrieb';i.forgedDay=S.day;i.durability=i.maxDurability;S.inventory.push(i);S.gold-=cost;S.stats.spent+=cost;S.army.forgeKnowledge[key]=Math.min(k.potential,k.current+.04*Math.pow(Math.max(0,1-k.current/Math.max(1,k.potential)),.65));M.persist();return M.itemName(i)+' hergestellt. Werte einmalig innerhalb ±10 %.';}
function workshopImprove(id,axis){if(S.battle)return 'Während des Kampfes nicht möglich.';const i=M.inventoryItem(id);if(!i||!['sharp','balance','penetration','durability'].includes(axis))return 'Gegenstand nicht gefunden.';i.up??={sharp:0,balance:0,penetration:0,durability:0};const cost=Math.round(30*Math.pow(1.7,i.up[axis]||0)+M.itemPrice(i.kind,i.def,i.q)*.04);if(S.gold<cost)return 'Nicht genug Gold.';if((i.up[axis]||0)>=10)return 'Maximal verfeinert.';S.gold-=cost;S.stats.spent+=cost;i.up[axis]=(i.up[axis]||0)+1;if(axis==='durability'){i.maxDurability+=5;i.durability+=5;}M.persist();return 'Verfeinerung verbessert · '+cost+' Gold.';}
M.craft=workshopCraft;M.forgeStaff=()=>S.smiths;M.forgeKnowledge=key=>forgeInfo(key);M.assignSmith=()=> 'Die Schmiede arbeitet unabhängig vom Gladiatorenkader.';
if(!S.army.familyTimeMigration){for(const w of S.household)if(w.partnerId)w.nextFamilyDay=Math.min(w.nextFamilyDay||S.day+30,S.day+30);for(const c of S.children){c.template.age=Math.max(18,c.template.age);}S.army.familyTimeMigration=true;}if(!S.army.challenges||S.army.challengeVersion!==2)generateChallenges();
M.pendingOpponentRole=i=>{const style=S.pendingChallenge?.style;return style==='Soldaten'?(i%4===3?'Fernkämpfer':'Soldat'):style==='Assassinen'?(i%3===0?'Soldat':'Assassine'):style==='Fernkämpfer'?(i%3===0?'Soldat':'Fernkämpfer'):M.roles[i%3];};Object.assign(M,{army:{person,plan,teamOf,bestWeapon,equipmentNeeds,rating,eligibility,ready,recruitMany,autoClasses,autoEquip,getSlot,putSlot,slots,savePlan,activateTeam,newTeam,deleteTeam,setMember,autoTeam,replaceInjured,prepareTeam,ammoRequired,buyAmmo,heroValue,challengeTier,generateChallenges,beginChallenge,hospitalEstimate,nextDay,hireWorkshop,forgeInfo,workshopImprove,audit},fightSize,onArmyBattle});
})();
