'use strict';
(()=>{const M=window.MG,S=M.s;
const specs={
 Soldat:{stats:{strength:.16,stamina:.11,condition:.08,block:.16,balance:.11,toughness:.11,pain:.07,will:.05,teamwork:.08,tactics:.04,experience:.03},moves:{shieldBash:.20,overhead:.15,thrust:.15,slash:.15,charge:.15,recover:.10,rise:.10},weapons:['short','gladius','long','axe','doubleaxe','club','mace','hammer','spear','trident','halberd','greatsword'],body:['lua','rua','chest','lt','rt'],plan:'Hält die Front, bindet Gegner und schützt bedrängte Fernkämpfer. Metallrüstung; Schild für Schutz oder Zweihandwaffe für Schaden.'},
 Assassine:{stats:{agility:.22,reflex:.16,dexterity:.16,tactics:.12,experience:.07,teamwork:.08,condition:.08,precision:.06,balance:.05},moves:{rearFinish:.25,dodge:.20,backstep:.15,thrust:.15,charge:.10,spin:.10,sand:.05},weapons:['dagger','short','gladius','axe','long'],body:['lt','rt','lf','rf','rh'],plan:'Umläuft gebundene Gegner und greift Seite oder Rücken an. Leder oder keine Rüstung; kurze, schnelle Klingen.'},
 Fernkämpfer:{stats:{precision:.25,dexterity:.18,tactics:.13,reflex:.10,agility:.12,condition:.07,experience:.08,teamwork:.07},moves:{backstep:.35,dodge:.30,thrust:.15,sand:.10,recover:.10},weapons:['bow','crossbow','javelin','throwaxe','net'],body:['rh','rfa','lua','lf','rf'],plan:'Hält Abstand, sucht freie seitliche Schusslinien und nutzt die Front als Deckung. Leichte Rüstung, Fernwaffe und eine Nahkampfwaffe als Reserve.'}
};
function scoutScore(g,role,potential=true){M.ensureCareer(g);const d=specs[role]||specs.Soldat,st=potential?g.caps.stats:g.stats,mv=potential?g.caps.moves:g.moves,ws=potential?g.caps.weapons:g.mastery;const weighted=(keys,values)=>Object.entries(keys).reduce((n,[k,w])=>n+(values[k]||1)*w,0);const best=d.weapons.map(id=>({id,value:ws[id]||1})).sort((a,b)=>b.value-a.value||a.id.localeCompare(b.id))[0];const body=d.body.reduce((n,id)=>n+(potential?g.caps.body[id].strength+g.caps.body[id].agility:g.body[id].strength+g.body[id].agility)/2,0)/d.body.length;return {score:M.clamp(weighted(d.stats,st)*.55+weighted(d.moves,mv)*.15+best.value*.20+body*.10,1,100),best,components:{stats:weighted(d.stats,st),moves:weighted(d.moves,mv),weapon:best.value,body}};}
function scout(g){const roles=M.roles.map(role=>({role,current:scoutScore(g,role,false),potential:scoutScore(g,role,true)})).sort((a,b)=>b.potential.score-a.potential.score);return {roles,recommended:roles[0].role,overall:roles[0].potential.score};}
function setClass(id,role){if(S.battle)return 'Während eines Kampfes nicht möglich.';const g=S.roster.find(g=>g.id===id);if(!g||!M.roles.includes(role))return 'Klasse nicht gefunden.';g.role=role;M.persist();return g.name+' · '+role;}
Object.assign(M,{classSpecs:specs,scoutScore,scout,setClass});})();
