'use strict';
(()=>{const M=window.MG,S=M.s,C=M.clamp;
// Independent, bounded numerical model. Never calls the live simulation or its RNG.
function fighter(g,side,i,n,formation){const st={...g.stats},primary=M.gear(g,'weapon'),secondary=M.gear(g,'secondary'),ranged=primary&&['bow','crossbow'].includes(primary.def),item=ranged?primary:secondary||primary,w=M.itemStats(item)||{id:'fist',damage:4,delay:1.1,range:24,pen:0,weight:1},backup=M.itemStats(secondary)||{id:'fist',damage:4,delay:1.1,range:24,pen:0,weight:1},armor=M.armorItems(g),weight=M.weightGear(g),protection=armor.reduce((v,it)=>{const d=M.definition(it);return v+M.itemStats(it).protection*d.parts.length/18;},0),shield=M.itemStats(M.gear(g,'shield')),legs=M.limb(g,['lt','rt','lsh','rsh','lf','rf']),arm=M.limb(g,['rs','rua','rfa','rh']),health=M.health(g),torso=M.limb(g,['chest','belly']),pain=Object.values(g.body).reduce((v,p)=>v+p.pain,0)/18;
return {id:g.id,name:g.name,side,role:g.role,st,mastery:{...g.mastery},moves:{...g.moves},rivals:Object.keys(g.social?.rivals||{}),friends:JSON.parse(JSON.stringify(g.social?.bonds||{})),x:side?700:300,y:180+i*360/Math.max(1,n-1),hp:health*1.5,full:health*1.5,energy:(65+st.stamina*1.15)*(.5+torso*.5)*(1-g.fatigue*.005),maxEnergy:65+st.stamina*1.15,regen:(5+st.condition*.14)*torso/(1+weight/(30+st.strength*.4)),speed:(35+st.agility*.45)*(.18+.82*legs)/(1+weight/(30+st.strength*.4))*(armor.every(it=>it.material==='leather')?1.18:1),ranged,ammo:ranged?w.ammo:0,w,backup,shield:shield&&!w.twoHand?shield:null,armor:protection,reach:g.arm*.19,force:(.58+st.strength*.009+(g.body.rua.strength+g.body.rfa.strength+g.body.rh.strength)/3*.004+g.muscle*.003)*(.3+.7*arm)*C(1-pain/(130+st.pain*2),.48,1)*C(g.blood/100,.4,1)*(.85+st.morale*.003)*(1-g.fatigue*.003),cool:0,bleed:Object.values(g.body).reduce((v,p)=>v+p.bleed,0)*.025,target:null,dead:false,down:false,formation};}
function simulate(base,random,risk){const a=base.map(v=>({...v})),alive=t=>a.filter(v=>v.side===t&&!v.down),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);let winner=-1;
for(let turn=0;turn<540;turn++){const sides=[alive(0),alive(1)];if(!sides[0].length||!sides[1].length){winner=sides[0].length?0:sides[1].length?1:-1;break;}
for(const f of a){if(f.down)continue;f.hp-=f.bleed*.5;if(f.hp<=0){f.down=true;f.dead=random()<C(.02+risk*.6,0,.16);continue;}const allies=sides[f.side],foes=sides[1-f.side].filter(g=>!g.down);if(!foes.length)continue;let t=null,best=Infinity;for(const v of foes){let score=distance(f,v);if(f.role==='Assassine'&&v.target&&v.target!==f.id)score-=80*f.st.tactics/100;if(f.role==='Soldat'&&v.role==='Assassine')score-=25;if(f.rivals.includes(v.id))score-=20;const bond=f.friends[v.target]?.value||0;score-=bond*.2;if(score<best){best=score;t=v;}}f.target=t.id;const d=distance(f,t),near=d<75,ranged=f.ranged&&f.ammo>0&&!near,w=ranged?f.w:f.ranged?f.backup:f.w,range=ranged?w.range:w.range+f.reach,damageScale=1+(f.mastery[w.id]||0)*.003,front=allies.some(x=>x.role==='Soldat'&&x.id!==f.id&&distance(x,t)<150),flank=allies.some(x=>x.role==='Assassine'&&x.id!==f.id&&distance(x,t)<140),fire=allies.some(x=>x.role==='Fernkämpfer'&&x.id!==f.id&&x.ammo>0),cooperation=C((f.st.teamwork+f.st.tactics)/200,0,1),support=f.role==='Soldat'?1+(fire?.12:0)*cooperation+(flank?.08:0)*cooperation:1+(front?.2:0)*cooperation;
f.energy=Math.min(f.maxEnergy,f.energy+f.regen*.5);f.cool-=.5;if(d>range+10||ranged&&d<150){const direction=ranged&&d<150?-1:1,dx=(t.x-f.x)/Math.max(1,d),dy=(t.y-f.y)/Math.max(1,d);f.x=C(f.x+dx*f.speed*.5*direction,80,960);f.y=C(f.y+dy*f.speed*.5*direction+(f.role==='Assassine'?Math.sin(turn*.1+f.y)*3:0),140,640);if(d>range+25)continue;}if(f.cool>0)continue;
f.cool=w.delay/((.7+f.st.dexterity*.007)*(1+(f.mastery[w.id]||0)*.002));if(ranged){f.ammo--;if(w.id==='crossbow')f.cool=Math.max(2,f.cool);}f.energy-=5+(w.weight||1)*.7;
const back=f.role==='Assassine'&&t.target!==f.id&&random()<C((f.st.tactics+f.st.agility+f.st.experience+f.st.teamwork)/600,.04,.5),hitChance=C(.76+(f.st.precision+f.st.dexterity-t.st.reflex-t.moves.dodge)*.001, .3,.96);if(random()>hitChance)continue;if(!back&&t.shield&&random()<C(t.st.block*.005+t.shield.block*.2,0,.58)){t.energy=Math.max(0,t.energy-6);continue;}let damage=w.damage*damageScale*f.force*support*(.78+random()*.44)*(back?(w.id==='dagger'?2.5:2):1)*(f.energy<15?.55:1);damage=Math.max(1.4,damage-t.armor*(1-(w.pen||0))*.55);if(random()<.025+f.st.precision*.0012+f.st.experience*.0008)damage*=w.crit||1.5;t.hp-=damage*.72;if(w.bladed||ranged)t.bleed+=damage*.002;if(t.hp<=0){t.down=true;t.dead=random()<C(.01+risk*.7+damage/1200,.01,.22);}}
}
if(winner<0){const totals=[0,1].map(t=>a.filter(f=>f.side===t&&!f.down).reduce((v,f)=>v+Math.max(0,f.hp),0));winner=totals[0]===totals[1]?-1:totals[0]>totals[1]?0:1;}
// The existing crowd can condemn incapacitated members of the defeated team.
for(const f of a)if(f.down&&!f.dead&&f.side!==winner&&random()<1/3)f.dead=true;
return {winner,survived:a.filter(f=>f.side===0&&!f.dead).map(f=>f.id)};}
async function spy(sid,tid,onProgress){if(S.battle)throw Error('Beende zuerst den Kampf.');const s=M.world.school(sid),t=s?.teams.find(t=>t.id===tid),own=M.selectedTeam();if(!t||own.length!==t.size||M.army.plan().size!==t.size)throw Error('Wähle ein vollständiges eigenes '+(t?.size||'passendes')+'er-Team.');const enemy=M.world.teamRoster(s,t);if(enemy.length!==t.size||enemy.some(g=>!M.world.fighting(g)))throw Error('Dieses Team ist nicht einsatzbereit.');const reportDay=S.day,planId=M.army.plan().id;const ownNames=own.map(g=>({id:g.id,name:g.name}));const base=[...own.map((g,i)=>fighter(g,0,i,own.length,M.army.plan().formation)),...enemy.map((g,i)=>fighter(g,1,i,enemy.length,'Normal'))],counts=Object.fromEntries(own.map(g=>[g.id,0]));let seed=(Math.random()*4294967296)>>>0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;};let wins=0,draws=0;const started=performance.now(),risk=M.leagues[M.world.prices(s,t).league].risk;for(let n=0;n<100;n++){const r=simulate(base,random,risk);wins+=r.winner===0?1:0;draws+=r.winner<0?1:0;for(const id of r.survived)counts[id]++;if((n+1)%5===0){onProgress?.(n+1);await new Promise(resolve=>setTimeout(resolve,0));}}return {schoolId:sid,teamId:tid,playerTeamId:planId,day:reportDay,trials:100,wins,draws,winChance:wins,survival:ownNames.map(g=>({id:g.id,name:g.name,count:counts[g.id],chance:counts[g.id]})),ms:Math.round(performance.now()-started)};}
M.spyTeam=spy;
})();
