'use strict';
(()=>{const M=window.MG;let preview=null;
function startTechniquePreview(canvas,g,key){if(!canvas||!M.moveNames[key])return;const copy=JSON.parse(JSON.stringify(g));copy.enemyGear={weapon:JSON.parse(JSON.stringify(M.gear(g,'weapon')||null)),secondary:JSON.parse(JSON.stringify(M.gear(g,'secondary')||null)),shield:JSON.parse(JSON.stringify(M.gear(g,'shield')||null)),armor:Object.fromEntries(M.armorItems(g).map(i=>[i.def,JSON.parse(JSON.stringify(i))]))};const melee=[copy.enemyGear.secondary,copy.enemyGear.weapon].find(i=>i&&!M.definition(i).ammo);copy.enemyGear.weapon=melee||null;copy.enemyGear.secondary=null;let farmer=null;if(['rearFinish','groundFinish','pierce','sand'].includes(key)){farmer=JSON.parse(JSON.stringify(copy));farmer.id='preview-farmer';farmer.name=key==='groundFinish'?'Trainingspartner':'Bauer';farmer.age=35;farmer.height=175;farmer.weight=72;farmer.fame=0;farmer.dead=false;farmer.bisected=false;farmer.fatigue=0;farmer.blood=100;farmer.scars=[];farmer.appearance={...farmer.appearance,cloth:'#8c7955',style:1,beard:2};farmer.equipment={weapon:null,secondary:null,shield:null,armor:{}};farmer.enemyGear={weapon:null,secondary:null,shield:null,armor:{}};for(const part of Object.values(farmer.body)){Object.assign(part,{hp:100,pain:0,bleed:0,missing:false,fracture:null,internal:null,wounds:[]});}}const skill=g.moves[key]||0;const combo=key==='combo'?[]:null;if(combo){const length=2+Math.floor(Math.random()*3);for(let n=0;n<length;n++){const pool=['slash','thrust','overhead','spin'].filter(k=>k!==combo[n-1]);combo.push(pool[Math.floor(Math.random()*pool.length)]);}}preview={canvas,g:copy,farmer,key,combo,t:0,speed:(.65+skill*.009)*1.05,done:false};tick(0);}
function tick(dt){const p=preview;if(!p||p.canvas.isConnected===false)return;if(p.done)return;p.t+=Math.min(dt,.05)*p.speed;const t=p.t,a={g:p.g,x:230,y:218,a:0,team:0,phase:t*10,energy:100,ammo:3,state:'idle',moveSpeed:0},dummy=p.farmer?{g:p.farmer,x:316,y:218,a:0,team:1,energy:100,state:'idle',phase:0,moveSpeed:0}:{x:316,y:218};let contact=0;const wind=M.clamp((t-.35)/.7,0,1),swing=M.clamp((t-1.05)/.6,0,1),active=t>=1.05&&t<1.65;
if(p.key==='groundFinish'){a.previewVictim=dummy;a.x=285;dummy.x=340;dummy.down=true;dummy.state='down';dummy.fallSide=-1;dummy.energy=20;a.technique='groundFinish';a.contactPoint=M.contactAnchor(dummy,'chest');if(t>.35&&t<1.95){a.windMax=1.6;a.wind=1.95-t;}if(t>=1.95&&t<2.85){const k=(t-1.95)/.9;a.swingKind='groundFinish';a.swingMax=.9;a.swing=2.85-t;contact=k>.55?(k-.55)/.45:0;}}
else if(p.key==='pierce'){a.x=270;a.previewVictim=dummy;a.technique='thrust';a.contactPoint=M.contactAnchor(dummy,'chest');if(t>.35&&t<1.05){a.windMax=.7;a.wind=1.05-t;}if(t>=1.05&&t<1.45){a.swingKind='thrust';a.swingMax=.4;a.swing=1.45-t;}if(t>=1.27&&t<2){a.pierceContact={target:dummy.g.id,part:'chest',left:.5*(1-(t-1.27)/.73)};a.swing=0;contact=1;}}
else if(p.key==='combo'){const i=Math.floor(Math.max(0,t-.35)/.68),k=(t-.35)-i*.68;if(t>=.35&&i<p.combo.length){a.technique=p.combo[i];if(k<.22){a.windMax=.22;a.wind=.22-k;}else{a.swingKind=p.combo[i];a.swingMax=.46;a.swing=.68-k;contact=k>.44?1:0;}a.x=245+(a.technique==='thrust'?Math.sin(k/.68*Math.PI)*16:0);}a.previewCombo=p.combo.length;}
else if(['slash','overhead','thrust','spin'].includes(p.key)){a.technique=p.key;if(t>.35&&t<1.05){a.windMax=.7;a.wind=.7*(1-wind);}if(active){a.swingKind=p.key;a.swingMax=.6;a.swing=.6*(1-swing);a.x+=p.key==='thrust'?Math.sin(swing*Math.PI)*14:0;contact=swing>.55?(swing-.55)/.45:0;}}
else if(p.key==='shieldBash'){a.x+=16;if(active){a.shieldBashTimer=.44*(1-swing);a.state='shieldbash';contact=swing>.5?(swing-.5)*2:0;}}
else if(p.key==='kick'){a.x+=12;if(active){a.kickTimer=.48*(1-swing);a.state='kick';contact=swing>.5?(swing-.5)*2:0;}}
else if(p.key==='charge'){a.x=160+M.clamp((t-.3)/.85,0,1)*90;if(t>.3&&t<1.15){a.state='charge';a.moveSpeed=90;}if(t>=1.15&&t<1.65){a.swingKind='overhead';a.swingMax=.5;a.swing=1.65-t;contact=t>1.42?(t-1.42)*4:0;}}
else if(p.key==='sand'){if(active){a.sandKick=.62*(1-swing);a.state='sandkick';a.previewSand=swing;contact=swing>.5?(swing-.5)*2:0;}if(t>1.3&&t<2.5){dummy.wipeTimer=2.5-t;dummy.blindTimer=2.5-t;dummy.state='wipe';}}
else if(p.key==='backstep'){if(active){a.jumpTimer=.26*(1-swing);a.x-=swing*48;a.state='backstep';}}
else if(p.key==='dodge'){if(active){a.dodgeTimer=.22*(1-swing);a.y+=Math.sin(swing*Math.PI)*23;a.x-=Math.sin(swing*Math.PI)*14;}}
else if(p.key==='recover'){if(t>.5&&t<1.25){a.stagger=(1.25-t)*.7;a.hit=.12;a.state='stagger';}}
else if(p.key==='rise'){a.fallSide=-1;if(t<.8){a.state='fallen';a.fallTimer=2;a.fallDuration=2.5;}else if(t<2.15){a.state='rising';a.riseDuration=1.35;a.fallTimer=2.15-t;a.fallDuration=2.6;}}
else if(p.key==='rearFinish'){
a.x=296;a.y=221;dummy.x=316;
const gripStart=.5,contactTime=gripStart+.85;
if(t>=gripStart&&t<contactTime){a.state='reargrab';dummy.state='grabbed';a.rearFinish={target:'dummy',left:contactTime-t};a.previewVictim=dummy;}
if(t>=contactTime&&p.farmer){const elapsed=t-contactTime,pose=M.rearFollowPose(elapsed);dummy.finishReaction=elapsed;dummy.down=true;dummy.fallSide=-1;dummy.x+=pose.slide;
if(elapsed<.7){a.state='finishpush';a.finishPush={elapsed};a.postKickPose=M.limb(a.g,['rt','rsh','rf'])>.45?pose.kick:0;}
}
}
M.renderTechnique(p.canvas,a,dummy,contact);if(t>(p.key==='combo'?.8+p.combo.length*.68:p.key==='groundFinish'?3.5:p.key==='rearFinish'?2.9:2.5))p.done=true;}
Object.assign(M,{startTechniquePreview,stopTechniquePreview:()=>preview=null,previewTick:tick});})();
