'use strict';
// Herumtreiber: kleine Gruppen (1–3) erscheinen in Abständen vor der Schule. Der Spieler wählt KAMPF oder KEIN KAMPF.
// Kämpfe laufen vollständig über das vorhandene Kampf-, Team- und Abrechnungssystem. Dialoge folgen später über eine eigene Schnittstelle.
(()=>{
const M=window.MG,S=M.s,A=M.army,W=M.world,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const personalities=[['freundlich','freundlich'],['arrogant','arrogant'],['aggressiv','aggressiv'],['grossmaul','großmäulig'],['feige','feige'],['ehrenhaft','ehrenhaft'],['hinterlistig','hinterlistig'],['veteran','wie ein besoffener Veteran'],['soeldner','wie ein brutaler Söldner'],['raeuber','wie ein Straßenräuber'],['irre','vollkommen durchgeknallt']];
const SCHOOL='wanderers',state=()=>S.wanderers??={version:1,next:0,group:null,known:[]};
const fit=()=>S.roster.filter(g=>A.ready(g,true)).sort((a,b)=>M.power(b)-M.power(a));
// Ein Herumtreiber entsteht wie ein Arenagegner: vorhandener Generator, vorhandene Schwierigkeitsstufen. Die Stufe wird so gewählt, dass der vorhandene Kampfwert zum Ziel passt.
function drifter(target){let lo=1,hi=50,best=null;for(let n=0;n<7;n++){const rank=(lo+hi)/2,g=M.makeGladiator(0,true);g.enemy=true;M.ensureCareer(g);g.role=M.pick(M.roles);const weapon=g.role==='Fernkämpfer'?M.pick(['bow','crossbow']):g.role==='Soldat'?M.pick(['short','gladius','mace','spear']):M.pick(['dagger','axe','short','long']);g.enemyGear={weapon:M.makeItem('weapon',weapon,0),secondary:M.makeItem('weapon','dagger',0),shield:g.role==='Soldat'&&M.rng()<.6?M.makeItem('shield','smallshield',0):null,armor:{}};for(const d of M.armorDefs)if(M.rng()<(g.role==='Soldat'?.5:.3))g.enemyGear.armor[d.id]=M.makeItem('armor',d.id,0,'leather');M.applyChallengeDifficulty(g,{rank});for(const k in g.stats)g.stats[k]=Math.min(g.caps.stats[k],g.stats[k]);for(const k in g.mastery)g.mastery[k]=Math.min(g.caps.weapons[k],g.mastery[k]);for(const it of [g.enemyGear.weapon,g.enemyGear.secondary,g.enemyGear.shield,...Object.values(g.enemyGear.armor)].filter(Boolean))it.durability=it.maxDurability;const power=M.power(g);if(!best||Math.abs(power-target)<Math.abs(best.power-target))best={g,power};if(power<target)lo=rank;else hi=rank;}return best.g;}
function spawn(){const st=state(),mine=fit();if(st.group||!mine.length)return null;const size=Math.min(mine.length,1+Math.floor(M.rng()*3)),factor=M.rng()<.72?M.rnd(.6,.97):M.rnd(.97,1.4),members=[];for(let i=0;i<size;i++)members.push(drifter(M.power(mine[i])*factor*M.rnd(.92,1.08)));const kind=M.pick(personalities);st.group={id:M.uid(),day:S.day,size,members,leader:{id:members[0].id,name:members[0].name,personality:kind[0],aggression:Math.round(M.rnd(5,95)),courage:Math.round(M.rnd(5,95)),sympathy:Math.round(M.rnd(-40,40)),fightWill:Math.round(M.rnd(10,95))},fightId:null};return st.group;}
function remember(outcome){const st=state(),g=st.group;if(!g)return;const old=st.known.find(k=>k.name===g.leader.name);const entry={name:g.leader.name,personality:g.leader.personality,relation:(old?.relation||0)+(outcome==='won'?-10:outcome==='lost'?5:0),lastDay:S.day,meetings:(old?.meetings||0)+1,outcome};st.known=[entry,...st.known.filter(k=>k!==old)].slice(0,20);st.group=null;st.next=S.day+4+Math.floor(M.rng()*5);}
function decline(){const st=state();if(!st.group||S.battle)return '';const name=st.group.leader.name;remember('declined');M.persist();return (st.known[0].meetings>1?name+' und seine Leute ziehen wieder ab.':'Die Herumtreiber ziehen weiter.');}
function ensurePlan(size){const i=S.teamPlans.findIndex(p=>p.size===size);if(i<0){A.newTeam('Kohorte '+(S.teams.length+1),size);W.teamIds?.();}else if(i!==S.teamIndex)A.activateTeam(i);return A.plan()?.size===size;}
function fight(){const st=state(),g=st.group;if(!g)return 'Niemand steht vor dem Tor.';if(S.battle)return 'Es läuft bereits ein Kampf.';if(!ensurePlan(g.size))return 'Für diese Größe kann kein Team angelegt werden.';S.pendingChallenge={schoolId:SCHOOL,wanderer:g.id,size:g.size,name:'Herumtreiber · '+g.leader.name,league:S.fightLeague??S.league,fee:0,reward:0};const error=M.beginFight('school',g.id);delete S.pendingChallenge;if(!error){g.fightId=S.battle.id;M.persist();}return error;}
function settle(report){const st=state(),g=st.group;if(!g?.fightId||report?.id!==g.fightId)return;remember(report.won?'won':report.draw?'draw':'lost');M.persist();}
// Vorhandene Einhängepunkte: Gegneraufstellung, Kampfende, Tageswechsel.
const opponent=M.worldOpponent;M.worldOpponent=()=>{const c=S.pendingChallenge;if(c?.schoolId!==SCHOOL)return opponent?.();const g=state().group;return {name:c.name,champion:false,roster:g.members};};
const finished=M.onFinish;M.onFinish=report=>{settle(report);return finished?.(report);};
const nextDay=A.nextDay;A.nextDay=(...args)=>{const result=nextDay(...args);if(S.battle||M.benchmarkActive)return result;const st=state();if(st.group&&!st.group.fightId&&st.group.day<S.day){remember('ignored');}if(!st.next)st.next=S.day+2+Math.floor(M.rng()*4);else if(!st.group&&S.day>=st.next&&S.lanista){if(spawn()){M.persist();return typeof result==='string'?(result+' Herumtreiber stehen vor dem Tor.').trim():result;}st.next=S.day+1;}M.persist();return result;};M.advanceDay=A.nextDay;
// ---------- Oberfläche: Kasten im Ludus und Seite für Aufstellung und Kampfbeginn ----------
function lineup(g){const mine=fit().slice(0,g.size).reduce((n,x)=>n+M.power(x),0),theirs=g.members.reduce((n,x)=>n+M.power(x),0),kind=personalities.find(p=>p[0]===g.leader.personality)?.[1]||'undurchschaubar';return `<div class="world-fighters">${g.members.map((x,i)=>`<div class="world-fighter"><canvas data-wanderer-portrait="${esc(x.id)}"></canvas><b>${esc(x.name)}</b><small>${esc(x.role)}${i?'':' · Anführer'}<br>KW ${M.power(x)}<br>${esc(M.itemName(M.gear(x,'weapon')||M.gear(x,'secondary')))}</small></div>`).join('')}</div><p>${esc(g.leader.name)} wirkt ${esc(kind)}. Kampfwert der Gruppe: <b>${theirs}</b> · deine stärksten ${g.size===1?'Kämpfer':g.size}: <b>${mine}</b>.</p>`;}
function box(){const g=state().group;if(!g||g.fightId)return '';return `<section class="box wanderer-box"><p class="eyebrow">VOR DEM TOR</p><h2>${g.size===1?'Ein Herumtreiber':g.size+' Herumtreiber'} · ${g.size} gegen ${g.size}</h2>${lineup(g)}<div class="buttons"><button class="btn primary" data-action="wanderer:fight">⚔ KAMPF</button><button class="btn" data-action="wanderer:leave">KEIN KAMPF</button></div></section>`;}
function page(){const g=state().group;if(!g||g.fightId)return `<div class="pagehead"><div><p class="eyebrow">${esc(S.schoolName)} · TAG ${S.day}</p><h1>Herumtreiber</h1><p>Vor dem Tor steht niemand mehr.</p></div></div><div class="buttons"><button class="btn" data-action="nav:home">ZURÜCK ZUM LUDUS</button></div>`;const ready=A.plan()?.size===g.size&&M.selectedTeam().length===g.size&&!M.validateTeam('school');return `<div class="pagehead"><div><p class="eyebrow">${esc(S.schoolName)} · TAG ${S.day}</p><h1>Herumtreiber</h1><p>${g.size} gegen ${g.size} im Sand deiner Arena. Kein Antrittsgeld, keine Siegprämie – Verletzungen und Tod bleiben dauerhaft.</p></div></div><section class="box"><h2>Die Gruppe</h2>${lineup(g)}</section><section class="box"><h2>Dein ${g.size}er-Team</h2>${M.teamPicker?.({size:g.size})||''}</section><section class="box"><div class="buttons"><button class="btn primary" data-action="wanderer:start" ${ready?'':'disabled'}>⚔ KAMPF BEGINNEN</button><button class="btn" data-action="wanderer:leave">KEIN KAMPF</button><button class="btn" data-action="nav:home">ZURÜCK</button></div></section>`;}
M.wandererTeam=()=>{const g=state().group;return g&&!g.fightId&&M.ui?.getPage?.()==='wanderers'?{size:g.size}:null;};
const oldPage=M.schoolPage;M.schoolPage=p=>p==='wanderers'?page():p==='home'?box()+(oldPage(p)||''):oldPage(p);
const oldClick=M.schoolClick;M.schoolClick=action=>{if(!action.startsWith('wanderer:'))return oldClick(action);const key=action.split(':')[1];if(S.battle)return true;if(key==='fight'){const g=state().group;if(g&&!g.fightId){ensurePlan(g.size);M.persist();M.ui.click('nav:wanderers');}return true;}if(key==='leave'){const message=decline();if(message)M.ui.notify(message);M.ui.click('nav:home');return true;}if(key==='start'){M.audioStart?.();const error=fight();if(error){M.ui.notify(error);M.ui.render();}else M.ui.close();return true;}return true;};
const paint=M.paintTeamLineup;M.paintTeamLineup=()=>{paint?.();const g=state().group;if(!g)return;for(const c of document.querySelectorAll('[data-wanderer-portrait]')){const x=g.members.find(m=>m.id===c.dataset.wandererPortrait);if(x)M.renderPortrait(c,x);}};
M.wanderers={state,spawn,decline,fight,settle,personalities:personalities.map(p=>p[0])};
M.ui?.render?.();
})();
