'use strict';
// Vorformulierte Herumtreiber-Dialoge: Eröffnung je Persönlichkeit, vier Antworten zum Anklicken, eine Erwiderung, dann KAMPF oder KEIN KAMPF.
// Reine Texte und eine feste Auswahl je Gruppe (ohne Karriere-Zufall). Platzhalter: {D} Anrede, {S} Schule, {NN} „Drei gegen drei“, {n} Anzahl.
(()=>{
const M=window.MG;
const slots={
 D:['Sandfresser','Schulmeister','Ziegenhirt','Maulheld','Schankwirt','Hänfling','Staubschlucker','Bettvorleger','Pfeifenkopf','Hosenscheißer','Lumpensammler','Wichtigtuer','Kettenrassler','Sklavenhüter'],
 S:['Bruchbude','Hühnerstall','Sandkasten','Ziegenstall','Misthaufen','Rattenloch','Bretterverschlag','Flohzirkus','Saustall','Schuppen','Abtritt mit Tor','Bauernhof']
};
const open={
 freundlich:['Wir suchen einen Krug, etwas Schatten und ausnahmsweise mal keinen verdammten Ärger.','Schöner Hof, {D} – riecht nach Schweiß, Eisen und ehrlicher Arbeit, das mag ich.','Keine Sorge, wir beißen nur, wenn man uns das Bier wegnimmt.','Man sagt, hier wird anständig gekämpft – wir wollten nur mal schauen, ob das stimmt.','Hast du Wasser für drei staubige Kehlen oder nur böse Blicke?','Ruhig Blut, Alter, wir sind bloß auf der Durchreise und hundemüde.','Deine Jungs machen einen guten Eindruck – darf ein alter Streuner mal zusehen?','Bei den Göttern, endlich ein Tor, hinter dem nicht sofort einer mit der Mistgabel wartet.'],
 arrogant:['Das soll eine Gladiatorenschule sein, ich habe schon Latrinen mit mehr Würde gesehen.','Sag deinem Herrn, dass Besuch da ist – ach, du bist der Herr, wie bedauerlich.','Ich habe in Arenen gekämpft, deren Stallburschen besser gekleidet waren als du.','Man hat mir von diesem {S} erzählt, die Leute übertreiben wirklich gern.','Tritt beiseite, {D}, ich möchte sehen, wofür andere hier Gold bezahlen.','Deine Männer stehen herum wie Vieh, das auf den Schlachter wartet.','Ich nehme an, das Beste, was du hast, ist bereits tot.','Verzeih, ich suche jemanden von Bedeutung – weißt du zufällig, wo so einer wohnt?'],
 aggressiv:['Ist das hier eine Gladiatorenschule oder ein Stall für bewaffnete Waschlappen?','Was glotzt du so, noch nie richtige Kämpfer gesehen?','Ich hab heute noch keinem die Fresse poliert, und das macht mich unruhig.','Hol deine Besten raus, bevor ich mir die Schlechtesten selber hole.','Dein Tor ist hässlich, deine Schule stinkt und dein Gesicht gefällt mir auch nicht.','Einer von deinen Hunden hat mich schief angesehen, und jetzt will ich Blut sehen.','Ich zähl bis drei, dann will ich wissen, wer hier der Härteste ist.','Schluss mit dem Gaffen, {D}, entweder Fäuste oder ich trete dein Tor ein.'],
 grossmaul:['Man erzählt sich, hier gäb es starke Kämpfer – bislang seh ich nur dich.','Ich hab mal drei Mann mit einem Suppenlöffel erschlagen, was können deine denn so?','Schicker Laden, wär fast schade, wenn jemand ausprobieren müsste, ob deine Männer genauso hübsch sind.','Der Kerl dort hinten hält sein Schwert wie einen toten Fisch, soll ich es ihm zeigen?','In meinem Dorf haben die Waschweiber härter zugeschlagen als dein ganzer Haufen.','Ich bin der Beste zwischen hier und dem Meer, und das Meer hat Angst vor mir.','Deine Gladiatoren sehen aus, als hätte man sie aus einem Brunnen gezogen.','Leg schon mal Verbandszeug bereit, {D}, nur für den Fall, dass ich mich langweile.'],
 feige:['Wir wollen keinen Ärger, außer du hast weniger Männer, als es von hier aussieht.','Schöne Schule, wirklich, und so … viele Bewaffnete, wie ich sehe.','Mein Freund hier meint, deine Kämpfer taugen nichts – ich selbst habe dazu keine Meinung.','Wir könnten euch alle fertigmachen, aber uns tut heute der Rücken weh.','Sag mal, wie viele von denen dort sind eigentlich wach?','Hätten wir gewusst, dass hier einer wohnt, hätten wir vorher angeklopft und wären weggelaufen.','Ich fordere euch heraus, sobald meine Kameraden vorangehen.','Nur damit das klar ist, {D}, ich bin sehr gefährlich, wenn man mich nicht ansieht.'],
 ehrenhaft:['Ich grüße dich, Lanista, wir suchen einen ehrlichen Kampf ohne Tücke und ohne Publikum.','Man sagt, deine Schule kämpft sauber – das will ich mit eigener Klinge prüfen.','Kein Groll, kein Gold, nur Stahl gegen Stahl, wenn du Männer hast, die das verstehen.','Ich habe einen Eid geschworen, keinem guten Kampf aus dem Weg zu gehen.','Wir kommen nicht als Räuber, wir kommen als Männer, die wissen wollen, was sie wert sind.','Zeig mir deinen Besten, und ich zeige ihm den Respekt, den er sich verdient.','Ein offenes Tor, ein fester Boden, mehr verlange ich nicht von dir.','Sprich frei, Lanista, ich höre zu, bevor ich das Schwert ziehe.'],
 hinterlistig:['Hübsches Tor – wäre schade, wenn es nachts jemand offen ließe.','Wir sind nur einfache Wanderer, die sich gern merken, wo andere ihr Gold aufbewahren.','Du siehst müde aus, Lanista, schläfst du gut, bei so dünnen Mauern?','Ich hörte, einer deiner Männer redet im Schlaf, erstaunlich, was man da erfährt.','Wir tun dir nichts, jedenfalls nicht heute und nicht von vorn.','So viele Kämpfer, und trotzdem steht nur einer am Tor, das merke ich mir.','Nenn mir einen Grund, warum wir Freunde sein sollten, ich sammle solche Gründe.','Keine Angst, {D}, wer mich kommen sieht, hat nichts zu befürchten.'],
 veteran:['Ich hab schon geblutet, da hast du noch in die Windeln geschissen, also schenk ein oder halt den Mund.','Dreißig Jahre Sand im Maul, und noch immer hat keiner einen anständigen Krug für mich.','Früher hat man in solchen Schulen noch gestorben, heute wird hier wohl getanzt.','Mein Knie sagt Regen, mein Durst sagt Bier, und beide lügen selten.','Ich kannte deinen Vorgänger, der war auch ein Arschloch, aber er hatte Wein.','Stell mir einen deiner Welpen hin, ich bring ihm bei, wie man fällt.','Ich hab mehr Narben als du Zähne, Junge, und beides wird nicht mehr.','Riecht wie damals in Capua hier, nach Angst, Öl und billigem Fusel.'],
 soeldner:['Wir töten für Gold, und für wenig Gold töten wir schlampig.','Dein Nachbar hat uns nichts bezahlt, also schauen wir mal, was es bei dir zu holen gibt.','Ich hab keinen Streit mit dir, aber meine Klinge ist nicht wählerisch.','Sag an, {D}, was zahlst du dafür, dass wir einfach weitergehen?','Wir haben seit vier Tagen keinen erschlagen, die Männer werden langsam unleidlich.','Deine Kämpfer sind Ware, meine sind Werkzeug, mal sehen, was länger hält.','Ich zähle Köpfe, Lanista, und bei euch komme ich auf einen guten Tageslohn.','Kein böses Blut, nur Geschäft, und das Geschäft ist heute Gewalt.'],
 raeuber:['Schöne Schule, schweres Tor, volle Truhen – drei Dinge, die mir sofort gefallen.','Her mit dem Wegzoll, {D}, die Straße vor deinem Tor gehört seit heute uns.','Wir nehmen nur, was glänzt, und lassen stehen, was schreit.','Du hast da hübsche Waffen, die würden in meinem Sack noch hübscher aussehen.','Gib uns einen Krug und einen Beutel, dann vergessen wir, wo du wohnst.','Ich hab schon reichere Leute ärmer gemacht, als du es je sein wirst.','Mach das Tor ruhig weiter auf, dann müssen wir es nicht tun.','Deine Stiefel gefallen mir, Lanista, welche Größe hast du?'],
 irre:['Drei Raben haben mir gesagt, hier gäbe es Bier, Blut und schlechte Entscheidungen.','Ich habe geträumt, dein Tor frisst mich, also bin ich gekommen, um zurückzubeißen.','Mein Schwert hat Hunger, und es mag keine Rüben.','Bist du echt oder redet schon wieder nur der Sand mit mir?','Wir suchen meinen Kopf, ich hatte ihn gestern noch.','Die Toten unter deinem Hof kratzen, hörst du das nicht, {D}?','Ich tausche dir ein Ohr gegen einen Krug, es ist nicht mal meins.','Heute ist ein guter Tag zum Sterben, ich weiß nur noch nicht, für wen.']
};
const say={
 nett:['Kommt rein, der erste Krug geht auf mich.','Setzt euch in den Schatten, hier schlägt keiner einen müden Mann.','Wasser, Brot und ein Platz am Feuer, mehr braucht ihr nicht zu fragen.','Ihr seht aus, als hättet ihr die halbe Straße gefressen, trinkt erst mal.','Wer friedlich kommt, kriegt bei mir einen vollen Becher.','Legt die Klingen ab und die Beine hoch, heute wird hier nur gesoffen.','Ein Krug für jeden, und danach erzählt ihr mir, was ihr gesehen habt.','Bleibt eine Weile, mein Schmied ist schlimmer als ihr alle zusammen.'],
 frage:['Was wollt ihr hier?','Wer hat euch geschickt, und was hat er dafür bezahlt?','Redet schon, ich hab nicht den ganzen Tag für Gesindel.','Sucht ihr Arbeit, Ärger oder bloß einen Platz zum Sterben?','Und was genau soll mich an euch beeindrucken?','Sagt mir einen Grund, warum ich das Tor nicht einfach zuschlage.','Ihr steht vor meinem Tor, also erklärt mir, warum ihr noch steht.','Ich höre viel Maul und wenig Anliegen, also raus damit.'],
 weg:['Verpisst euch von meinem Tor.','Schert euch fort, bevor ich die Hunde und den Schmied loslasse.','Hier gibt es nichts für Landstreicher, zieht weiter.','Dreht um, solange ihr noch alle Zähne im Maul habt.','Mein Hof ist kein Rastplatz für räudiges Pack.','Verschwindet, ihr verpestet mir die Luft.','Weiter, Gesindel, ich füttere keine Köter, die nicht mir gehören.','Macht, dass ihr wegkommt, sonst gieße ich euch mit der Jauche vom Hof.'],
 kampf:['{NN} im Hinterhof, wenn ihr euch traut.','Große Worte, kleiner Haufen – {NN}, jetzt gleich.','Meine Männer machen Hackfleisch aus euch, {NN}.','Dann zeigt, was ihr könnt, {NN}, bis einer liegen bleibt.','Ich hab Sand, ihr habt Blut, {NN} und wir bringen beides zusammen.','{NN}, ihr feigen Hunde, oder haltet endlich das Maul.','Maul halten, Waffen ziehen, {NN} hinter dem Haus.','Ihr wollt Ärger, ihr kriegt ihn, {NN} und keine Gnade.']
};
// Erwiderungen: F = es kommt zum Kampf, N = sie ziehen ab bzw. bleiben friedlich.
const reply={
 freundlich:{nett:{N:['Bei allen Göttern, endlich ein Ludus, der sein Bier nicht nur an seine Pfeifen verschwendet.','Auf dich, Lanista, möge dein Sand nass bleiben und dein Krug voll.','So spricht ein Mann, bei dem ich gern noch einmal vorbeikomme.'],F:['Trinken wir erst, und dann prügeln wir uns zum Spaß, wie anständige Leute.']},frage:{N:['Nur einen Schluck und ein freundliches Wort, mehr hatten wir nicht im Sinn.','Nichts, was dich Schlaf kostet, wir ziehen gleich weiter.'],F:['Ein kleines Kräftemessen unter Freunden, wenn du schon so fragst.']},weg:{N:['Schon gut, schon gut, behalt dein Tor und deine schlechte Laune.','Schade, ich hätte dich für gastlicher gehalten, aber wir gehen ja schon.'],F:['Für so viel Unhöflichkeit gibt es bei uns eins aufs Maul, {D}.']},kampf:{F:['Na schön, aber danach gibst du einen aus, wenn du noch stehen kannst.','Ein ehrlicher Tanz vor dem Bier, das lasse ich mir gefallen.'],N:['Heute nicht, Alter, wir haben mehr Durst als Zorn.']}},
 arrogant:{nett:{N:['Dein Fusel schmeckt sicher wie dein Hof aussieht, aber ich lasse mich ausnahmsweise herab.','Gnädig von dir, {D}, ich werde es bei Gelegenheit vergessen.'],F:['Ich trinke nicht mit dem Gesinde, ich lasse es bluten.']},frage:{N:['Was ich will, verstehst du ohnehin nicht, also spare ich mir die Mühe und gehe.','Ich wollte sehen, ob es sich lohnt, und es lohnt sich nicht.'],F:['Ich will dir zeigen, wie ein richtiger Kämpfer aussieht, hol deine Schüler.']},weg:{F:['Niemand schickt mich fort wie einen Hund, am wenigsten ein {D} wie du.','Für diesen Ton lasse ich deine Männer im eigenen Dreck knien.'],N:['Mit Vergnügen, ich habe mir hier ohnehin schon die Sandalen ruiniert.']},kampf:{F:['Endlich ein Satz, der nicht nach Stall riecht, hol deine Männer.','Du forderst mich, wie rührend, ich werde es kurz machen.'],N:['Ich mache mir an deinem Pöbel nicht die Klinge stumpf.']}},
 aggressiv:{nett:{F:['Sauf dein Bier allein, ich bin zum Zuschlagen hier und nicht zum Kuscheln.','Dein Krug kann warten, erst will ich hören, wie deine Männer quieken.'],N:['Na gut, ein Krug, aber sieh mich dabei nicht so an.']},frage:{F:['Was ich will, ich will einem von deinen die Zähne ins Hirn treiben.','Frag nicht so blöd, hol Männer, die bluten können.'],N:['Ich wollte Streit, aber du bist mir zu langweilig dafür.']},weg:{F:['Sag das noch einmal, wenn dein Maul voll Sand ist, {D}.','Ich gehe erst, wenn hier einer liegt, und der bin nicht ich.'],N:['Leck mich, dein {S} ist den Tritt nicht wert.']},kampf:{F:['Endlich redest du weniger Scheiße, hol deine Besten raus.','Genau das wollte ich hören, ich breche ihnen zuerst die Beine.'],N:['Heute hast du Glück, mir ist der Arm noch taub vom letzten.']}},
 grossmaul:{nett:{N:['Siehst du, sogar du erkennst einen Helden, wenn er vor dir steht.','Ein Krug für mich, und für meine Geschichten brauchst du ein ganzes Fass.'],F:['Erst zeige ich deinen Hanswursten, was ein Schlag ist, dann trinke ich dein Bier.']},frage:{N:['Ich wollte nur sehen, ob hier einer meiner würdig ist, und nein.','Bewundert werden, was sonst, aber dein Haufen hat keinen Geschmack.'],F:['Deinen Leuten beibringen, wie man verliert, das will ich.']},weg:{F:['Mich jagt keiner fort, ich bin schon aus besseren Schulen geflogen, mit Fäusten.','Dafür haue ich deinem Besten die Ohren vom Kopf, {D}.'],N:['Ich gehe, weil ich will, und merk dir, dass ich fast geblieben wäre.']},kampf:{F:['Ha, ich brauche keine {n}, ich brauche nur eine Hand und gute Laune.','Sag deinen Männern, sie sollen vorher beten, ich bin heute in Form.'],N:['Würde ich ja, aber mein Schwertarm ist verliehen und kommt erst morgen wieder.','Ich kämpfe nie vor dem Mittagessen, das wäre unfair für euch.']}},
 feige:{nett:{N:['Oh, das nehmen wir gern an, und wir setzen uns ganz nah an die Tür.','Ein Krug, ja, und du kostest ihn bitte zuerst.'],F:['Ein Hinterhalt mit Bier, das kenne ich, drauf, Männer, bevor sie es tun.']},frage:{N:['Nichts, gar nichts, wir haben uns nur im Tor geirrt.','Wir wollten fragen, wo es zur nächsten Schule geht, die kleiner ist.'],F:['Eigentlich wollten wir dich einschüchtern, und jetzt müssen wir es wohl durchziehen.']},weg:{N:['Wir gehen ja schon, und zwar aus freien Stücken und sehr schnell.','Behalt deinen {S}, für so etwas ruiniere ich mir nicht die guten Sandalen.','Du hast Glück, dass ich heute meinen friedlichen Tag habe.'],F:['Das lasse ich mir nicht bieten, glaube ich, oder, Männer?']},kampf:{N:['Ich würde ja, aber mein Kamerad hier hat es im Kreuz.','Gegen Bewaffnete, bist du irre, wir dachten an etwas mit weniger Eisen.','Ein andermal, wenn du allein bist und schläfst.'],F:['Verdammt, jetzt haben es alle gehört, also gut, aber nicht ins Gesicht.']}},
 ehrenhaft:{nett:{N:['Ich danke dir, Lanista, und ich trinke auf dein Haus, bevor ich weiterziehe.','Gastrecht ist heilig, heute bleibt meine Klinge in der Scheide.'],F:['Erst der Kampf, dann der Krug, so halte ich es seit jeher.']},frage:{F:['Einen ehrlichen Kampf, {NN}, und danach scheiden wir ohne Groll.','Ich will wissen, ob deine Männer halten, was man von ihnen sagt.'],N:['Nur ein Wort unter Kämpfern, und das habe ich nun gehabt.']},weg:{N:['Wie du willst, ich dränge mich keinem auf, der keinen Mut hat.','Dann gehe ich, aber man wird erfahren, dass dein Tor verschlossen blieb.'],F:['Wer mich so abweist, hat etwas zu verbergen, also ziehe ich blank.']},kampf:{F:['So spricht ein Mann, ich nehme an und kämpfe ohne Hinterlist.','Bei meinem Eid, {NN}, und wer fällt, fällt mit Ehre.','Gut gesprochen, ruf deine Besten, ich warte im Hof.'],N:['Du bist zornig, und im Zorn kämpfe ich mit niemandem.']}},
 hinterlistig:{nett:{N:['Wie großzügig, ich merke mir genau, wo der Keller ist.','Gern, und keine Sorge, wir zählen deine Wachen nur aus Gewohnheit.'],F:['Wer so freundlich ist, hat Angst, und Angst mache ich mir gern zunutze.']},frage:{N:['Gar nichts, Lanista, wir haben schon gesehen, was wir sehen wollten.','Nur schauen, und schauen kostet nichts, noch nicht.'],F:['Ich wollte wissen, wie schnell deine Männer sind, und das klären wir jetzt.']},weg:{N:['Wir gehen, und wir kommen wieder, wenn du nicht hinsiehst.','Schlaf gut, {D}, und prüf heute Nacht ruhig zweimal den Riegel.'],F:['Solche Worte zahlt man bei mir mit Zinsen, und ich nehme sie sofort.']},kampf:{F:['Wie plump, aber gut, im Hinterhof sieht wenigstens keiner, was ich mit ihnen mache.','Abgemacht, und beschwer dich nachher nicht über meine Art zu kämpfen.'],N:['Von vorn, bei Tageslicht, ich bin doch nicht blöd.','Ich kämpfe, wann ich will, und du wirst nicht dabei sein, wenn es losgeht.']}},
 veteran:{nett:{N:['Na endlich einer mit Verstand, schenk ein und halt mir die Jungen vom Leib.','Auf die Toten, Lanista, die hatten wenigstens Ruhe.','Dafür erzähle ich dir, wie man in Capua einen Löwen bestochen hat.'],F:['Erst zeige ich deinem Welpen, wie man fällt, dann saufen wir.']},frage:{N:['Bier, einen Hocker und keine dummen Fragen, in dieser Reihenfolge.','Ich wollte sehen, ob die Jugend noch was taugt, und ich bin nicht überrascht.'],F:['Einem deiner Grünschnäbel Manieren beibringen, ehe mein Knie ganz aufgibt.']},weg:{N:['Ich bin schon aus besseren Löchern geworfen worden, {D}, und zwar von Männern.','Wie du meinst, in meinem Alter streitet man nicht mehr um jede Schwelle.'],F:['Vorlaut, das treibe ich dir mit dem Knauf aus, Junge.']},kampf:{F:['Na dann, ich hab schon Schlimmeres überlebt als deine Schüler.','Meinetwegen, aber weck mich, falls einer von deinen was Interessantes macht.'],N:['Spar dir den Atem, ich kämpfe nicht mehr umsonst und schon gar nicht nüchtern.']}},
 soeldner:{nett:{N:['Bier ist auch eine Währung, heute nehmen wir sie an.','Freibier, da stecke ich die Klinge weg, das rechnet sich.'],F:['Nett von dir, aber ein Krug bezahlt keine vier Tage Marsch, wir holen uns den Rest.']},frage:{F:['Gold oder Blut, und Gold sehe ich bei dir keines.','Arbeit, und wenn es keine gibt, machen wir uns welche.'],N:['Nur den Preis schätzen, und du bist den Aufwand nicht wert.']},weg:{F:['Für Beleidigungen berechne ich doppelt, und kassiert wird sofort.','Du wirfst keinen raus, der vom Rauswerfen lebt, {D}.'],N:['Kein Gold, kein Kampf, wir gehen dahin, wo sich das Töten lohnt.']},kampf:{F:['Abgemacht, {NN}, und was am Boden liegt, gehört uns.','Endlich ein klares Angebot, meine Männer arbeiten schnell.'],N:['Umsonst sterben nur Dummköpfe, zahl oder vergiss es.']}},
 raeuber:{nett:{N:['Ein Krug geschenkt, das ist fast so gut wie gestohlen.','Na schön, heute plündern wir nur dein Fass.'],F:['Wer Bier verschenkt, hat mehr im Keller, also holen wir uns alles.']},frage:{F:['Deinen Beutel, deine Stiefel und was sonst noch klimpert.','Wegzoll, und wer nicht zahlt, zahlt in Zähnen.'],N:['Wir wollten nur wissen, ob sich der Einbruch lohnt, und das tut er nicht.']},weg:{F:['Erst zahlst du, dann gehen wir, so herum läuft das, {D}.','Mit leeren Händen ziehe ich nicht ab, also nehme ich mir deine Männer vor.'],N:['Schon gut, bei so vielen Klingen suchen wir uns einen fetteren Hof.']},kampf:{F:['Gern, den Toten nimmt man am leichtesten die Stiefel ab.','Gut, dann holen wir uns die Beute eben auf die harte Tour.'],N:['Kämpfen, wenn nichts dabei herausspringt, für wie blöd hältst du mich?']}},
 irre:{nett:{N:['Bier, die Raben hatten recht, die Raben haben immer recht.','Ich trinke auf dein Tor, es hat mich doch nicht gefressen.'],F:['Dein Krug lügt, ich höre es blubbern, also schlage ich zu.']},frage:{N:['Ich weiß es nicht mehr, frag den Sand, der war dabei.','Meinen Kopf, aber du hast ihn auch nicht, ich gehe weiter suchen.'],F:['Mein Schwert will dich etwas fragen, und es fragt sehr laut.']},weg:{F:['Du schickst mich fort und meine Stimmen bleiben hier, das geht nicht gut aus.','Die Toten unter deinem Hof sagen, ich soll bleiben und dir wehtun.'],N:['Gut, ich gehe rückwärts, damit du nicht siehst, wie ich weine.','Dein Tor hat mich nie gemocht, ich verstehe das.']},kampf:{F:['Ja, ja, Blut, endlich spricht einer meine Sprache.','Ich zähle bis blau, dann fange ich an, und zwar mit dem Hübschesten.'],N:['Nicht heute, heute ist der Tag, an dem ich niemanden umbringe, glaube ich.']}}
};
// Kampfneigung je Persönlichkeit und Ton (0..1). Das Spiel entscheidet; die Texte folgen der Entscheidung.
const lean={freundlich:{nett:.03,frage:.1,weg:.25,kampf:.75},arrogant:{nett:.12,frage:.3,weg:.75,kampf:.85},aggressiv:{nett:.6,frage:.8,weg:.92,kampf:.97},grossmaul:{nett:.12,frage:.3,weg:.6,kampf:.6},feige:{nett:.03,frage:.08,weg:.08,kampf:.15},ehrenhaft:{nett:.1,frage:.6,weg:.2,kampf:.93},hinterlistig:{nett:.15,frage:.25,weg:.4,kampf:.55},veteran:{nett:.06,frage:.2,weg:.35,kampf:.75},soeldner:{nett:.2,frage:.65,weg:.75,kampf:.9},raeuber:{nett:.2,frage:.65,weg:.7,kampf:.8},irre:{nett:.3,frage:.45,weg:.6,kampf:.7}};
function sample(id,salt){let h=2166136261;for(const c of id+'|'+salt)h=Math.imul(h^c.charCodeAt(0),16777619);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return (h>>>0)/4294967296;}
const choose=(list,id,salt)=>list[Math.floor(sample(id,salt)*list.length)];
function fill(text,g,salt){const n=g.size,addr=M.s.lanista?.lostArm?[...slots.D,'Einarm','Einarm','Stummelflügel']:slots.D;return text.replace(/\{D\}/g,()=>choose(addr,g.id,salt+'D')).replace(/\{S\}/g,()=>choose(slots.S,g.id,salt+'S')).replace(/\{NN\}/g,['Einer gegen einen','Zwei gegen zwei','Drei gegen drei'][n-1]||n+' gegen '+n).replace(/\{n\}/g,['einen','zwei','drei'][n-1]||n);}
const tones=['nett','frage','weg','kampf'];
function opener(g){return fill(choose(open[g.leader.personality]||open.grossmaul,g.id,'open'),g,'open');}
function options(g){return tones.map(tone=>({tone,text:fill(choose(say[tone],g.id,'say'+tone),g,'say'+tone)}));}
function chance(g,tone){const kind=lean[g.leader.personality]||lean.grossmaul,l=g.leader;return Math.min(.98,Math.max(.02,kind[tone]+((l.aggression??50)-50)/500+((l.fightWill??50)-50)/500-(tone==='kampf'||tone==='weg'?(50-(l.courage??50))/600:0)-(tone==='nett'?(l.sympathy??0)/400:0)));}
function decide(g,tone){return sample(g.id,'roll'+tone)<chance(g,tone)?'FIGHT':'NO_FIGHT';}
function answer(g,tone,outcome){const cell=(reply[g.leader.personality]||reply.grossmaul)[tone],key=outcome==='FIGHT'?'F':'N',list=cell[key]?.length?cell[key]:cell.F||cell.N;return fill(choose(list,g.id,'reply'+tone+key),g,'reply'+tone);}
M.wandererTalk={tones,opener,options,decide,chance,answer,texts:{open,say,reply,slots}};
})();
