'use strict';
(()=>{const M=window.MG,S=M.s,A=M.army,C=M.clamp,formats=[1,2,3,5,10,15,20,30,50,75,100];
S.world??={version:1,schools:[],people:{},teams:{},weapons:{},names:{},lastDay:S.day,log:[],spyReports:[]};const W=S.world;
// Existing full saves migrate lazily. New IDB writes update only affected schools,
// together with the main profile in one atomic transaction.
const profileKey=window.GladiatorProfiles?.key||'mini-gladiator-manager-v2';
W.schools=W.schools.map(s=>{if(!s.ref)return s;const raw=window.MGSave?.get(profileKey+':npc:'+s.ref);if(!raw)throw Error('Die gespeicherte Schule '+s.ref+' konnte nicht geladen werden.');return JSON.parse(raw);});
const dirtySchools=new Set(W.schools.map(s=>s.id));
M.worldSerialize=key=>{if(S.battle?.challengeData?.schoolId)dirtySchools.add(S.battle.challengeData.schoolId);if(window.MGSave?.error)for(const s of W.schools)dirtySchools.add(s.id);const entries=W.schools.filter(s=>dirtySchools.has(s.id)).map(s=>[key+':npc:'+s.id,JSON.stringify(s)]);dirtySchools.clear();return {entries,root:{...S,world:{...W,schools:W.schools.map(s=>({ref:s.id}))}}};};

const teamIds=()=>{for(const p of S.teamPlans){p.id??=M.uid();W.teams[p.id]={id:p.id,name:p.name,schoolId:'player',active:true};}};teamIds();
const schoolNames=['Ludus des Strohs','Die Staubfüchse','Hof der Kiesel','Ludus Tiberius','Die Kupferwölfe','Sandbrüder','Ludus Falco','Die roten Schilde','Haus der Esche','Ludus Aquila','Die bronzenen Löwen','Ludus Aurelius','Die schwarzen Lanzen','Haus der Eichen','Ludus Ferrum','Marswache','Ludus Corvinus','Die purpurnen Adler','Ludus Vindex','Die eiserne Sonne','Ludus Invictus','Hüter des Triumphs','Ludus Imperialis','Die goldenen Prätorianer','Haus der Titanen','Ludus Aeternus','Die unsterbliche Legion','Ludus Solis','Thron des Mars','Die letzte Krone'];
function school(id){return W.schools.find(x=>x.id===id);}function person(id){return S.roster.find(g=>g.id===id)||S.trainers.find(g=>g.id===id)||W.schools.flatMap(x=>x.roster).find(g=>g.id===id)||W.people[id];}
function social(g){g.social??={bonds:{},rivals:{},former:[],mentor:null,students:[],events:[],courage:g.traits.includes('Feige')?0:g.traits.includes('Mutig')?100:50,originTraits:[...g.traits]};return g.social;}
function remember(g,sid=g.schoolId||(g.enemy?'historic-opponents':'player')){const old=W.people[g.id]||{};W.people[g.id]={...old,id:g.id,name:g.name,schoolId:sid,dead:!!g.dead,retired:!!g.retired,day:g.dead?(old.day||S.day):old.day};}
function event(g,text){const so=social(g);so.events.unshift({day:S.day,text});if(so.events.length>150)so.events.length=150;}
function log(text){W.log.unshift({day:S.day,text});W.log.length=Math.min(80,W.log.length);}
function items(g){return [M.gear(g,'weapon'),M.gear(g,'secondary'),M.gear(g,'shield'),...M.armorItems(g)].filter(Boolean);}
function weaponHistory(i){if(!i||i.kind!=='weapon')return null;i.story??={acquired:S.day,owners:[],owner:null,fights:0,wins:0,kills:0,stage:0,name:null,events:[]};return i.story;}
function ownership(i,g){const h=weaponHistory(i);if(!h)return;if(g&&h.owner!==g.id){if(!h.owners.some(o=>o.id===g.id))h.owners.push({id:g.id,name:g.name,day:S.day});if((h.owner||h.lastOwner)&&(h.owner||h.lastOwner)!==g.id){h.events.unshift({day:S.day,text:'Von '+(person(h.owner||h.lastOwner)?.name||'einem früheren Träger')+' an '+g.name+' weitergegeben.',from:h.owner||h.lastOwner,to:g.id});h.events.length=Math.min(100,h.events.length);}h.owner=g.id;}else if(!g){if(h.owner)h.lastOwner=h.owner;h.owner=null;}}
function legendaryName(i){const families={blade:['Urteil','Zorn','Klinge','Schwur','Glanz','Schatten'],axe:['Spalter','Zorn','Eisenurteil','Ruf','Sturm'],spear:['Spitze','Stoß','Lanze','Wächter','Stachel'],hammer:['Donner','Brecher','Hammer','Faust','Urteil'],bow:['Sehne','Flüstern','Regen','Blick','Flug'],crossbow:['Bolzen','Eisenhagel','Blick','Urteil','Donner'],net:['Fessel','Netz','Griff','Schleier','Bann']},d=i.def,f=d==='net'?'net':d==='crossbow'?'crossbow':d==='bow'?'bow':['axe','doubleaxe','throwaxe'].includes(d)?'axe':['spear','trident','halberd','javelin'].includes(d)?'spear':['hammer','mace','club'].includes(d)?'hammer':'blade',ends=['des Mars','der Morgenröte','des Triumphs','der Wölfe','der letzten Legion','des Adlers','des Saturn','der Ewigkeit','der Dämmerung','des Kaisers','des Sieges','der Prätorianer','des Schicksals','der Asche','der Titanen','des Nordens','der Eroberer','der eisernen Sonne'];let name=M.pick(families[f])+' '+M.pick(ends),base=name,n=2;while(W.names[name])name=base+' · '+n++;W.names[name]=i.id;return name;}
function addWeaponKill(i,g,victim,extra=''){const h=weaponHistory(i);if(!h)return;ownership(i,g);h.kills++;h.victims??={};if(victim?.id){const v=h.victims[victim.id]??={id:victim.id,name:victim.name,day:S.day,ownerId:g.id,ownerName:g.name};v.day=S.day;}if(h.kills===1)h.firstKill=S.day;const stage=h.kills>=1000?2:h.kills>=100?1:0;if(stage>h.stage){h.stage=stage;h.name??=legendaryName(i);h[stage===1?'hundredDay':'thousandDay']=S.day;h.events.unshift({day:S.day,text:stage===1?'100. Kill · Legendenstufe I':'1.000. Kill · Legendenstufe II'});log(h.name+' erreicht Legendenstufe '+stage+'.');}if(extra||victim?.fame>1000)h.events.unshift({day:S.day,text:extra||'Besiegte den berühmten Gladiator '+victim.name+'.',victimId:victim?.id});h.events.length=Math.min(h.events.length,100);}
function resolveWeapon(id){if(!id)return null;return S.inventory.find(i=>i.id===id)||W.schools.flatMap(s=>s.roster).flatMap(items).find(i=>i.id===id)||W.weapons[id];}
function syncOwners(){const owners=new Map();for(const g of [...S.roster,...S.trainers])for(const i of items(g))owners.set(i.id,g);for(const i of S.inventory)ownership(i,owners.get(i.id));}
function gearNpc(g,q){const d=g.role==='Fernkämpfer'?M.pick(['bow','crossbow']):g.role==='Assassine'?M.pick(['dagger','short','long']):M.pick(['gladius','spear','mace','hammer']);g.enemyGear={weapon:g.role==='Fernkämpfer'?M.makeItem('weapon',d,q):null,secondary:M.makeItem('weapon',g.role==='Fernkämpfer'?'dagger':d,q),shield:g.role==='Soldat'&&!M.definition(M.makeItem('weapon',d,q)).twoHand?M.makeItem('shield','roundshield',q):null,armor:{}};for(const def of M.armorDefs)g.enemyGear.armor[def.id]=M.makeItem('armor',def.id,q,g.role==='Soldat'?'metal':'leather');for(const i of items(g))ownership(i,g);}
function recruitNpc(s){const mean=s.base,g=M.makeGladiator(0,true);g.schoolId=s.id;g.enemy=true;g.role=M.roles[s.recruits++%3];for(const k in g.stats){g.stats[k]=C(M.bernoulliValue(mean),1,99);g.caps.stats[k]=C(Math.max(g.stats[k],mean+5+M.rnd(0,8)),1,100);}for(const k in g.mastery){g.mastery[k]=C(M.bernoulliValue(mean),1,99);g.caps.weapons[k]=C(Math.max(g.mastery[k],mean+8),1,100);}for(const k in g.moves){g.moves[k]=C(M.bernoulliValue(mean),1,99);g.caps.moves[k]=Math.min(100,Math.max(g.moves[k],mean+8));}for(const [id,p] of Object.entries(g.body)){p.strength=C(M.bernoulliValue(mean),1,99);p.agility=C(M.bernoulliValue(mean),1,99);g.caps.body[id]={strength:Math.min(100,p.strength+10),agility:Math.min(100,p.agility+10)};}g.stats.morale=C(40+mean*.5,1,100);g.caps.stats.morale=Math.max(g.caps.stats.morale,g.stats.morale);g.fame=Math.floor(mean*12);g.fights=Math.floor(mean*2);g.wins=Math.floor(g.fights*.5);g.birthday=S.day;g.ageAtJoin=g.age;gearNpc(g,C(Math.floor((mean-4)/15),0,6));s.roster.push(g);remember(g,s.id);return g;}
function fighting(g){return !g.dead&&!g.retired&&M.health(g)>55&&g.blood>50&&!['head','neck','chest'].some(k=>g.body[k].missing)&&M.limb(g,['lt','rt','lsh','rsh'])>.35;}
function rebuild(s){dirtySchools.add(s.id);const ready=s.roster.filter(fighting).sort((a,b)=>M.power(b)-M.power(a));for(const t of s.teams){const chosen=[],style=s.style||'Ausgeglichen',order=style==='Assassinen'?['Assassine','Assassine','Soldat','Fernkämpfer']:style==='Fernkämpfer'?['Soldat','Fernkämpfer','Fernkämpfer','Assassine']:style==='Soldaten'?['Soldat','Soldat','Assassine','Fernkämpfer']:['Soldat','Assassine','Fernkämpfer'];for(let i=0;i<t.size;i++){const g=ready.find(g=>!chosen.includes(g)&&g.role===order[i%order.length])||ready.find(g=>!chosen.includes(g));if(g)chosen.push(g);}t.members=chosen.map(g=>g.id);t.leader=t.members[0]||null;W.teams[t.id]={id:t.id,name:t.name,schoolId:s.id,active:true};}s.average=s.roster.filter(g=>!g.dead&&!g.retired).reduce((n,g)=>n+M.power(g),0)/Math.max(1,s.roster.filter(g=>!g.dead&&!g.retired).length);s.strength=Math.round(s.average);s.best=Math.round(ready.slice(0,3).reduce((n,g)=>n+M.power(g),0)/Math.max(1,Math.min(3,ready.length)));}
if(!W.schools.length){const batching=M.batchSaving;M.batchSaving=true;for(let n=0;n<30;n++){const s={id:M.uid(),name:schoolNames[n],style:['Ausgeglichen','Soldaten','Assassinen','Fernkämpfer'][n%4],base:4+n*93/29,rankPoints:100+n*100,fame:n*n*25,wins:n*4,losses:n*2,recruits:0,roster:[],teams:formats.map((size,i)=>({id:M.uid(),name:'Kohorte '+(i+1),size,members:[],leader:null})),history:[]};for(let j=0;j<18;j++)recruitNpc(s);rebuild(s);W.schools.push(s);dirtySchools.add(s.id);}M.batchSaving=batching;log('30 Gladiatorenschulen sind in der Arena bekannt.');}
for(const s of W.schools)for(const size of formats)if(!s.teams.some(t=>t.size===size)){const t={id:M.uid(),name:size+'er-Aufgebot',size,members:[],leader:null,mustered:false};s.teams.push(t);W.teams[t.id]={id:t.id,name:t.name,schoolId:s.id,active:true};dirtySchools.add(s.id);}
function muster(sid,size){const s=school(sid),t=s?.teams.find(t=>t.size===size);if(!t||size<=15||t.mustered||S.battle)return;t.mustered=true;s.capacity=Math.max(s.capacity||18,size+5);const active=s.roster.filter(g=>!g.dead&&!g.retired).length;for(let i=active;i<s.capacity;i++)recruitNpc(s);rebuild(s);M.persist();}
for(const g of [...S.roster,...S.trainers]){social(g);remember(g);}syncOwners();for(const a of S.battle?.actors||[]){if(a.g.schoolId){const s=school(a.g.schoolId),i=s?.roster.findIndex(g=>g.id===a.id);if(i>=0)s.roster[i]=a.g;}}
function teamRoster(s,t){return t.members.map(id=>s.roster.find(g=>g.id===id)).filter(Boolean);}function rivalLocation(r){const s=school(r.schoolId),g=s?.roster.find(g=>g.id===r.id)||W.people[r.id];return {school:s,name:g?.name||r.name,dead:!!g?.dead,retired:!!g?.retired,teams:s?.teams.filter(t=>t.members.includes(r.id))||[]};}
function bond(g,id){return social(g).bonds[id]?.value||0;}function bondName(value){return value>=80?'Vertrauter Kampfgefährte':value>=50?'Enger Freund':value>=25?'Freund':'Kamerad';}
function rivalry(g,foe,reason,force=false){if(!foe?.schoolId||g.dead)return;const so=social(g),existing=so.rivals[foe.id];if(existing){existing.grievances=(existing.grievances||1)+1;return;}if(!force&&M.rng()>.35)return;const loc=school(foe.schoolId),t=loc?.teams.find(t=>t.members.includes(foe.id));so.rivals[foe.id]={id:foe.id,name:foe.name,schoolId:foe.schoolId,teamId:t?.id,reason,day:S.day,encounters:1,wins:0,losses:0};event(g,'Erzfeind: '+foe.name+' · '+reason);}
function onHarm(victim,attacker,kind){const b=S.battle;if(!b||b.benchmark||!b.challengeData?.schoolId)return;if(attacker){victim.lastAttackerId=attacker.id;victim.lastAttacker=attacker.g.name;}if(victim.team===0&&attacker?.team===1){const reason=(kind==='death'?'Tötete ':kind==='down'?'Schlug nieder: ':'Verletzte schwer: ')+victim.g.name+' an Tag '+S.day+'.';if(kind!=='death')rivalry(victim.g,attacker.g,reason);for(const ally of b.actors.filter(a=>a.team===0&&a.id!==victim.id&&!a.g.dead)){const closeness=bond(ally.g,victim.id);if(closeness>=25){rivalry(ally.g,attacker.g,reason,kind==='death'&&closeness>=50);if(kind==='death'){event(ally.g,'Freund '+victim.g.name+' starb durch '+attacker.g.name+'.');ally.g.stats.morale=Math.max(1,ally.g.stats.morale-(closeness>=50?7:3));social(ally.g).griefUntil=S.day+7;social(ally.g).courage=Math.max(0,social(ally.g).courage-(ally.g.traits.includes('Aggressiv')?0:1));}}}}}
function onDeath(victim,killer,cause){const b=S.battle;if(!b||b.benchmark)return;const damageOwner=victim.lastAttackerId;onHarm(victim,killer,'death');remember(victim.g);W.people[victim.id].social=M.copy(social(victim.g));W.people[victim.id].cause=cause;if(!killer)return;const so=social(killer.g),r=so.rivals[victim.id];let revenge='';if(r&&!r.completed){r.completed=S.day;so.former.push({...r,completedBy:killer.id});delete so.rivals[victim.id];killer.revengeBonus=.5;revenge='Tötete Erzfeind '+victim.g.name+'.';event(killer.g,'Rache vollendet: '+victim.g.name+'.');log(killer.g.name+': Rache vollendet.');}const w=damageOwner===killer.id&&Object.hasOwn(victim,'lastDamageWeaponId')&&!b.finale?resolveWeapon(victim.lastDamageWeaponId):M.weapon(killer).item;addWeaponKill(w,killer.g,victim.g,revenge);}
function startStory(b){if(b.benchmark||!b.challengeData?.schoolId)return;teamIds();b.playerTeamId=A.plan().id;syncOwners();const t=school(b.challengeData.schoolId)?.teams.find(t=>t.id===b.challengeData.teamId);b.leaders[1]=t?.leader||b.leaders[1];for(const a of b.actors){social(a.g);remember(a.g);a.storyWeapons=[];const team=b.actors.filter(x=>x.team===a.team);a.friendBonus=Math.min(.02,Math.max(0,...team.filter(x=>x.id!==a.id).map(x=>bond(a.g,x.id)))/5000);const vets=team.filter(x=>x!==a&&x.g.fights>=25&&x.g.stats.experience>=45&&x.g.wins>=8);const veteran=vets.sort((x,y)=>y.g.stats.experience-x.g.stats.experience)[0];a.mentorBonus=veteran&&veteran.g.stats.experience>a.g.stats.experience&&a.g.fights<30?C((veteran.g.stats.experience-a.g.stats.experience)/500,.05,.15):0;a.mentorId=veteran?.id;for(const i of items(a.g)){ownership(i,a.g);const h=weaponHistory(i);if(h){h.fights++;a.storyWeapons.push(i.id);}}for(const r of Object.values(social(a.g).rivals)){if(b.actors.some(x=>x.id===r.id)){r.encounters++;b.log.unshift({time:0,text:a.g.name+' hat Erzfeind '+r.name+' entdeckt.'});}}}}
function finishStory(b,winner){if(b.challengeData?.schoolId)dirtySchools.add(b.challengeData.schoolId);if(b.benchmark||!b.challengeData?.schoolId)return;const s=school(b.challengeData.schoolId);if(s){if(winner===1){s.wins++;s.rankPoints+=20;s.fame+=15;}else if(winner===0){s.losses++;s.rankPoints=Math.max(0,s.rankPoints-12);}}
 for(const a of b.actors){const g=a.g,so=social(g),won=a.team===winner;for(const id of a.storyWeapons||[]){const h=weaponHistory(resolveWeapon(id));if(h&&won)h.wins++;}if(a.team===0&&winner===1){so.encounters??={};for(const foe of b.actors.filter(x=>x.team===1)){const losses=so.encounters[foe.id]=(so.encounters[foe.id]||0)+1;if(losses>=3)rivalry(g,foe.g,'Nach '+losses+' Niederlagen gegen '+foe.g.name+' an Tag '+S.day+'.',true);}}if(a.team===1){if(!g.dead){g.wins+=won?1:0;g.losses+=won?0:1;g.fatigue=C(g.fatigue+18+b.time/18,0,100);g.fame+=won?12:3;M.applyLearningBonus(a);}for(const p of Object.values(g.body))p.bleed=0;}
 for(const mate of b.actors.filter(x=>x.team===a.team&&x.id!==a.id)){const rel=so.bonds[mate.id]??={id:mate.id,name:mate.g.name,value:0,shared:0};rel.shared++;if(!g.dead&&!mate.g.dead)rel.value=C(rel.value+.6+(won?.7:0)+Math.min(.3,(a.blocks+a.damage/300)*.03),0,100);if(a.mentorId===mate.id&&rel.shared>=8){so.mentor=mate.id;const teacher=social(mate.g);if(!teacher.students.includes(g.id))teacher.students.push(g.id);}}
 for(const r of Object.values(so.rivals))if(b.actors.some(x=>x.id===r.id)){if(won)r.wins++;else if(winner>=0)r.losses++;}
 if(!g.dead){const old=so.courage;so.courage=C(old+(won?1.2:.1)+(a.mentorBonus?.2:0)+(M.health(g)<65?.15:0),0,100);if(so.originTraits.includes('Feige')){const states=['Feige','Unsicher','Vorsichtig','Gefestigt','Mutig'],stage=Math.min(4,Math.floor(so.courage/25)),prev=states.find(x=>g.traits.includes(x));if(prev!==states[stage]){g.traits=g.traits.filter(x=>!states.includes(x));g.traits.push(states[stage]);event(g,'Durch Kampferfahrung: '+states[stage]+'.');}}if(won&&g.stats.teamwork>65&&Object.values(so.bonds).filter(r=>r.value>=50).length>=2&&!g.traits.includes('Teamspieler')&&g.fights>=60){g.traits.push('Teamspieler');event(g,'Aus gemeinsamen Kämpfen erwuchs Teamgeist.');}}
 if(!g.dead&&Object.values(so.bonds).some(r=>r.value>=25)){M.addLearning(g,'stats','teamwork',.005);}remember(g);
 }if(s)rebuild(s);}
function socialPriority(a,t){if(!S.battle?.challengeData?.schoolId)return 0;const so=a.g.social;let bonus=so?.rivals[t.id]?35:0;const friend=S.battle.actors.find(x=>x.id===t.target&&x.team===a.team&&!x.down);if(friend)bonus+=Math.min(30,(so?.bonds[friend.id]?.value||0)*.3);return bonus;}
function beforeFinish(b,w){for(const a of b.actors)if(!a.g.dead){a.xpMultiplier=(a.xpMultiplier||1)+(a.mentorBonus||0)+(a.revengeBonus||0);}finishStory(b,w);}
function lootTransfer(item,original,b){if(!b.challengeData?.schoolId)return;dirtySchools.add(b.challengeData.schoolId);item.id=original.id;for(const a of b.actors.filter(a=>a.team===1)){const eg=a.g.enemyGear;for(const k of ['weapon','secondary','shield'])if(eg[k]?.id===original.id)eg[k]=null;for(const k in eg.armor)if(eg.armor[k]?.id===original.id)delete eg.armor[k];}ownership(item,null);const h=weaponHistory(item);if(h)h.events.unshift({day:S.day,text:'Als Beute zu '+S.schoolName+' gelangt.'});}
function prices(s,t){const league=C(Math.floor((s.base-4)/14),0,6),L=M.leagues[league];return {league,fee:Math.round(L.fee*t.size/3),reward:Math.round(L.reward*t.size/3*(.8+s.base/250))};}
function challenge(sid,tid){if(S.battle)return 'Es läuft bereits ein Kampf.';if(S.tournament){W.legacyTournament=M.copy(S.tournament);S.tournament=null;}const s=school(sid),t=s?.teams.find(t=>t.id===tid);if(!s||!t)return 'Team nicht gefunden.';if(t.size!==A.plan().size)return 'Wähle ein eigenes '+t.size+'er-Team.';if(teamRoster(s,t).length!==t.size||teamRoster(s,t).some(g=>!fighting(g)))return 'Dieses Team ist derzeit nicht einsatzbereit.';S.pendingChallenge={schoolId:s.id,teamId:t.id,name:s.name+' · '+t.name,...prices(s,t)};const error=M.beginFight('school',t.id);delete S.pendingChallenge;M.persist();return error;}
if(S.tournament&&!S.battle){W.legacyTournament=M.copy(S.tournament);S.tournament=null;}S.army.challenges=[];
const oldBegin=M.beginFight;M.beginFight=(type,id)=>{if(type==='school'&&S.pendingChallenge?.schoolId)return oldBegin(type,id);return 'Wähle eine gegnerische Schule und eines ihrer Teams in der Arena.';};
M.worldOpponent=()=>{const c=S.pendingChallenge;if(!c?.schoolId)return null;const s=school(c.schoolId),t=s?.teams.find(t=>t.id===c.teamId);return {name:s.name+' · '+t.name,champion:s.base>80,roster:teamRoster(s,t)};};
function npcDay(){if(W.lastDay>=S.day)return;W.lastDay=S.day;S.army.challenges=[];if(S.army.dayReport)S.army.dayReport.challenges=W.schools.reduce((n,s)=>n+s.teams.length,0);for(const s of W.schools){for(const g of s.roster){if(g.dead||g.retired)continue;g.ageAtJoin??=g.age;g.age=g.ageAtJoin+Math.floor((S.day-g.birthday)/365);if(!M.gear(g,'secondary')){const i=M.makeItem('weapon',g.role==='Assassine'?'dagger':g.role==='Fernkämpfer'?'short':'gladius',C(Math.floor((s.base-4)/15),0,6));g.enemyGear.secondary=i;ownership(i,g);}g.fatigue=Math.max(0,g.fatigue-12);g.blood=Math.min(100,g.blood+10);for(const p of Object.values(g.body)){p.bleed=0;p.pain=Math.max(0,p.pain-5);if(p.fracture&&--p.fracture.days<=0)delete p.fracture;if(p.internal&&--p.internal.days<=0)delete p.internal;if(!p.missing)p.hp=Math.min(100-p.chronic,p.hp+(p.fracture||p.internal?.8:2.5));p.grade=M.injuryGrade(p);}if(M.rng()<.025){const key=M.pick(['strength','condition','tactics','teamwork','dexterity']);M.addLearning(g,'stats',key,.06);}const w=M.gear(g,'secondary');if(w&&M.rng()<.2)M.addLearning(g,'weapons',w.def,.035);if((g.age>48||Object.values(g.body).filter(p=>p.missing).length>=2)&&M.rng()<.04){g.retired=true;remember(g);event(g,'In den Ruhestand verabschiedet.');}if(M.rng()<.004){const i=M.pick(items(g));if(i){i.durability=i.maxDurability;if(i.q<Math.min(6,Math.floor(s.base/15)))i.q++;}}}
 const active=s.roster.filter(g=>!g.dead&&!g.retired).length;if(active<(s.capacity||18))for(let n=active;n<Math.min(s.capacity||18,active+2);n++)recruitNpc(s);rebuild(s);}
 // One compact offscreen contest per school; no per-frame world work.
 for(let j=0;j<W.schools.length;j+=2){const left=W.schools[j],right=W.schools[(j+1+(S.day%3)*2)%W.schools.length];if(left===right)continue;const win=M.rng()<left.strength/(left.strength+right.strength)?left:right,lose=win===left?right:left;win.wins++;lose.losses++;win.rankPoints+=6;lose.rankPoints=Math.max(0,lose.rankPoints-4);win.fame+=3;const v=M.pick(lose.roster.filter(fighting)),killer=M.pick(win.roster.filter(fighting));if(v&&killer){v.fights++;killer.fights++;killer.wins++;v.losses++;for(const [g,won]of [[v,false],[killer,true]]){const w=M.gear(g,'secondary')||M.gear(g,'weapon'),h=weaponHistory(w);if(h){h.fights++;if(won)h.wins++;}if(w)M.addLearning(g,'weapons',w.def,.015);}if(M.rng()<.22){const part=M.pick(Object.keys(v.body));v.body[part].hp=Math.max(10,v.body[part].hp-M.rnd(8,30));v.body[part].injury='Verletzung gegen '+win.name;M.recordWound(v,part,'Arenaverletzung',killer.name,'Offscreen-Kampf',15);}if(M.rng()<.006){v.dead=true;v.cause='Gefallen gegen '+killer.name;remember(v);addWeaponKill(M.gear(killer,'secondary')||M.gear(killer,'weapon'),killer,v);killer.kills++;}M.addLearning(killer,'stats','experience',.025);}}
 for(const s of W.schools){const departed=s.roster.filter(g=>g.dead||g.retired);for(const g of departed){remember(g);W.people[g.id].social=M.copy(social(g));for(const i of items(g))if(i.kind==='weapon')W.weapons[i.id]=M.copy(i);}s.roster=s.roster.filter(g=>!g.dead&&!g.retired);rebuild(s);}
 teamIds();const pairs=new Set();for(const t of S.teams)for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++){const key=[t[i],t[j]].sort().join('|');if(pairs.has(key))continue;pairs.add(key);const a=S.roster.find(g=>g.id===t[i]),b=S.roster.find(g=>g.id===t[j]);if(!a||!b)continue;for(const [g,other]of [[a,b],[b,a]]){const r=social(g).bonds[other.id]??={id:other.id,name:other.name,value:0,shared:0};r.value=Math.min(100,r.value+.025);}}
 for(const g of S.roster){remember(g);const so=social(g);if(so.griefUntil&&so.griefUntil>=S.day)g.stats.morale=Math.min(g.caps.stats.morale,g.stats.morale+1);}syncOwners();log('Die Schulen haben trainiert, sich erholt und ihre Aufstellungen aktualisiert.');}
const day=A.nextDay;A.nextDay=()=>{if(S.battle)return day();const batch=M.batchSaving;M.batchSaving=true;try{const result=day();npcDay();return result;}finally{M.batchSaving=batch;M.persist();}};M.advanceDay=A.nextDay;
const oldDelete=A.deleteTeam;A.deleteTeam=i=>{const p=S.teamPlans[i??S.teamIndex];if(p&&!S.battle){teamIds();W.teams[p.id].active=false;W.teams[p.id].ended=S.day;}const r=oldDelete(i);teamIds();return r;};
const oldEquip=M.equip;M.equip=(...args)=>{const r=oldEquip(...args);syncOwners();M.persist();return r;};const oldSell=M.sellItem;M.sellItem=id=>{const i=M.inventoryItem(id);if(i&&!M.equippedBy(id)){ownership(i,null);if(weaponHistory(i))W.weapons[id]=M.copy(i);}return oldSell(id);};
const oldStats=M.itemStats;M.itemStats=i=>{const v=oldStats(i);if(v&&i.kind==='weapon')v.damage*=1+(i.story?.stage===2?.10:i.story?.stage===1?.05:0);return v;};const oldTitle=M.itemTitle,oldName=M.itemName;M.itemTitle=i=>i?.story?.name||oldTitle(i);M.itemName=i=>i?.story?.name?i.story.name+' · '+M.gearQuality[i.q]+' · Legende '+(i.story.stage===2?'II':'I'):oldName(i);
Object.assign(M,{world:{muster,school,person,formats,social,bond,bondName,rivalLocation,rivalry,weaponHistory,addWeaponKill,resolveWeapon,ownership,syncOwners,challenge,prices,teamRoster,fighting,npcDay,rebuild,remember,teamIds},worldStart:startStory,worldHarm:onHarm,worldDeath:onDeath,worldFinish:beforeFinish,worldLoot:lootTransfer,worldPriority:socialPriority,worldCombatBonus:a=>Math.min(.03,(a.friendBonus||0)+(a.g.social?.rivals[a.target]?.id?.length? .01:0))});
})();
